services:
  postgres:
    image: postgres:17
    container_name: gnome-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - gnome_db_data:/var/lib/postgresql/data

volumes:
  gnome_db_data:
    external: true
