defmodule GnomeGarden.Repo.Migrations.AddWorkflowToOpportunities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:opportunities) do
      modify :stage, :text, null: false
      add :workflow, :text
    end
  end

  def down do
    alter table(:opportunities) do
      remove :workflow
      modify :stage, :text, null: true
    end
  end
end
