defmodule GnomeGarden.Repo.Migrations.TaskContextLinksAndAccountability do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :created_by_team_member_id,
          references(:team_members,
            column: :id,
            name: "tasks_created_by_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :assigned_by_team_member_id,
          references(:team_members,
            column: :id,
            name: "tasks_assigned_by_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :project_id,
          references(:execution_projects,
            column: :id,
            name: "tasks_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :work_item_id,
          references(:execution_work_items,
            column: :id,
            name: "tasks_work_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :work_order_id,
          references(:execution_work_orders,
            column: :id,
            name: "tasks_work_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :bid_id,
          references(:bids,
            column: :id,
            name: "tasks_bid_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :procurement_source_id,
          references(:procurement_sources,
            column: :id,
            name: "tasks_procurement_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:tasks, "tasks_created_by_team_member_id_fkey")

    drop constraint(:tasks, "tasks_assigned_by_team_member_id_fkey")

    drop constraint(:tasks, "tasks_project_id_fkey")

    drop constraint(:tasks, "tasks_work_item_id_fkey")

    drop constraint(:tasks, "tasks_work_order_id_fkey")

    drop constraint(:tasks, "tasks_bid_id_fkey")

    drop constraint(:tasks, "tasks_procurement_source_id_fkey")

    alter table(:tasks) do
      remove :procurement_source_id
      remove :bid_id
      remove :work_order_id
      remove :work_item_id
      remove :project_id
      remove :assigned_by_team_member_id
      remove :created_by_team_member_id
    end
  end
end
