defmodule GnomeGarden.Repo.Migrations.GovernProcurementSourcePortfolio do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:procurement_sources) do
      add :portfolio_decision, :text, null: false, default: "defer"
      add :expected_coverage, :text
      add :adapter_owner, :text
      add :launch_prerequisites, {:array, :text}, null: false, default: []
      add :compliance_decision, :text, null: false, default: "defer"
      add :allowed_retrieval_paths, {:array, :text}, null: false, default: []
      add :terms_url, :text
      add :robots_policy, :text
      add :authentication_policy, :text
      add :retention_days, :bigint
      add :rate_limit_per_day, :bigint
      add :policy_reviewed_at, :utc_datetime
      add :governance_notes, :text
      add :deferred_until, :utc_datetime
      add :defer_reason, :text
      add :last_health_action, :text
      add :health_action_reason, :text
      add :health_action_at, :utc_datetime
    end
  end

  def down do
    alter table(:procurement_sources) do
      remove :health_action_at
      remove :health_action_reason
      remove :last_health_action
      remove :defer_reason
      remove :deferred_until
      remove :governance_notes
      remove :policy_reviewed_at
      remove :rate_limit_per_day
      remove :retention_days
      remove :authentication_policy
      remove :robots_policy
      remove :terms_url
      remove :allowed_retrieval_paths
      remove :compliance_decision
      remove :launch_prerequisites
      remove :adapter_owner
      remove :expected_coverage
      remove :portfolio_decision
    end
  end
end
