defmodule GnomeGarden.Repo.Migrations.AddAgentWorkflowDefinitions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_workflow_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :version, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "draft"
      add :lua_source, :text, null: false
      add :input_schema, :map, null: false, default: %{}
      add :output_schema, :map, null: false, default: %{}
      add :allowed_domains, {:array, :text}, null: false, default: []
      add :allowed_actions, {:array, :text}, null: false, default: []
      add :allowed_tools, {:array, :text}, null: false, default: []
      add :risk_level, :text, null: false, default: "medium"
      add :validated_at, :utc_datetime
      add :published_at, :utc_datetime
      add :disabled_at, :utc_datetime
      add :archived_at, :utc_datetime
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :cloned_from_id,
          references(:agent_workflow_definitions,
            column: :id,
            name: "agent_workflow_definitions_cloned_from_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:agent_workflow_definitions, [:status, :risk_level])

    create index(:agent_workflow_definitions, [:key, :status])

    create unique_index(:agent_workflow_definitions, [:key, :version],
             name: "agent_workflow_definitions_unique_workflow_version_index"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_workflow_definitions, [:key, :version],
                     name: "agent_workflow_definitions_unique_workflow_version_index"
                   )

    drop constraint(:agent_workflow_definitions, "agent_workflow_definitions_cloned_from_id_fkey")

    drop_if_exists index(:agent_workflow_definitions, [:key, :status])

    drop_if_exists index(:agent_workflow_definitions, [:status, :risk_level])

    drop table(:agent_workflow_definitions)
  end
end
