defmodule GnomeGarden.Repo.Migrations.AddLeadSourceStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lead_sources) do
      add :status, :text, default: "candidate", null: false
      modify :portal_id, :text, null: true
    end

    execute """
    UPDATE lead_sources
    SET status = CASE
      WHEN config_status IN ('configured', 'scan_failed', 'manual') THEN 'approved'
      ELSE 'candidate'
    END
    """
  end

  def down do
    alter table(:lead_sources) do
      modify :portal_id, :text, null: false
      remove :status
    end
  end
end
