defmodule GnomeGarden.Repo.Migrations.CompanyRegistrationAndPaymentDestinations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_company_tax_identifiers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :identifier_type, :text, null: false
      add :jurisdiction, :text, null: false
      add :label, :text, null: false, default: "Tax identifier"
      add :encrypted_value, :map
      add :value_fingerprint, :text
      add :value_last4, :text
      add :value_present, :boolean, null: false, default: false
      add :status, :text, null: false, default: "active"
      add :last_rotated_at, :utc_datetime
      add :notes, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_profile_id,
          references(:commercial_company_profiles,
            column: :id,
            name: "commercial_company_tax_identifiers_company_profile_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(
             :commercial_company_tax_identifiers,
             [:company_profile_id, :identifier_type, :jurisdiction],
             name: "company_tax_identifiers_profile_type_jurisdiction_idx"
           )

    create table(:finance_payment_destinations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :label, :text, null: false
      add :provider, :text, null: false, default: "custom"
      add :status, :text, null: false, default: "active"
      add :account_kind, :text, null: false, default: "checking"
      add :beneficiary_name, :text, null: false
      add :beneficiary_address, :map, null: false, default: %{}
      add :bank_name, :text, null: false
      add :bank_address, :map, null: false, default: %{}
      add :domestic_routing_number, :text
      add :wire_routing_number, :text
      add :alternate_routing_number, :text
      add :swift_bic, :text
      add :intermediary_swift_bic, :text
      add :encrypted_account_number, :map
      add :account_number_fingerprint, :text
      add :account_number_last4, :text
      add :account_number_present, :boolean, null: false, default: false
      add :currency_code, :text, null: false, default: "USD"
      add :last_rotated_at, :utc_datetime
      add :notes, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:finance_payment_destinations, [:key],
             name: "finance_payment_destinations_unique_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:finance_payment_destinations, [:key],
                     name: "finance_payment_destinations_unique_key_index"
                   )

    drop table(:finance_payment_destinations)

    drop constraint(
           :commercial_company_tax_identifiers,
           "commercial_company_tax_identifiers_company_profile_id_fkey"
         )

    drop_if_exists unique_index(
                     :commercial_company_tax_identifiers,
                     [:company_profile_id, :identifier_type, :jurisdiction],
                     name: "company_tax_identifiers_profile_type_jurisdiction_idx"
                   )

    drop table(:commercial_company_tax_identifiers)
  end
end
