defmodule GnomeGarden.Repo.Migrations.CreateSalesDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false
      add :pinned, :boolean, default: false
      add :notable_type, :text, null: false
      add :notable_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:industries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :code, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:industries, [:name], name: "industries_unique_name_index")

    create table(:contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :email, :citext
      add :phone, :text
      add :mobile, :text
      add :title, :text
      add :department, :text
      add :role, :text
      add :is_primary, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id, :uuid, null: false
    end

    create table(:companies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:contacts) do
      modify :company_id,
             references(:companies,
               column: :id,
               name: "contacts_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:companies) do
      add :name, :text, null: false
      add :legal_name, :text
      add :company_type, :text, null: false, default: "prospect"
      add :status, :text, null: false, default: "active"
      add :website, :text
      add :phone, :text
      add :address, :text
      add :city, :text
      add :state, :text
      add :postal_code, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :industry_id,
          references(:industries,
            column: :id,
            name: "companies_industry_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:companies, [:name], name: "companies_unique_name_index")

    create table(:activities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :activity_type, :text, null: false
      add :subject, :text, null: false
      add :description, :text
      add :occurred_at, :utc_datetime, null: false
      add :duration_minutes, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:companies,
            column: :id,
            name: "activities_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :contact_id,
          references(:contacts,
            column: :id,
            name: "activities_contact_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:activities, "activities_company_id_fkey")

    drop constraint(:activities, "activities_contact_id_fkey")

    drop table(:activities)

    drop_if_exists unique_index(:companies, [:name], name: "companies_unique_name_index")

    drop constraint(:companies, "companies_industry_id_fkey")

    alter table(:companies) do
      remove :industry_id
      remove :updated_at
      remove :inserted_at
      remove :postal_code
      remove :state
      remove :city
      remove :address
      remove :phone
      remove :website
      remove :status
      remove :company_type
      remove :legal_name
      remove :name
    end

    drop constraint(:contacts, "contacts_company_id_fkey")

    alter table(:contacts) do
      modify :company_id, :uuid
    end

    drop table(:companies)

    drop table(:contacts)

    drop_if_exists unique_index(:industries, [:name], name: "industries_unique_name_index")

    drop table(:industries)

    drop table(:notes)
  end
end
