defmodule GnomeGarden.Repo.Migrations.AddChangeOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_change_order_lines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :line_number, :bigint, null: false, default: 1
      add :line_kind, :text, null: false, default: "other"
      add :description, :text, null: false
      add :quantity, :decimal, null: false
      add :unit_price, :decimal, null: false
      add :line_total, :decimal, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :change_order_id, :uuid, null: false
    end

    create table(:commercial_change_orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:commercial_change_order_lines) do
      modify :change_order_id,
             references(:commercial_change_orders,
               column: :id,
               name: "commercial_change_order_lines_change_order_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:commercial_change_order_lines, [:change_order_id, :line_number],
             name: "ccol_change_order_line_no_idx"
           )

    alter table(:commercial_change_orders) do
      add :change_order_number, :text, null: false
      add :title, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "draft"
      add :change_type, :text, null: false, default: "scope_addition"
      add :pricing_model, :text, null: false, default: "fixed_fee"
      add :requested_on, :date
      add :approved_on, :date
      add :implemented_on, :date
      add :effective_on, :date
      add :schedule_impact_days, :bigint
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "commercial_change_orders_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :project_id,
          references(:execution_projects,
            column: :id,
            name: "commercial_change_orders_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "commercial_change_orders_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :site_id,
          references(:sites,
            column: :id,
            name: "commercial_change_orders_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :managed_system_id,
          references(:managed_systems,
            column: :id,
            name: "commercial_change_orders_managed_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "commercial_change_orders_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:commercial_change_orders, [:change_order_number],
             name: "commercial_change_orders_unique_change_order_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(:commercial_change_orders, [:change_order_number],
                     name: "commercial_change_orders_unique_change_order_number_index"
                   )

    drop constraint(:commercial_change_orders, "commercial_change_orders_agreement_id_fkey")

    drop constraint(:commercial_change_orders, "commercial_change_orders_project_id_fkey")

    drop constraint(:commercial_change_orders, "commercial_change_orders_organization_id_fkey")

    drop constraint(:commercial_change_orders, "commercial_change_orders_site_id_fkey")

    drop constraint(:commercial_change_orders, "commercial_change_orders_managed_system_id_fkey")

    drop constraint(:commercial_change_orders, "commercial_change_orders_owner_user_id_fkey")

    alter table(:commercial_change_orders) do
      remove :owner_user_id
      remove :managed_system_id
      remove :site_id
      remove :organization_id
      remove :project_id
      remove :agreement_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :schedule_impact_days
      remove :effective_on
      remove :implemented_on
      remove :approved_on
      remove :requested_on
      remove :pricing_model
      remove :change_type
      remove :status
      remove :description
      remove :title
      remove :change_order_number
    end

    drop_if_exists unique_index(:commercial_change_order_lines, [:change_order_id, :line_number],
                     name: "ccol_change_order_line_no_idx"
                   )

    drop constraint(
           :commercial_change_order_lines,
           "commercial_change_order_lines_change_order_id_fkey"
         )

    alter table(:commercial_change_order_lines) do
      modify :change_order_id, :uuid
    end

    drop table(:commercial_change_orders)

    drop table(:commercial_change_order_lines)
  end
end
