defmodule GnomeGarden.Repo.Migrations.AddCompanyDocumentStorage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:company_document_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :blob_id, :uuid, null: false
      add :company_document_id, :uuid
    end

    create table(:company_document_blobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:company_document_attachments) do
      modify :blob_id,
             references(:company_document_blobs,
               column: :id,
               name: "company_document_attachments_blob_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :company_document_id,
             references(:company_documents,
               column: :id,
               name: "company_document_attachments_company_document_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:company_document_blobs) do
      add :key, :text, null: false
      add :filename, :text, null: false
      add :content_type, :text
      add :byte_size, :bigint
      add :checksum, :text
      add :service_name, :text, null: false
      add :service_opts, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}
      add :analyzers, :map, null: false, default: %{}
      add :pending_purge, :boolean, null: false, default: false
      add :pending_analyzers, :boolean, null: false, default: false
      add :pending_variants, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:company_document_blobs, [:key],
             name: "company_document_blobs_unique_storage_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:company_document_blobs, [:key],
                     name: "company_document_blobs_unique_storage_key_index"
                   )

    alter table(:company_document_blobs) do
      remove :updated_at
      remove :inserted_at
      remove :pending_variants
      remove :pending_analyzers
      remove :pending_purge
      remove :analyzers
      remove :metadata
      remove :service_opts
      remove :service_name
      remove :checksum
      remove :byte_size
      remove :content_type
      remove :filename
      remove :key
    end

    drop constraint(:company_document_attachments, "company_document_attachments_blob_id_fkey")

    drop constraint(
           :company_document_attachments,
           "company_document_attachments_company_document_id_fkey"
         )

    alter table(:company_document_attachments) do
      modify :company_document_id, :uuid
      modify :blob_id, :uuid
    end

    drop table(:company_document_blobs)

    drop table(:company_document_attachments)
  end
end
