defmodule GnomeGarden.Repo.Migrations.CrmSchemaUpdate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :due_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :priority, :text, default: "normal"
      add :status, :text, default: "pending"
      add :task_type, :text
      add :related_to_type, :text
      add :related_to_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "tasks_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :company_id,
          references(:companies,
            column: :id,
            name: "tasks_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :contact_id,
          references(:contacts,
            column: :id,
            name: "tasks_contact_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:prospects) do
      add :converted_company_id,
          references(:companies,
            column: :id,
            name: "prospects_converted_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :converted_lead_id, :uuid
    end

    create table(:opportunities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :stage, :text, default: "discovery"
      add :amount, :decimal
      add :probability, :bigint, default: 10
      add :expected_close_date, :date
      add :actual_close_date, :date
      add :source, :text
      add :loss_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "opportunities_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :company_id,
          references(:companies,
            column: :id,
            name: "opportunities_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :primary_contact_id,
          references(:contacts,
            column: :id,
            name: "opportunities_primary_contact_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :bid_id,
          references(:bids,
            column: :id,
            name: "opportunities_bid_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:notes) do
      add :created_by_id,
          references(:users,
            column: :id,
            name: "notes_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:leads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:prospects) do
      modify :converted_lead_id,
             references(:leads,
               column: :id,
               name: "prospects_converted_lead_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:leads) do
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :email, :citext
      add :phone, :text
      add :title, :text
      add :company_name, :text
      add :status, :text, default: "new"
      add :source, :text
      add :source_details, :text
      add :converted_at, :utc_datetime
      add :converted_company_id, :uuid
      add :converted_contact_id, :uuid
      add :converted_opportunity_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "leads_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :prospect_id,
          references(:prospects,
            column: :id,
            name: "leads_prospect_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:contacts) do
      add :status, :text, default: "active"
      add :linkedin_url, :text
      add :preferred_contact_method, :text
      add :do_not_call, :boolean, default: false
      add :do_not_email, :boolean, default: false
      add :last_contacted_at, :utc_datetime

      add :owner_id,
          references(:users,
            column: :id,
            name: "contacts_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :address_id,
          references(:addresses,
            column: :id,
            name: "contacts_address_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:companies) do
      add :description, :text
      add :employee_count, :bigint
      add :annual_revenue, :decimal
      add :region, :text
      add :source, :text

      add :owner_id,
          references(:users,
            column: :id,
            name: "companies_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :primary_contact_id,
          references(:contacts,
            column: :id,
            name: "companies_primary_contact_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:bids) do
      remove :assigned_to

      add :owner_id,
          references(:users,
            column: :id,
            name: "bids_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :opportunity_id,
          references(:opportunities,
            column: :id,
            name: "bids_opportunity_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :agency_company_id,
          references(:companies,
            column: :id,
            name: "bids_agency_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:activities) do
      add :direction, :text
      add :outcome, :text

      add :owner_id,
          references(:users,
            column: :id,
            name: "activities_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:activities, "activities_owner_id_fkey")

    alter table(:activities) do
      remove :owner_id
      remove :outcome
      remove :direction
    end

    drop constraint(:bids, "bids_owner_id_fkey")

    drop constraint(:bids, "bids_opportunity_id_fkey")

    drop constraint(:bids, "bids_agency_company_id_fkey")

    alter table(:bids) do
      remove :agency_company_id
      remove :opportunity_id
      remove :owner_id
      add :assigned_to, :text
    end

    drop constraint(:companies, "companies_owner_id_fkey")

    drop constraint(:companies, "companies_primary_contact_id_fkey")

    alter table(:companies) do
      remove :primary_contact_id
      remove :owner_id
      remove :source
      remove :region
      remove :annual_revenue
      remove :employee_count
      remove :description
    end

    drop constraint(:contacts, "contacts_owner_id_fkey")

    drop constraint(:contacts, "contacts_address_id_fkey")

    alter table(:contacts) do
      remove :address_id
      remove :owner_id
      remove :last_contacted_at
      remove :do_not_email
      remove :do_not_call
      remove :preferred_contact_method
      remove :linkedin_url
      remove :status
    end

    drop constraint(:leads, "leads_owner_id_fkey")

    drop constraint(:leads, "leads_prospect_id_fkey")

    alter table(:leads) do
      remove :prospect_id
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :converted_opportunity_id
      remove :converted_contact_id
      remove :converted_company_id
      remove :converted_at
      remove :source_details
      remove :source
      remove :status
      remove :company_name
      remove :title
      remove :phone
      remove :email
      remove :last_name
      remove :first_name
    end

    drop constraint(:prospects, "prospects_converted_lead_id_fkey")

    alter table(:prospects) do
      modify :converted_lead_id, :uuid
    end

    drop table(:leads)

    drop constraint(:notes, "notes_created_by_id_fkey")

    alter table(:notes) do
      remove :created_by_id
    end

    drop constraint(:opportunities, "opportunities_owner_id_fkey")

    drop constraint(:opportunities, "opportunities_company_id_fkey")

    drop constraint(:opportunities, "opportunities_primary_contact_id_fkey")

    drop constraint(:opportunities, "opportunities_bid_id_fkey")

    drop table(:opportunities)

    drop constraint(:prospects, "prospects_converted_company_id_fkey")

    alter table(:prospects) do
      remove :converted_lead_id
      remove :converted_company_id
    end

    drop constraint(:tasks, "tasks_owner_id_fkey")

    drop constraint(:tasks, "tasks_company_id_fkey")

    drop constraint(:tasks, "tasks_contact_id_fkey")

    drop table(:tasks)
  end
end
