defmodule GnomeGarden.Repo.Migrations.CreateCompanyDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:company_documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :category, :text, null: false, default: "other"
      add :version, :text, null: false, default: "1.0"
      add :file_path, :text, null: false
      add :status, :text, null: false, default: "active"
      add :expiry_date, :date
      add :supersedes_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:document_send_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :company_document_id,
          references(:company_documents,
            column: :id,
            name: "document_send_logs_company_document_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :organization_id, :uuid
      add :sent_to_email, :text, null: false
      add :sent_by_user_id, :uuid, null: false
      add :message, :text
      add :sent_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:document_send_logs, "document_send_logs_company_document_id_fkey")

    drop table(:document_send_logs)

    drop table(:company_documents)
  end
end
