defmodule GnomeGarden.Repo.Migrations.AddOperationalFinance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:finance_invoices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :invoice_number, :text
      add :status, :text, null: false, default: "draft"
      add :currency_code, :text, null: false, default: "USD"
      add :subtotal, :decimal
      add :tax_total, :decimal
      add :total_amount, :decimal
      add :balance_amount, :decimal
      add :issued_on, :date
      add :due_on, :date
      add :paid_on, :date
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "finance_invoices_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "finance_invoices_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :project_id,
          references(:execution_projects,
            column: :id,
            name: "finance_invoices_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :work_order_id,
          references(:execution_work_orders,
            column: :id,
            name: "finance_invoices_work_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:finance_time_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :work_date, :date, null: false
      add :minutes, :bigint, null: false
      add :description, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :billable, :boolean, null: false, default: true
      add :bill_rate, :decimal
      add :cost_rate, :decimal
      add :approved_at, :utc_datetime
      add :billed_at, :utc_datetime
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "finance_time_entries_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "finance_time_entries_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :project_id,
          references(:execution_projects,
            column: :id,
            name: "finance_time_entries_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :work_item_id,
          references(:execution_work_items,
            column: :id,
            name: "finance_time_entries_work_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :work_order_id,
          references(:execution_work_orders,
            column: :id,
            name: "finance_time_entries_work_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :member_user_id,
          references(:users,
            column: :id,
            name: "finance_time_entries_member_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          ),
          null: false

      add :approved_by_user_id,
          references(:users,
            column: :id,
            name: "finance_time_entries_approved_by_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:finance_expenses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :incurred_on, :date, null: false
      add :category, :text, null: false, default: "other"
      add :description, :text, null: false
      add :amount, :decimal, null: false
      add :vendor, :text
      add :receipt_url, :text
      add :status, :text, null: false, default: "draft"
      add :billable, :boolean, null: false, default: true
      add :approved_at, :utc_datetime
      add :billed_at, :utc_datetime
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "finance_expenses_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "finance_expenses_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :project_id,
          references(:execution_projects,
            column: :id,
            name: "finance_expenses_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :work_order_id,
          references(:execution_work_orders,
            column: :id,
            name: "finance_expenses_work_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :incurred_by_user_id,
          references(:users,
            column: :id,
            name: "finance_expenses_incurred_by_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          ),
          null: false

      add :approved_by_user_id,
          references(:users,
            column: :id,
            name: "finance_expenses_approved_by_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:finance_expenses, "finance_expenses_organization_id_fkey")

    drop constraint(:finance_expenses, "finance_expenses_agreement_id_fkey")

    drop constraint(:finance_expenses, "finance_expenses_project_id_fkey")

    drop constraint(:finance_expenses, "finance_expenses_work_order_id_fkey")

    drop constraint(:finance_expenses, "finance_expenses_incurred_by_user_id_fkey")

    drop constraint(:finance_expenses, "finance_expenses_approved_by_user_id_fkey")

    drop table(:finance_expenses)

    drop constraint(:finance_time_entries, "finance_time_entries_organization_id_fkey")

    drop constraint(:finance_time_entries, "finance_time_entries_agreement_id_fkey")

    drop constraint(:finance_time_entries, "finance_time_entries_project_id_fkey")

    drop constraint(:finance_time_entries, "finance_time_entries_work_item_id_fkey")

    drop constraint(:finance_time_entries, "finance_time_entries_work_order_id_fkey")

    drop constraint(:finance_time_entries, "finance_time_entries_member_user_id_fkey")

    drop constraint(:finance_time_entries, "finance_time_entries_approved_by_user_id_fkey")

    drop table(:finance_time_entries)

    drop constraint(:finance_invoices, "finance_invoices_organization_id_fkey")

    drop constraint(:finance_invoices, "finance_invoices_agreement_id_fkey")

    drop constraint(:finance_invoices, "finance_invoices_project_id_fkey")

    drop constraint(:finance_invoices, "finance_invoices_work_order_id_fkey")

    drop table(:finance_invoices)
  end
end
