defmodule GnomeGarden.Repo.Migrations.AutomationTimeTriggers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:automation_rules) do
      add :cloned_from_rule_id,
          references(:automation_rules,
            column: :id,
            name: "automation_rules_cloned_from_rule_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:automation_events) do
      add :dedupe_key, :text
    end

    create unique_index(:automation_events, [:dedupe_key],
             name: "automation_events_unique_dedupe_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:automation_events, [:dedupe_key],
                     name: "automation_events_unique_dedupe_key_index"
                   )

    alter table(:automation_events) do
      remove :dedupe_key
    end

    drop constraint(:automation_rules, "automation_rules_cloned_from_rule_id_fkey")

    alter table(:automation_rules) do
      remove :cloned_from_rule_id
    end
  end
end
