defmodule GnomeGarden.Repo.Migrations.AddOperationsFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text
      add :name, :text, null: false
      add :site_kind, :text, null: false, default: "facility"
      add :status, :text, null: false, default: "active"
      add :address1, :text
      add :address2, :text
      add :city, :text
      add :state, :text
      add :postal_code, :text
      add :country_code, :text
      add :timezone, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id, :uuid, null: false
    end

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sites) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "sites_organization_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:sites, [:organization_id, :name],
             name: "sites_unique_name_per_organization_index"
           )

    alter table(:organizations) do
      add :name, :text, null: false
      add :legal_name, :text
      add :organization_kind, :text, null: false, default: "business"
      add :status, :text, null: false, default: "prospect"
      add :relationship_roles, {:array, :text}, null: false, default: []
      add :website, :text
      add :phone, :text
      add :primary_region, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:organizations, [:name], name: "organizations_unique_name_index")

    create table(:managed_systems, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text
      add :name, :text, null: false
      add :description, :text
      add :system_type, :text, null: false, default: "hybrid"
      add :delivery_mode, :text, null: false, default: "hybrid"
      add :lifecycle_status, :text, null: false, default: "prospective"
      add :criticality, :text, null: false, default: "normal"
      add :vendor, :text
      add :platform, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "managed_systems_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :site_id,
          references(:sites,
            column: :id,
            name: "managed_systems_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:managed_systems, [:organization_id, :name],
             name: "managed_systems_unique_name_per_organization_index"
           )
  end

  def down do
    drop_if_exists unique_index(:managed_systems, [:organization_id, :name],
                     name: "managed_systems_unique_name_per_organization_index"
                   )

    drop constraint(:managed_systems, "managed_systems_organization_id_fkey")

    drop constraint(:managed_systems, "managed_systems_site_id_fkey")

    drop table(:managed_systems)

    drop_if_exists unique_index(:organizations, [:name], name: "organizations_unique_name_index")

    alter table(:organizations) do
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :primary_region
      remove :phone
      remove :website
      remove :relationship_roles
      remove :status
      remove :organization_kind
      remove :legal_name
      remove :name
    end

    drop_if_exists unique_index(:sites, [:organization_id, :name],
                     name: "sites_unique_name_per_organization_index"
                   )

    drop constraint(:sites, "sites_organization_id_fkey")

    alter table(:sites) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop table(:sites)
  end
end
