defmodule GnomeGarden.Repo.Migrations.AddOriginUniquenessToAcquisitionFindings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:acquisition_findings, [:source_bid_id],
             name: "acquisition_findings_unique_source_bid_index"
           )

    create unique_index(:acquisition_findings, [:source_target_account_id],
             name: "acquisition_findings_unique_source_target_account_index"
           )
  end

  def down do
    drop_if_exists unique_index(:acquisition_findings, [:source_target_account_id],
                     name: "acquisition_findings_unique_source_target_account_index"
                   )

    drop_if_exists unique_index(:acquisition_findings, [:source_bid_id],
                     name: "acquisition_findings_unique_source_bid_index"
                   )
  end
end
