defmodule GnomeGarden.Repo.Migrations.AddPursuitLinksToSalesFollowups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      modify :status, :text, null: false

      add :pursuit_id,
          references(:commercial_pursuits,
            column: :id,
            name: "tasks_pursuit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:leads) do
      modify :status, :text, null: false
    end

    alter table(:activities) do
      add :pursuit_id,
          references(:commercial_pursuits,
            column: :id,
            name: "activities_pursuit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:activities, "activities_pursuit_id_fkey")

    alter table(:activities) do
      remove :pursuit_id
    end

    alter table(:leads) do
      modify :status, :text, null: true
    end

    drop constraint(:tasks, "tasks_pursuit_id_fkey")

    alter table(:tasks) do
      remove :pursuit_id
      modify :status, :text, null: true
    end
  end
end
