defmodule GnomeGarden.Repo.Migrations.AddTargetAccountDiscoveryModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_target_observations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :observation_type, :text, null: false, default: "other"
      add :source_channel, :text, null: false, default: "agent_discovery"
      add :external_ref, :text
      add :source_url, :text
      add :observed_at, :utc_datetime
      add :confidence_score, :bigint, null: false, default: 50
      add :summary, :text, null: false
      add :raw_excerpt, :text
      add :evidence_points, {:array, :text}, null: false, default: []
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :target_account_id, :uuid, null: false
    end

    create table(:commercial_target_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:commercial_target_observations) do
      modify :target_account_id,
             references(:commercial_target_accounts,
               column: :id,
               name: "commercial_target_observations_target_account_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:commercial_target_observations, [:external_ref],
             name: "commercial_target_observations_unique_external_ref_index"
           )

    alter table(:commercial_target_accounts) do
      add :name, :text, null: false
      add :website, :text
      add :website_domain, :text
      add :location, :text
      add :region, :text
      add :industry, :text
      add :size_bucket, :text
      add :fit_score, :bigint, null: false, default: 50
      add :intent_score, :bigint, null: false, default: 50
      add :status, :text, null: false, default: "new"
      add :promoted_at, :utc_datetime
      add :notes, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "commercial_target_accounts_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "commercial_target_accounts_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :promoted_signal_id,
          references(:commercial_signals,
            column: :id,
            name: "commercial_target_accounts_promoted_signal_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:commercial_target_accounts, [:name, :location],
             name: "commercial_target_accounts_unique_name_location_index"
           )

    create unique_index(:commercial_target_accounts, [:website_domain],
             name: "commercial_target_accounts_unique_website_domain_index"
           )
  end

  def down do
    drop_if_exists unique_index(:commercial_target_accounts, [:website_domain],
                     name: "commercial_target_accounts_unique_website_domain_index"
                   )

    drop_if_exists unique_index(:commercial_target_accounts, [:name, :location],
                     name: "commercial_target_accounts_unique_name_location_index"
                   )

    drop constraint(
           :commercial_target_accounts,
           "commercial_target_accounts_organization_id_fkey"
         )

    drop constraint(:commercial_target_accounts, "commercial_target_accounts_owner_user_id_fkey")

    drop constraint(
           :commercial_target_accounts,
           "commercial_target_accounts_promoted_signal_id_fkey"
         )

    alter table(:commercial_target_accounts) do
      remove :promoted_signal_id
      remove :owner_user_id
      remove :organization_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :notes
      remove :promoted_at
      remove :status
      remove :intent_score
      remove :fit_score
      remove :size_bucket
      remove :industry
      remove :region
      remove :location
      remove :website_domain
      remove :website
      remove :name
    end

    drop_if_exists unique_index(:commercial_target_observations, [:external_ref],
                     name: "commercial_target_observations_unique_external_ref_index"
                   )

    drop constraint(
           :commercial_target_observations,
           "commercial_target_observations_target_account_id_fkey"
         )

    alter table(:commercial_target_observations) do
      modify :target_account_id, :uuid
    end

    drop table(:commercial_target_accounts)

    drop table(:commercial_target_observations)
  end
end
