defmodule GnomeGarden.Repo.Migrations.AddLeadPreviewRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_lead_preview_candidates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :url, :text, null: false
      add :website_domain, :text
      add :query, :text
      add :published_date, :text
      add :candidate_type, :text
      add :dedupe_context, :text
      add :route, :text
      add :suppressed, :boolean, default: false
      add :recommendation, :text
      add :rank, :bigint
      add :status, :text, null: false, default: "pending"
      add :promoted_record_id, :uuid
      add :promoted_at, :utc_datetime
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :lead_preview_run_id, :uuid, null: false
    end

    create table(:acquisition_lead_preview_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:acquisition_lead_preview_candidates) do
      modify :lead_preview_run_id,
             references(:acquisition_lead_preview_runs,
               column: :id,
               name: "acquisition_lead_preview_candidates_lead_preview_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:acquisition_lead_preview_runs) do
      add :source, :text, null: false, default: "exa"
      add :status, :text, null: false, default: "completed"
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
      add :query_count, :bigint, default: 0
      add :candidate_count, :bigint, default: 0
      add :promotable_count, :bigint, default: 0
      add :needs_enrichment_count, :bigint, default: 0
      add :suppressed_count, :bigint, default: 0
      add :total_cost, :decimal, default: "0"
      add :errors, {:array, :text}, default: []
      add :metadata, :map, default: %{}
      add :discovery_program_id, :uuid
      add :created_by_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:acquisition_lead_preview_runs) do
      remove :updated_at
      remove :inserted_at
      remove :created_by_id
      remove :discovery_program_id
      remove :metadata
      remove :errors
      remove :total_cost
      remove :suppressed_count
      remove :needs_enrichment_count
      remove :promotable_count
      remove :candidate_count
      remove :query_count
      remove :finished_at
      remove :started_at
      remove :status
      remove :source
    end

    drop constraint(
           :acquisition_lead_preview_candidates,
           "acquisition_lead_preview_candidates_lead_preview_run_id_fkey"
         )

    alter table(:acquisition_lead_preview_candidates) do
      modify :lead_preview_run_id, :uuid
    end

    drop table(:acquisition_lead_preview_runs)

    drop table(:acquisition_lead_preview_candidates)
  end
end
