defmodule GnomeGarden.Repo.Migrations.UpdateAgentMessageRunDeleteCascade do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:agent_messages, "agent_messages_agent_run_id_fkey")

    alter table(:agent_messages) do
      modify :agent_run_id,
             references(:agent_runs,
               column: :id,
               name: "agent_messages_agent_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:agent_messages, "agent_messages_agent_run_id_fkey")

    alter table(:agent_messages) do
      modify :agent_run_id,
             references(:agent_runs,
               column: :id,
               name: "agent_messages_agent_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
