defmodule GnomeGarden.Repo.Migrations.MercuryBankRulesAndEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mercury_bank_rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :priority, :bigint, null: false, default: 0
      add :direction, :text, null: false
      add :counterparty_contains, :text
      add :amount_operator, :text
      add :amount_value, :decimal
      add :reconciliation_category, :text, null: false
      add :auto_note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:mercury_alias_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :actor_id, :uuid
      add :counterparty_name_fragment, :text, null: false
      add :organization_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:mercury_transactions) do
      add :reconciliation_note, :text
      add :reconciliation_category, :text
    end

    create table(:mercury_transaction_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :actor_id, :uuid
      add :amount, :decimal
      add :invoice_ids, {:array, :uuid}, default: []
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :mercury_transaction_id,
          references(:mercury_transactions,
            column: :id,
            name: "mercury_transaction_events_mercury_transaction_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end
  end

  def down do
    drop constraint(
           :mercury_transaction_events,
           "mercury_transaction_events_mercury_transaction_id_fkey"
         )

    drop table(:mercury_transaction_events)

    alter table(:mercury_transactions) do
      remove :reconciliation_category
      remove :reconciliation_note
    end

    drop table(:mercury_alias_events)

    drop table(:mercury_bank_rules)
  end
end
