defmodule GnomeGarden.Repo.Migrations.AddAgentRunOutputs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_run_outputs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :output_type, :text, null: false
      add :output_id, :uuid, null: false
      add :event, :text, null: false
      add :label, :text, null: false
      add :summary, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "agent_run_outputs_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:agent_run_outputs, [:agent_run_id, :output_type, :output_id, :event],
             name: "agent_run_outputs_unique_output_event_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :agent_run_outputs,
                     [:agent_run_id, :output_type, :output_id, :event],
                     name: "agent_run_outputs_unique_output_event_index"
                   )

    drop constraint(:agent_run_outputs, "agent_run_outputs_agent_run_id_fkey")

    drop table(:agent_run_outputs)
  end
end
