defmodule GnomeGarden.Repo.Migrations.DiscoveryFeedbackLearning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:acquisition_lead_preview_runs) do
      add :program_source_id,
          references(:acquisition_program_sources,
            column: :id,
            name: "acquisition_lead_preview_runs_program_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    execute("""
    UPDATE acquisition_lead_preview_runs
    SET program_source_id = (metadata->>'program_source_id')::uuid
    WHERE program_source_id IS NULL
      AND metadata->>'program_source_id' IS NOT NULL
      AND metadata->>'program_source_id' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
      AND EXISTS (
        SELECT 1
        FROM acquisition_program_sources
        WHERE acquisition_program_sources.id = (metadata->>'program_source_id')::uuid
      )
    """)

    create index(:acquisition_lead_preview_runs, [:program_source_id, :inserted_at],
             name: "lead_preview_runs_program_source_inserted_index"
           )
  end

  def down do
    drop_if_exists index(:acquisition_lead_preview_runs, [:program_source_id, :inserted_at],
                     name: "lead_preview_runs_program_source_inserted_index"
                   )

    drop constraint(
           :acquisition_lead_preview_runs,
           "acquisition_lead_preview_runs_program_source_id_fkey"
         )

    alter table(:acquisition_lead_preview_runs) do
      remove :program_source_id
    end
  end
end
