defmodule GnomeGarden.Repo.Migrations.AddTaxRateToInvoices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:finance_invoices) do
      add :tax_rate, :decimal, null: false, default: "0"
    end
  end

  def down do
    alter table(:finance_invoices) do
      remove :tax_rate
    end
  end
end
