defmodule GnomeGarden.Repo.Migrations.AddBillingLoopFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:commercial_agreements) do
      add :billing_cycle, :text, null: false, default: "none"
      add :next_billing_date, :date
    end

    alter table(:mercury_transactions) do
      add :match_confidence, :text
    end

    create table(:mercury_client_bank_aliases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :counterparty_name_fragment, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "mercury_client_bank_aliases_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:mercury_client_bank_aliases, [:counterparty_name_fragment],
             name: "mercury_client_bank_aliases_unique_counterparty_fragment_index"
           )
  end

  def down do
    drop_if_exists unique_index(:mercury_client_bank_aliases, [:counterparty_name_fragment],
                     name: "mercury_client_bank_aliases_unique_counterparty_fragment_index"
                   )

    drop constraint(
           :mercury_client_bank_aliases,
           "mercury_client_bank_aliases_organization_id_fkey"
         )

    drop table(:mercury_client_bank_aliases)

    alter table(:mercury_transactions) do
      remove :match_confidence
    end

    alter table(:commercial_agreements) do
      remove :next_billing_date
      remove :billing_cycle
    end
  end
end
