defmodule GnomeGarden.Repo.Migrations.GrowthFlywheelHardening do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bids) do
      add :capability_gaps_recorded_at, :utc_datetime
    end

    alter table(:operations_learning_recommendations) do
      add :dedupe_key, :text
    end

    create unique_index(:operations_learning_recommendations, [:dedupe_key],
             name: "operations_learning_recommendations_unique_dedupe_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:operations_learning_recommendations, [:dedupe_key],
                     name: "operations_learning_recommendations_unique_dedupe_key_index"
                   )

    alter table(:operations_learning_recommendations) do
      remove :dedupe_key
    end

    alter table(:bids) do
      remove :capability_gaps_recorded_at
    end
  end
end
