defmodule GnomeGarden.Repo.Migrations.RemoveSalesOpportunities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:research_links) do
      remove :opportunity_id
    end

    alter table(:sales_events) do
      remove :opportunity_id
    end

    alter table(:leads) do
      remove :converted_opportunity_id
    end

    alter table(:activities) do
      remove :opportunity_id
    end

    drop table(:opportunities)
  end

  def down do
    create table(:opportunities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :stage, :text, null: false, default: "discovery"
      add :workflow, :text
      add :amount, :decimal
      add :probability, :bigint, default: 10
      add :expected_close_date, :date
      add :actual_close_date, :date
      add :source, :text
      add :loss_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "opportunities_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :company_id,
          references(:companies,
            column: :id,
            name: "opportunities_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :primary_contact_id,
          references(:contacts,
            column: :id,
            name: "opportunities_primary_contact_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :bid_id,
          references(:bids,
            column: :id,
            name: "opportunities_bid_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:activities) do
      add :opportunity_id,
          references(:opportunities,
            column: :id,
            name: "activities_opportunity_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:leads) do
      add :converted_opportunity_id, :uuid
    end

    alter table(:sales_events) do
      add :opportunity_id,
          references(:opportunities,
            column: :id,
            name: "sales_events_opportunity_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:research_links) do
      add :opportunity_id,
          references(:opportunities,
            column: :id,
            name: "research_links_opportunity_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
