defmodule GnomeGarden.Repo.Migrations.MakeFilePathNullable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:company_documents) do
      modify :file_path, :text, null: true
    end
  end

  def down do
    alter table(:company_documents) do
      modify :file_path, :text, null: false
    end
  end
end
