defmodule GnomeGarden.Repo.Migrations.AddReconciliationCategoryToMercuryTransactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:mercury_transactions) do
      add :reconciliation_category, :text
    end
  end

  def down do
    alter table(:mercury_transactions) do
      remove :reconciliation_category
    end
  end
end
