defmodule GnomeGarden.Repo.Migrations.AddCompanyProfileResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_company_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false, default: "primary"
      add :name, :text, null: false
      add :legal_name, :text
      add :positioning_summary, :text
      add :specialty_summary, :text
      add :voice_summary, :text
      add :core_capabilities, {:array, :text}, null: false, default: []
      add :adjacent_capabilities, {:array, :text}, null: false, default: []
      add :target_industries, {:array, :text}, null: false, default: []
      add :preferred_engagements, {:array, :text}, null: false, default: []
      add :disqualifiers, {:array, :text}, null: false, default: []
      add :voice_principles, {:array, :text}, null: false, default: []
      add :preferred_phrases, {:array, :text}, null: false, default: []
      add :avoid_phrases, {:array, :text}, null: false, default: []
      add :default_profile_mode, :text, null: false, default: "industrial_plus_software"
      add :keyword_profiles, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:commercial_company_profiles, [:key],
             name: "commercial_company_profiles_unique_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:commercial_company_profiles, [:key],
                     name: "commercial_company_profiles_unique_key_index"
                   )

    drop table(:commercial_company_profiles)
  end
end
