defmodule GnomeGarden.Repo.Migrations.RemoveSalesDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:research_links) do
      remove :lead_id
    end

    drop constraint(:research_links, "research_links_event_id_fkey")

    drop_if_exists unique_index(:acquisition_findings, [:source_lead_id],
                     name: "acquisition_findings_unique_source_lead_index"
                   )

    alter table(:acquisition_findings) do
      remove :source_lead_id
    end

    alter table(:activities) do
      remove :lead_id
    end

    rename table(:sales_events), to: table(:commercial_events)

    execute(
      "ALTER TABLE commercial_events RENAME CONSTRAINT sales_events_actor_id_fkey TO commercial_events_actor_id_fkey",
      "ALTER TABLE commercial_events RENAME CONSTRAINT commercial_events_actor_id_fkey TO sales_events_actor_id_fkey"
    )

    execute(
      "ALTER TABLE commercial_events RENAME CONSTRAINT sales_events_organization_id_fkey TO commercial_events_organization_id_fkey",
      "ALTER TABLE commercial_events RENAME CONSTRAINT commercial_events_organization_id_fkey TO sales_events_organization_id_fkey"
    )

    alter table(:research_links) do
      modify :event_id,
             references(:commercial_events,
               column: :id,
               name: "research_links_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop table(:notes)
    drop table(:leads)
  end

  def down do
    raise "Sales domain removal is irreversible"
  end
end
