defmodule GnomeGarden.Repo.Migrations.SourceSearchFilterFeedback do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:procurement_source_search_filter_feedback, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :decision, :text, null: false
      add :reason, :text
      add :reason_code, :text
      add :feedback_scope, :text
      add :source_feedback_category, :text
      add :recorded_at, :utc_datetime
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_search_filter_id,
          references(:procurement_source_search_filters,
            column: :id,
            name: "source_filter_feedback_filter_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :finding_id,
          references(:acquisition_findings,
            column: :id,
            name: "source_filter_feedback_finding_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:procurement_source_search_filter_feedback, [:recorded_at])

    create index(:procurement_source_search_filter_feedback, [:reason_code])

    create index(:procurement_source_search_filter_feedback, [:source_search_filter_id, :decision])

    create unique_index(
             :procurement_source_search_filter_feedback,
             [:source_search_filter_id, :finding_id, :decision],
             name: "source_filter_feedback_unique_idx"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :procurement_source_search_filter_feedback,
                     [:source_search_filter_id, :finding_id, :decision],
                     name: "source_filter_feedback_unique_idx"
                   )

    drop constraint(
           :procurement_source_search_filter_feedback,
           "source_filter_feedback_filter_id_fkey"
         )

    drop constraint(
           :procurement_source_search_filter_feedback,
           "source_filter_feedback_finding_id_fkey"
         )

    drop_if_exists index(:procurement_source_search_filter_feedback, [
                     :source_search_filter_id,
                     :decision
                   ])

    drop_if_exists index(:procurement_source_search_filter_feedback, [:reason_code])

    drop_if_exists index(:procurement_source_search_filter_feedback, [:recorded_at])

    drop table(:procurement_source_search_filter_feedback)
  end
end
