defmodule GnomeGarden.Repo.Migrations.AddIdentityMergeControlsAndMatcherIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :merged_into_id,
          references(:organizations,
            column: :id,
            name: "organizations_merged_into_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:organizations, [:name_key], name: "organizations_name_key_idx")

    create index(:organizations, [:website_domain], name: "organizations_website_domain_idx")

    create index(:commercial_target_accounts, [:website_domain],
             name: "commercial_target_accounts_website_domain_idx"
           )

    alter table(:people) do
      add :merged_into_id,
          references(:people,
            column: :id,
            name: "people_merged_into_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:people, [:name_key, :email_domain], name: "people_name_key_email_domain_idx")

    create index(:people, [:name_key], name: "people_name_key_idx")
  end

  def down do
    drop constraint(:people, "people_merged_into_id_fkey")

    drop_if_exists index(:people, [:name_key], name: "people_name_key_idx")

    drop_if_exists index(:people, [:name_key, :email_domain],
                     name: "people_name_key_email_domain_idx"
                   )

    alter table(:people) do
      remove :merged_into_id
    end

    drop_if_exists index(:commercial_target_accounts, [:website_domain],
                     name: "commercial_target_accounts_website_domain_idx"
                   )

    drop constraint(:organizations, "organizations_merged_into_id_fkey")

    drop_if_exists index(:organizations, [:website_domain],
                     name: "organizations_website_domain_idx"
                   )

    drop_if_exists index(:organizations, [:name_key], name: "organizations_name_key_idx")

    alter table(:organizations) do
      remove :merged_into_id
    end
  end
end
