defmodule GnomeGarden.Repo.Migrations.AddDefaultBillRateToAgreements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:commercial_agreements) do
      add :default_bill_rate, :decimal
    end
  end

  def down do
    alter table(:commercial_agreements) do
      remove :default_bill_rate
    end
  end
end
