defmodule GnomeGarden.Repo.Migrations.AddStripePaymentUrlToInvoices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:finance_invoices) do
      add :stripe_payment_url, :text
    end
  end

  def down do
    alter table(:finance_invoices) do
      remove :stripe_payment_url
    end
  end
end
