defmodule GnomeGarden.Repo.Migrations.AddUniqueInvoiceNumber do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:finance_invoices, [:invoice_number],
             name: "finance_invoices_unique_invoice_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(:finance_invoices, [:invoice_number],
                     name: "finance_invoices_unique_invoice_number_index"
                   )
  end
end
