defmodule GnomeGarden.Repo.Migrations.MoveTasksToOperations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      remove :related_to_id
      remove :related_to_type
    end

    drop constraint(:tasks, "tasks_person_id_fkey")

    drop constraint(:tasks, "tasks_organization_id_fkey")

    alter table(:tasks) do
      modify :task_type, :text, null: false, default: "other"
      modify :priority, :text, null: false
      add :started_at, :utc_datetime
      add :blocked_at, :utc_datetime
      add :blocked_reason, :text
      add :origin_domain, :text, null: false, default: "manual"
      add :origin_resource, :text
      add :origin_id, :uuid
      add :origin_label, :text
      add :origin_url, :text
      add :metadata, :map, default: %{}

      add :finding_id,
          references(:acquisition_findings,
            column: :id,
            name: "tasks_finding_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :signal_id,
          references(:commercial_signals,
            column: :id,
            name: "tasks_signal_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "tasks_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:tasks, [:task_type, :status])

    create index(:tasks, [:origin_domain, :origin_resource, :origin_id])

    create index(:tasks, [:status, :due_at])

    alter table(:tasks) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "tasks_organization_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :person_id,
             references(:people,
               column: :id,
               name: "tasks_person_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end
  end

  def down do
    drop constraint(:tasks, "tasks_finding_id_fkey")

    drop constraint(:tasks, "tasks_signal_id_fkey")

    drop constraint(:tasks, "tasks_agent_run_id_fkey")

    drop constraint(:tasks, "tasks_organization_id_fkey")

    drop constraint(:tasks, "tasks_person_id_fkey")

    alter table(:tasks) do
      modify :person_id,
             references(:people,
               column: :id,
               name: "tasks_person_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "tasks_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:tasks, [:status, :due_at])

    drop_if_exists index(:tasks, [:origin_domain, :origin_resource, :origin_id])

    drop_if_exists index(:tasks, [:task_type, :status])

    alter table(:tasks) do
      remove :agent_run_id
      remove :signal_id
      remove :finding_id
      remove :metadata
      remove :origin_url
      remove :origin_label
      remove :origin_id
      remove :origin_resource
      remove :origin_domain
      remove :blocked_reason
      remove :blocked_at
      remove :started_at
      modify :priority, :text, null: true
      modify :task_type, :text, null: true, default: nil
    end

    alter table(:tasks) do
      add :related_to_type, :text
      add :related_to_id, :uuid
    end
  end
end
