defmodule GnomeGarden.Repo.Migrations.RestrictProgramSourceDeletion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:acquisition_program_sources, "acquisition_program_sources_source_id_fkey")

    drop constraint(:acquisition_program_sources, "acquisition_program_sources_program_id_fkey")

    alter table(:acquisition_program_sources) do
      modify :program_id,
             references(:acquisition_programs,
               column: :id,
               name: "acquisition_program_sources_program_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :source_id,
             references(:acquisition_sources,
               column: :id,
               name: "acquisition_program_sources_source_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end
  end

  def down do
    drop constraint(:acquisition_program_sources, "acquisition_program_sources_program_id_fkey")

    drop constraint(:acquisition_program_sources, "acquisition_program_sources_source_id_fkey")

    alter table(:acquisition_program_sources) do
      modify :source_id,
             references(:acquisition_sources,
               column: :id,
               name: "acquisition_program_sources_source_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :program_id,
             references(:acquisition_programs,
               column: :id,
               name: "acquisition_program_sources_program_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end
end
