defmodule GnomeGarden.Repo.Migrations.AddRecordTypeAndIntegratorRequest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:commercial_discovery_records) do
      add :record_type, :text, null: false, default: "prospect"
    end
  end

  def down do
    alter table(:commercial_discovery_records) do
      remove :record_type
    end
  end
end
