defmodule GnomeGarden.Repo.Migrations.AddServiceLevelPolicies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_service_level_policies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "draft"
      add :severity, :text, null: false, default: "normal"
      add :coverage_mode, :text, null: false, default: "business_hours"
      add :response_target_minutes, :bigint, null: false
      add :resolution_target_minutes, :bigint
      add :business_hours_timezone, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "commercial_service_level_policies_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "commercial_service_level_policies_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:commercial_service_level_policies, [:agreement_id, :severity],
             name: "cslp_agreement_severity_idx"
           )

    alter table(:execution_service_tickets) do
      add :service_level_policy_id,
          references(:commercial_service_level_policies,
            column: :id,
            name: "execution_service_tickets_service_level_policy_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(
           :execution_service_tickets,
           "execution_service_tickets_service_level_policy_id_fkey"
         )

    alter table(:execution_service_tickets) do
      remove :service_level_policy_id
    end

    drop_if_exists unique_index(:commercial_service_level_policies, [:agreement_id, :severity],
                     name: "cslp_agreement_severity_idx"
                   )

    drop constraint(
           :commercial_service_level_policies,
           "commercial_service_level_policies_agreement_id_fkey"
         )

    drop constraint(
           :commercial_service_level_policies,
           "commercial_service_level_policies_organization_id_fkey"
         )

    drop table(:commercial_service_level_policies)
  end
end
