defmodule GnomeGarden.Repo.Migrations.EncryptBrowserSessionCustody do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:procurement_source_browser_sessions) do
      remove :screenshot_path
      remove :trace_path
      remove :storage_state_path
      add :encrypted_storage_state, :map
      add :credential_fingerprint, :text
    end
  end

  def down do
    alter table(:procurement_source_browser_sessions) do
      remove :credential_fingerprint
      remove :encrypted_storage_state
      add :storage_state_path, :text
      add :trace_path, :text
      add :screenshot_path, :text
    end
  end
end
