defmodule GnomeGarden.Repo.Migrations.AddQueueSnapshotFieldsToAcquisitionFinding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:acquisition_findings) do
      add :due_at, :utc_datetime
      add :due_note, :text
      add :location, :text
      add :location_note, :text
      add :work_summary, :text
      add :work_type, :text
      add :work_note, :text
      add :score_tier, :text
      add :score_note, :text
    end
  end

  def down do
    alter table(:acquisition_findings) do
      remove :score_note
      remove :score_tier
      remove :work_note
      remove :work_type
      remove :work_summary
      remove :location_note
      remove :location
      remove :due_note
      remove :due_at
    end
  end
end
