defmodule GnomeGarden.Repo.Migrations.AddRecurringVendorBills do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:finance_recurring_vendor_bills, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :description, :text, null: false
      add :amount, :decimal, null: false
      add :interval, :text, null: false
      add :status, :text, null: false, default: "active"
      add :next_due_on, :date, null: false
      add :end_date, :date
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :vendor_id,
          references(:finance_vendors,
            column: :id,
            name: "finance_recurring_vendor_bills_vendor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end
  end

  def down do
    drop constraint(
           :finance_recurring_vendor_bills,
           "finance_recurring_vendor_bills_vendor_id_fkey"
         )

    drop table(:finance_recurring_vendor_bills)
  end
end
