defmodule GnomeGarden.Repo.Migrations.AddOperationsMemoryBlocks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:operations_memory_blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :label, :text, null: false
      add :description, :text
      add :content, :text, null: false
      add :scope, :text, null: false, default: "global"
      add :scope_key, :text, null: false, default: "global"
      add :memory_type, :text, null: false, default: "context"
      add :status, :text, null: false, default: "draft"
      add :visibility, :text, null: false, default: "agent_context"
      add :read_only, :boolean, null: false, default: false
      add :source_type, :text, null: false, default: "operator"
      add :source_id, :uuid
      add :confidence, :decimal
      add :version, :bigint, null: false, default: 1
      add :metadata, :map, default: %{}
      add :approved_at, :utc_datetime
      add :rejected_at, :utc_datetime
      add :rejection_reason, :text
      add :archived_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_team_member_id,
          references(:team_members,
            column: :id,
            name: "operations_memory_blocks_created_by_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :approved_by_team_member_id,
          references(:team_members,
            column: :id,
            name: "operations_memory_blocks_approved_by_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :source_agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "operations_memory_blocks_source_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:operations_memory_blocks, [:source_type, :source_id])

    create index(:operations_memory_blocks, [:memory_type, :status])

    create index(:operations_memory_blocks, [:status, :scope, :scope_key])

    create unique_index(:operations_memory_blocks, [:key, :scope, :scope_key],
             name: "operations_memory_blocks_unique_key_per_scope_index"
           )
  end

  def down do
    drop constraint(
           :operations_memory_blocks,
           "operations_memory_blocks_created_by_team_member_id_fkey"
         )

    drop constraint(
           :operations_memory_blocks,
           "operations_memory_blocks_approved_by_team_member_id_fkey"
         )

    drop constraint(
           :operations_memory_blocks,
           "operations_memory_blocks_source_agent_run_id_fkey"
         )

    drop_if_exists unique_index(:operations_memory_blocks, [:key, :scope, :scope_key],
                     name: "operations_memory_blocks_unique_key_per_scope_index"
                   )

    drop_if_exists index(:operations_memory_blocks, [:status, :scope, :scope_key])

    drop_if_exists index(:operations_memory_blocks, [:memory_type, :status])

    drop_if_exists index(:operations_memory_blocks, [:source_type, :source_id])

    drop table(:operations_memory_blocks)
  end
end
