defmodule GnomeGarden.Repo.Migrations.HardenCommercialDiscoveryRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:commercial_discovery_runs, [:discovery_program_id],
             name: "discovery_runs_active_program_index",
             unique: true,
             where: "status IN ('queued', 'running')"
           )
  end

  def down do
    drop_if_exists index(:commercial_discovery_runs, [:discovery_program_id],
                     name: "discovery_runs_active_program_index"
                   )
  end
end
