defmodule GnomeGarden.Repo.Migrations.RenameAcquisitionSourceProcurementSourceRef do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:acquisition_sources), :legacy_procurement_source_id, to: :procurement_source_id

    execute("""
    ALTER TABLE acquisition_sources
    RENAME CONSTRAINT acquisition_sources_legacy_procurement_source_id_fkey
    TO acquisition_sources_procurement_source_id_fkey
    """)
  end

  def down do
    rename table(:acquisition_sources), :procurement_source_id, to: :legacy_procurement_source_id

    execute("""
    ALTER TABLE acquisition_sources
    RENAME CONSTRAINT acquisition_sources_procurement_source_id_fkey
    TO acquisition_sources_legacy_procurement_source_id_fkey
    """)
  end
end
