defmodule GnomeGarden.Repo.Migrations.AddMercuryAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mercury_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :mercury_id, :text, null: false
      add :name, :text, null: false
      add :nickname, :text
      add :legal_business_name, :text
      add :status, :text, null: false
      add :kind, :text, null: false
      add :current_balance, :decimal
      add :available_balance, :decimal
      add :routing_number, :text
      add :account_number, :text
      add :dashboard_id, :text
      add :company_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:mercury_accounts, [:mercury_id],
             name: "mercury_accounts_unique_mercury_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:mercury_accounts, [:mercury_id],
                     name: "mercury_accounts_unique_mercury_id_index"
                   )

    drop table(:mercury_accounts)
  end
end
