defmodule GnomeGarden.Repo.Migrations.AddBankAccountLedgerAccount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:banking_accounts) do
      add :ledger_account_id,
          references(:ledger_accounts,
            column: :id,
            name: "banking_accounts_ledger_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:banking_accounts, "banking_accounts_ledger_account_id_fkey")

    alter table(:banking_accounts) do
      remove :ledger_account_id
    end
  end
end
