defmodule GnomeGarden.Repo.Migrations.EnrichBankingDetailFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:banking_accounts) do
      remove :account_number_last4
      add :wire_routing_number, :text
      add :account_number_last, :text
      add :currency_code, :text, null: false, default: "USD"
      add :balance_as_of, :utc_datetime
    end

    alter table(:banking_transactions) do
      add :match_status, :text, null: false, default: "unmatched"
      add :kind, :text
      add :memo, :text
      add :counterparty_id, :text
      add :counterparty_account_last, :text
      add :dashboard_link, :text
      add :posted_at, :utc_datetime
    end
  end

  def down do
    alter table(:banking_transactions) do
      remove :posted_at
      remove :dashboard_link
      remove :counterparty_account_last
      remove :counterparty_id
      remove :memo
      remove :kind
      remove :match_status
    end

    alter table(:banking_accounts) do
      remove :balance_as_of
      remove :currency_code
      remove :account_number_last
      remove :wire_routing_number
      add :account_number_last4, :text
    end
  end
end
