defmodule GnomeGarden.Repo.Migrations.AddExecutionAssignments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:execution_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :assignment_type, :text, null: false, default: "project_work"
      add :location_mode, :text, null: false, default: "hybrid"
      add :status, :text, null: false, default: "planned"
      add :scheduled_start_at, :utc_datetime, null: false
      add :scheduled_end_at, :utc_datetime
      add :actual_start_at, :utc_datetime
      add :actual_end_at, :utc_datetime
      add :planned_minutes, :bigint
      add :billable, :boolean, null: false, default: true
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "execution_assignments_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :project_id,
          references(:execution_projects,
            column: :id,
            name: "execution_assignments_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :work_item_id,
          references(:execution_work_items,
            column: :id,
            name: "execution_assignments_work_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :work_order_id,
          references(:execution_work_orders,
            column: :id,
            name: "execution_assignments_work_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :assigned_user_id,
          references(:users,
            column: :id,
            name: "execution_assignments_assigned_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          ),
          null: false

      add :assigned_by_user_id,
          references(:users,
            column: :id,
            name: "execution_assignments_assigned_by_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:execution_assignments, "execution_assignments_organization_id_fkey")

    drop constraint(:execution_assignments, "execution_assignments_project_id_fkey")

    drop constraint(:execution_assignments, "execution_assignments_work_item_id_fkey")

    drop constraint(:execution_assignments, "execution_assignments_work_order_id_fkey")

    drop constraint(:execution_assignments, "execution_assignments_assigned_user_id_fkey")

    drop constraint(:execution_assignments, "execution_assignments_assigned_by_user_id_fkey")

    drop table(:execution_assignments)
  end
end
