defmodule GnomeGarden.Repo.Migrations.RestrictProposalPursuitReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:commercial_proposals, "commercial_proposals_pursuit_id_fkey")

    alter table(:commercial_proposals) do
      modify :pursuit_id,
             references(:commercial_pursuits,
               column: :id,
               name: "commercial_proposals_pursuit_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end
  end

  def down do
    drop constraint(:commercial_proposals, "commercial_proposals_pursuit_id_fkey")

    alter table(:commercial_proposals) do
      modify :pursuit_id,
             references(:commercial_pursuits,
               column: :id,
               name: "commercial_proposals_pursuit_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end
  end
end
