defmodule GnomeGarden.Repo.Migrations.SwitchUsersToPasswordAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @cutover_password_hash "$2b$12$JEvgH663gqti.eTfUsncvuM0yg1KIAI7TuKFI53u3vc3WpX18uesa"

  def up do
    alter table(:users) do
      add :hashed_password, :text
    end

    execute """
    UPDATE users
    SET hashed_password = '#{@cutover_password_hash}'
    WHERE hashed_password IS NULL
    """

    alter table(:users) do
      modify :hashed_password, :text, null: false
    end
  end

  def down do
    alter table(:users) do
      remove :hashed_password
    end
  end
end
