defmodule GnomeGarden.Repo.Migrations.AddBillingReliability do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:commercial_agreements) do
      add :payment_terms_days, :bigint, null: false, default: 30
    end

    alter table(:organizations) do
      add :billing_contact_id,
          references(:people,
            column: :id,
            name: "organizations_billing_contact_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:payment_schedule_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false
      add :label, :text, null: false
      add :percentage, :decimal, null: false
      add :due_days, :bigint, null: false, default: 30

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "payment_schedule_items_agreement_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:payment_schedule_items, "payment_schedule_items_agreement_id_fkey")

    drop table(:payment_schedule_items)

    drop constraint(:organizations, "organizations_billing_contact_id_fkey")

    alter table(:organizations) do
      remove :billing_contact_id
    end

    alter table(:commercial_agreements) do
      remove :payment_terms_days
    end
  end
end
