defmodule GnomeGarden.Repo.Migrations.AddClientUserOrgFk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:client_users) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "client_users_organization_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:client_users, [:organization_id])
  end

  def down do
    drop_if_exists index(:client_users, [:organization_id])

    drop constraint(:client_users, "client_users_organization_id_fkey")

    alter table(:client_users) do
      modify :organization_id, :uuid
    end
  end
end
