defmodule GnomeHub.Repo.Migrations.CreateLeadSourcesBidsProspects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:prospects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :website, :text
      add :location, :text
      add :region, :text
      add :industry, :text
      add :size, :text
      add :status, :text, default: "researched"
      add :signals, {:array, :text}, default: []
      add :signal_strength, :text, default: "medium"
      add :tech_indicators, {:array, :text}, default: []
      add :contacts, {:array, :map}, default: []
      add :discovered_via, :text
      add :discovered_at, :utc_datetime
      add :discovery_url, :text
      add :notes, :text
      add :next_action, :text
      add :next_action_date, :date
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:prospects, [:name, :location],
             name: "prospects_unique_name_location_index"
           )

    create table(:lead_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :url, :text, null: false
      add :source_type, :text, null: false
      add :portal_id, :text
      add :region, :text, default: "socal"
      add :priority, :text, default: "medium"
      add :api_available, :boolean, default: false
      add :requires_login, :boolean, default: false
      add :scrape_selector, :text
      add :last_scanned_at, :utc_datetime
      add :scan_frequency_hours, :bigint, default: 24
      add :enabled, :boolean, default: true
      add :metadata, :map, default: %{}
      add :discovered_by, :text
      add :discovery_notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:lead_sources, [:url], name: "lead_sources_unique_url_index")

    create table(:bids, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :external_id, :text
      add :url, :text, null: false
      add :source_url, :text
      add :agency, :text
      add :location, :text
      add :region, :text
      add :status, :text, default: "new"
      add :posted_at, :utc_datetime
      add :due_at, :utc_datetime
      add :discovered_at, :utc_datetime
      add :estimated_value, :decimal
      add :value_range, :text
      add :score_service_match, :bigint, default: 0
      add :score_geography, :bigint, default: 0
      add :score_value, :bigint, default: 0
      add :score_tech_fit, :bigint, default: 0
      add :score_industry, :bigint, default: 0
      add :score_opportunity_type, :bigint, default: 0
      add :score_total, :bigint, default: 0
      add :score_tier, :text
      add :keywords_matched, {:array, :text}, default: []
      add :keywords_rejected, {:array, :text}, default: []
      add :notes, :text
      add :assigned_to, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :lead_source_id,
          references(:lead_sources,
            column: :id,
            name: "bids_lead_source_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:bids, [:url], name: "bids_unique_url_index")
  end

  def down do
    drop_if_exists unique_index(:bids, [:url], name: "bids_unique_url_index")

    drop constraint(:bids, "bids_lead_source_id_fkey")

    drop table(:bids)

    drop_if_exists unique_index(:lead_sources, [:url], name: "lead_sources_unique_url_index")

    drop table(:lead_sources)

    drop_if_exists unique_index(:prospects, [:name, :location],
                     name: "prospects_unique_name_location_index"
                   )

    drop table(:prospects)
  end
end
