defmodule GnomeGarden.Repo.Migrations.AddDiscoveryRunProgramSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:commercial_discovery_runs) do
      add :program_source_id,
          references(:acquisition_program_sources,
            column: :id,
            name: "commercial_discovery_runs_program_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end
  end

  def down do
    drop constraint(
           :commercial_discovery_runs,
           "commercial_discovery_runs_program_source_id_fkey"
         )

    alter table(:commercial_discovery_runs) do
      remove :program_source_id
    end
  end
end
