defmodule GnomeGarden.Repo.Migrations.ProcurementSourceConfigStatusStateMachine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lead_sources) do
      remove :state
      modify :config_status, :text, null: false
    end
  end

  def down do
    alter table(:lead_sources) do
      modify :config_status, :text, null: true
      add :state, :text, null: false, default: "found"
    end
  end
end
