defmodule GnomeGarden.Repo.Migrations.AddAcquisitionIntakeSpine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_programs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :external_ref, :text, null: false
      add :description, :text
      add :program_family, :text, null: false
      add :program_type, :text, null: false
      add :status, :text, null: false, default: "active"
      add :scope, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}
      add :last_run_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :legacy_discovery_program_id,
          references(:commercial_discovery_programs,
            column: :id,
            name: "acquisition_programs_legacy_discovery_program_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "acquisition_programs_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:acquisition_programs, [:program_family, :status])

    create unique_index(:acquisition_programs, [:external_ref],
             name: "acquisition_programs_unique_external_ref_index"
           )

    create table(:acquisition_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :external_ref, :text, null: false
      add :url, :text, null: false
      add :source_family, :text, null: false
      add :source_kind, :text, null: false
      add :status, :text, null: false, default: "active"
      add :enabled, :boolean, null: false, default: true
      add :scan_strategy, :text, null: false, default: "deterministic"
      add :description, :text
      add :metadata, :map, null: false, default: %{}
      add :last_run_at, :utc_datetime
      add :last_success_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :legacy_procurement_source_id,
          references(:lead_sources,
            column: :id,
            name: "acquisition_sources_legacy_procurement_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "acquisition_sources_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:acquisition_sources, [:enabled, :status])

    create index(:acquisition_sources, [:source_family, :status])

    create unique_index(:acquisition_sources, [:external_ref],
             name: "acquisition_sources_unique_external_ref_index"
           )

    create unique_index(:acquisition_sources, [:url],
             name: "acquisition_sources_unique_url_index"
           )

    create table(:acquisition_findings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :summary, :text
      add :external_ref, :text, null: false
      add :source_url, :text
      add :finding_family, :text, null: false
      add :finding_type, :text, null: false
      add :status, :text, null: false, default: "new"
      add :fit_score, :bigint
      add :intent_score, :bigint
      add :confidence, :text
      add :recommendation, :text
      add :watchouts, {:array, :text}, null: false, default: []
      add :observed_at, :utc_datetime
      add :reviewed_at, :utc_datetime
      add :promoted_at, :utc_datetime
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_id,
          references(:acquisition_sources,
            column: :id,
            name: "acquisition_findings_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :program_id,
          references(:acquisition_programs,
            column: :id,
            name: "acquisition_findings_program_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "acquisition_findings_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "acquisition_findings_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :person_id,
          references(:people,
            column: :id,
            name: "acquisition_findings_person_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :signal_id,
          references(:commercial_signals,
            column: :id,
            name: "acquisition_findings_signal_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :source_bid_id,
          references(:bids,
            column: :id,
            name: "acquisition_findings_source_bid_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :source_target_account_id,
          references(:commercial_target_accounts,
            column: :id,
            name: "acquisition_findings_source_target_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:acquisition_findings, [:signal_id])

    create index(:acquisition_findings, [:status, :observed_at])

    create index(:acquisition_findings, [:finding_family, :status])

    create unique_index(:acquisition_findings, [:external_ref],
             name: "acquisition_findings_unique_external_ref_index"
           )
  end

  def down do
    drop_if_exists unique_index(:acquisition_findings, [:external_ref],
                     name: "acquisition_findings_unique_external_ref_index"
                   )

    drop constraint(:acquisition_findings, "acquisition_findings_source_id_fkey")

    drop constraint(:acquisition_findings, "acquisition_findings_program_id_fkey")

    drop constraint(:acquisition_findings, "acquisition_findings_agent_run_id_fkey")

    drop constraint(:acquisition_findings, "acquisition_findings_organization_id_fkey")

    drop constraint(:acquisition_findings, "acquisition_findings_person_id_fkey")

    drop constraint(:acquisition_findings, "acquisition_findings_signal_id_fkey")

    drop constraint(:acquisition_findings, "acquisition_findings_source_bid_id_fkey")

    drop constraint(:acquisition_findings, "acquisition_findings_source_target_account_id_fkey")

    drop_if_exists index(:acquisition_findings, [:finding_family, :status])

    drop_if_exists index(:acquisition_findings, [:status, :observed_at])

    drop_if_exists index(:acquisition_findings, [:signal_id])

    drop table(:acquisition_findings)

    drop_if_exists unique_index(:acquisition_sources, [:url],
                     name: "acquisition_sources_unique_url_index"
                   )

    drop_if_exists unique_index(:acquisition_sources, [:external_ref],
                     name: "acquisition_sources_unique_external_ref_index"
                   )

    drop constraint(:acquisition_sources, "acquisition_sources_legacy_procurement_source_id_fkey")

    drop constraint(:acquisition_sources, "acquisition_sources_organization_id_fkey")

    drop_if_exists index(:acquisition_sources, [:source_family, :status])

    drop_if_exists index(:acquisition_sources, [:enabled, :status])

    drop table(:acquisition_sources)

    drop_if_exists unique_index(:acquisition_programs, [:external_ref],
                     name: "acquisition_programs_unique_external_ref_index"
                   )

    drop constraint(
           :acquisition_programs,
           "acquisition_programs_legacy_discovery_program_id_fkey"
         )

    drop constraint(:acquisition_programs, "acquisition_programs_owner_user_id_fkey")

    drop_if_exists index(:acquisition_programs, [:program_family, :status])

    drop table(:acquisition_programs)
  end
end
