defmodule GnomeGarden.Repo.Migrations.RenameAcquisitionProgramDiscoveryProgramRef do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:acquisition_programs), :legacy_discovery_program_id, to: :discovery_program_id

    execute("""
    ALTER TABLE acquisition_programs
    RENAME CONSTRAINT acquisition_programs_legacy_discovery_program_id_fkey
    TO acquisition_programs_discovery_program_id_fkey
    """)
  end

  def down do
    rename table(:acquisition_programs), :discovery_program_id, to: :legacy_discovery_program_id

    execute("""
    ALTER TABLE acquisition_programs
    RENAME CONSTRAINT acquisition_programs_discovery_program_id_fkey
    TO acquisition_programs_legacy_discovery_program_id_fkey
    """)
  end
end
