defmodule GnomeGarden.Repo.Migrations.AddPersistedLeadAdmissionPolicy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_lead_admission_policies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false, default: "commercial-default"
      add :candidate_limit, :bigint, null: false, default: 5
      add :finding_run_limit, :bigint, null: false, default: 3
      add :finding_daily_limit, :bigint, null: false, default: 20
      add :min_search_score, :decimal, null: false, default: "0.10"
      add :min_evidence_characters, :bigint, null: false, default: 300

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:acquisition_lead_admission_policies, [:key],
             name: "acquisition_lead_admission_policies_unique_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:acquisition_lead_admission_policies, [:key],
                     name: "acquisition_lead_admission_policies_unique_key_index"
                   )

    drop table(:acquisition_lead_admission_policies)
  end
end
