defmodule GnomeGarden.Repo.Migrations.AddExecutionSpine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:execution_work_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text
      add :title, :text, null: false
      add :description, :text
      add :kind, :text, null: false, default: "task"
      add :discipline, :text, null: false, default: "other"
      add :status, :text, null: false, default: "backlog"
      add :priority, :text, null: false, default: "normal"
      add :estimate_minutes, :bigint
      add :due_on, :date
      add :completed_at, :utc_datetime
      add :sort_order, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id, :uuid, null: false
      add :parent_work_item_id, :uuid
      add :owner_user_id, :uuid
    end

    create table(:execution_projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:execution_work_items) do
      modify :project_id,
             references(:execution_projects,
               column: :id,
               name: "execution_work_items_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :parent_work_item_id,
             references(:execution_work_items,
               column: :id,
               name: "execution_work_items_parent_work_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :owner_user_id,
             references(:users,
               column: :id,
               name: "execution_work_items_owner_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:execution_projects) do
      add :code, :text
      add :name, :text, null: false
      add :description, :text
      add :project_type, :text, null: false, default: "implementation"
      add :delivery_mode, :text, null: false, default: "hybrid"
      add :status, :text, null: false, default: "planned"
      add :priority, :text, null: false, default: "normal"
      add :start_on, :date
      add :target_end_on, :date
      add :actual_end_on, :date
      add :budget_hours, :decimal
      add :budget_amount, :decimal
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "execution_projects_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :site_id,
          references(:sites,
            column: :id,
            name: "execution_projects_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :managed_system_id,
          references(:managed_systems,
            column: :id,
            name: "execution_projects_managed_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "execution_projects_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :manager_user_id,
          references(:users,
            column: :id,
            name: "execution_projects_manager_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:execution_work_orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reference_number, :text
      add :title, :text, null: false
      add :description, :text
      add :work_type, :text, null: false, default: "service_call"
      add :status, :text, null: false, default: "new"
      add :priority, :text, null: false, default: "normal"
      add :billable, :boolean, null: false, default: true
      add :estimated_minutes, :bigint
      add :due_on, :date
      add :scheduled_start_at, :utc_datetime
      add :scheduled_end_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :resolution_notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "execution_work_orders_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :site_id,
          references(:sites,
            column: :id,
            name: "execution_work_orders_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :managed_system_id,
          references(:managed_systems,
            column: :id,
            name: "execution_work_orders_managed_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "execution_work_orders_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :project_id,
          references(:execution_projects,
            column: :id,
            name: "execution_work_orders_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :requested_by_user_id,
          references(:users,
            column: :id,
            name: "execution_work_orders_requested_by_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :assigned_user_id,
          references(:users,
            column: :id,
            name: "execution_work_orders_assigned_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:execution_work_orders, "execution_work_orders_organization_id_fkey")

    drop constraint(:execution_work_orders, "execution_work_orders_site_id_fkey")

    drop constraint(:execution_work_orders, "execution_work_orders_managed_system_id_fkey")

    drop constraint(:execution_work_orders, "execution_work_orders_agreement_id_fkey")

    drop constraint(:execution_work_orders, "execution_work_orders_project_id_fkey")

    drop constraint(:execution_work_orders, "execution_work_orders_requested_by_user_id_fkey")

    drop constraint(:execution_work_orders, "execution_work_orders_assigned_user_id_fkey")

    drop table(:execution_work_orders)

    drop constraint(:execution_projects, "execution_projects_organization_id_fkey")

    drop constraint(:execution_projects, "execution_projects_site_id_fkey")

    drop constraint(:execution_projects, "execution_projects_managed_system_id_fkey")

    drop constraint(:execution_projects, "execution_projects_agreement_id_fkey")

    drop constraint(:execution_projects, "execution_projects_manager_user_id_fkey")

    alter table(:execution_projects) do
      remove :manager_user_id
      remove :agreement_id
      remove :managed_system_id
      remove :site_id
      remove :organization_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :budget_amount
      remove :budget_hours
      remove :actual_end_on
      remove :target_end_on
      remove :start_on
      remove :priority
      remove :status
      remove :delivery_mode
      remove :project_type
      remove :description
      remove :name
      remove :code
    end

    drop constraint(:execution_work_items, "execution_work_items_project_id_fkey")

    drop constraint(:execution_work_items, "execution_work_items_parent_work_item_id_fkey")

    drop constraint(:execution_work_items, "execution_work_items_owner_user_id_fkey")

    alter table(:execution_work_items) do
      modify :owner_user_id, :uuid
      modify :parent_work_item_id, :uuid
      modify :project_id, :uuid
    end

    drop table(:execution_projects)

    drop table(:execution_work_items)
  end
end
