defmodule GnomeGarden.Repo.Migrations.UpdateConfigStatusStates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lead_sources) do
      modify :state, :text, default: "found"
      modify :config_status, :text, default: "found"
    end
  end

  def down do
    alter table(:lead_sources) do
      modify :config_status, :text, default: "pending"
      modify :state, :text, default: "pending"
    end
  end
end
