defmodule GnomeGarden.Repo.Migrations.RetireMercuryDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:mercury_alias_events)

    drop table(:mercury_bank_rules)

    drop table(:mercury_client_bank_aliases)

    drop table(:mercury_payment_matches)

    drop table(:mercury_transaction_events)

    drop table(:mercury_transactions)

    drop table(:mercury_accounts)
  end

  def down do
    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually
  end
end
