defmodule GnomeGarden.Repo.Migrations.AddBillingRunsAndInvoiceEmailState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:finance_billing_run_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :outcome, :text, null: false
      add :email_outcome, :text, null: false, default: "not_attempted"
      add :detail, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :billing_run_id, :uuid, null: false
      add :agreement_id, :uuid
      add :invoice_id, :uuid
    end

    alter table(:finance_invoices) do
      add :email_status, :text, null: false, default: "pending"
      add :last_email_attempted_at, :utc_datetime
      add :email_sent_at, :utc_datetime
      add :email_failed_at, :utc_datetime
      add :email_failure_reason, :text
    end

    create table(:finance_billing_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:finance_billing_run_items) do
      modify :billing_run_id,
             references(:finance_billing_runs,
               column: :id,
               name: "finance_billing_run_items_billing_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :agreement_id,
             references(:commercial_agreements,
               column: :id,
               name: "finance_billing_run_items_agreement_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :invoice_id,
             references(:finance_invoices,
               column: :id,
               name: "finance_billing_run_items_invoice_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:finance_billing_runs) do
      add :source, :text, null: false, default: "scheduled"
      add :status, :text, null: false, default: "running"
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
      add :scanned_count, :bigint, default: 0
      add :drafted_count, :bigint, default: 0
      add :issued_count, :bigint, default: 0
      add :emailed_count, :bigint, default: 0
      add :failed_count, :bigint, default: 0
      add :skipped_count, :bigint, default: 0
      add :error_summary, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:finance_billing_runs) do
      remove :updated_at
      remove :inserted_at
      remove :error_summary
      remove :skipped_count
      remove :failed_count
      remove :emailed_count
      remove :issued_count
      remove :drafted_count
      remove :scanned_count
      remove :finished_at
      remove :started_at
      remove :status
      remove :source
    end

    drop constraint(:finance_billing_run_items, "finance_billing_run_items_billing_run_id_fkey")

    drop constraint(:finance_billing_run_items, "finance_billing_run_items_agreement_id_fkey")

    drop constraint(:finance_billing_run_items, "finance_billing_run_items_invoice_id_fkey")

    alter table(:finance_billing_run_items) do
      modify :invoice_id, :uuid
      modify :agreement_id, :uuid
      modify :billing_run_id, :uuid
    end

    drop table(:finance_billing_runs)

    alter table(:finance_invoices) do
      remove :email_failure_reason
      remove :email_failed_at
      remove :email_sent_at
      remove :last_email_attempted_at
      remove :email_status
    end

    drop table(:finance_billing_run_items)
  end
end
