defmodule GnomeGarden.Repo.Migrations.RenameLeadSourcesToProcurementSources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @constraint_renames [
    {"lead_sources_config_status_not_null", "procurement_sources_config_status_not_null"},
    {"lead_sources_id_not_null", "procurement_sources_id_not_null"},
    {"lead_sources_inserted_at_not_null", "procurement_sources_inserted_at_not_null"},
    {"lead_sources_name_not_null", "procurement_sources_name_not_null"},
    {"lead_sources_organization_id_fkey", "procurement_sources_organization_id_fkey"},
    {"lead_sources_pkey", "procurement_sources_pkey"},
    {"lead_sources_source_type_not_null", "procurement_sources_source_type_not_null"},
    {"lead_sources_status_not_null", "procurement_sources_status_not_null"},
    {"lead_sources_updated_at_not_null", "procurement_sources_updated_at_not_null"},
    {"lead_sources_url_not_null", "procurement_sources_url_not_null"}
  ]

  def up do
    rename table(:lead_sources), to: table(:procurement_sources)

    execute(
      "ALTER INDEX IF EXISTS lead_sources_unique_url_index RENAME TO procurement_sources_unique_url_index",
      "ALTER INDEX IF EXISTS procurement_sources_unique_url_index RENAME TO lead_sources_unique_url_index"
    )

    Enum.each(@constraint_renames, fn {from, to} ->
      rename_procurement_source_constraint(from, to)
    end)
  end

  def down do
    Enum.each(@constraint_renames, fn {from, to} ->
      rename_procurement_source_constraint(to, from)
    end)

    execute(
      "ALTER INDEX IF EXISTS procurement_sources_unique_url_index RENAME TO lead_sources_unique_url_index",
      "ALTER INDEX IF EXISTS lead_sources_unique_url_index RENAME TO procurement_sources_unique_url_index"
    )

    rename table(:procurement_sources), to: table(:lead_sources)
  end

  defp rename_procurement_source_constraint(from, to) do
    execute(
      "ALTER TABLE procurement_sources RENAME CONSTRAINT #{from} TO #{to}",
      "ALTER TABLE procurement_sources RENAME CONSTRAINT #{to} TO #{from}"
    )
  end
end
