defmodule GnomeGarden.Repo.Migrations.AddProposalNumberAutoGenerate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:commercial_proposals) do
      modify :proposal_number, :text, null: true
    end
  end

  def down do
    alter table(:commercial_proposals) do
      modify :proposal_number, :text, null: false
    end
  end
end
