defmodule GnomeGarden.Repo.Migrations.CreateAgentsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :template, :text, null: false
      add :description, :text
      add :model, :text, default: "fast"
      add :max_iterations, :bigint, default: 25
      add :tools, {:array, :text}, default: []
      add :system_prompt, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:agents, [:name], name: "agents_unique_name_index")

    create table(:agent_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :state, :text, null: false, default: "pending"
      add :task, :text, null: false
      add :result, :text
      add :error, :text
      add :token_count, :bigint, default: 0
      add :tool_count, :bigint, default: 0
      add :metadata, :map, default: %{}
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agent_id,
          references(:agents,
            column: :id,
            name: "agent_runs_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :parent_run_id,
          references(:agent_runs,
            column: :id,
            name: "agent_runs_parent_run_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:agent_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :content, :text
      add :tool_name, :text
      add :tool_input, :map
      add :tool_result, :map
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "agent_messages_agent_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:agent_memories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :content, :text, null: false
      add :type, :text, default: "fact"
      add :namespace, :text, default: "global"
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:agent_memories, [:key, :namespace],
             name: "agent_memories_unique_key_namespace_index"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_memories, [:key, :namespace],
                     name: "agent_memories_unique_key_namespace_index"
                   )

    drop table(:agent_memories)

    drop constraint(:agent_messages, "agent_messages_agent_run_id_fkey")

    drop table(:agent_messages)

    drop constraint(:agent_runs, "agent_runs_agent_id_fkey")

    drop constraint(:agent_runs, "agent_runs_parent_run_id_fkey")

    drop table(:agent_runs)

    drop_if_exists unique_index(:agents, [:name], name: "agents_unique_name_index")

    drop table(:agents)
  end
end
