defmodule GnomeGarden.Repo.Migrations.Playbooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :playbook_step_snapshot, :map
      add :playbook_run_id, :uuid
      add :playbook_step_id, :uuid
    end

    create table(:playbook_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:tasks) do
      modify :playbook_run_id,
             references(:playbook_runs,
               column: :id,
               name: "tasks_playbook_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:playbook_runs) do
      add :playbook_name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :playbook_id, :uuid, null: false
      add :applied_by_team_member_id, :uuid
      add :pursuit_id, :uuid
      add :project_id, :uuid
      add :bid_id, :uuid
      add :procurement_source_id, :uuid
      add :organization_id, :uuid
      add :signal_id, :uuid
    end

    create table(:playbook_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:tasks) do
      modify :playbook_step_id,
             references(:playbook_steps,
               column: :id,
               name: "tasks_playbook_step_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:playbook_steps) do
      add :position, :bigint, null: false
      add :title, :text, null: false
      add :description, :text
      add :task_type, :text, null: false, default: "other"
      add :priority, :text, null: false, default: "normal"
      add :due_offset_days, :bigint
      add :assignee_strategy, :text, null: false, default: "unassigned"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :playbook_id, :uuid, null: false
      add :assignee_team_member_id, :uuid
    end

    create table(:playbooks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:playbook_runs) do
      modify :playbook_id,
             references(:playbooks,
               column: :id,
               name: "playbook_runs_playbook_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :applied_by_team_member_id,
             references(:team_members,
               column: :id,
               name: "playbook_runs_applied_by_team_member_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :pursuit_id,
             references(:commercial_pursuits,
               column: :id,
               name: "playbook_runs_pursuit_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :project_id,
             references(:execution_projects,
               column: :id,
               name: "playbook_runs_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :bid_id,
             references(:bids,
               column: :id,
               name: "playbook_runs_bid_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :procurement_source_id,
             references(:procurement_sources,
               column: :id,
               name: "playbook_runs_procurement_source_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "playbook_runs_organization_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :signal_id,
             references(:commercial_signals,
               column: :id,
               name: "playbook_runs_signal_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:playbook_steps) do
      modify :playbook_id,
             references(:playbooks,
               column: :id,
               name: "playbook_steps_playbook_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :assignee_team_member_id,
             references(:team_members,
               column: :id,
               name: "playbook_steps_assignee_team_member_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:playbooks) do
      add :name, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:playbooks, [:name], name: "playbooks_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:playbooks, [:name], name: "playbooks_unique_name_index")

    alter table(:playbooks) do
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :description
      remove :name
    end

    drop constraint(:playbook_steps, "playbook_steps_playbook_id_fkey")

    drop constraint(:playbook_steps, "playbook_steps_assignee_team_member_id_fkey")

    alter table(:playbook_steps) do
      modify :assignee_team_member_id, :uuid
      modify :playbook_id, :uuid
    end

    drop constraint(:playbook_runs, "playbook_runs_playbook_id_fkey")

    drop constraint(:playbook_runs, "playbook_runs_applied_by_team_member_id_fkey")

    drop constraint(:playbook_runs, "playbook_runs_pursuit_id_fkey")

    drop constraint(:playbook_runs, "playbook_runs_project_id_fkey")

    drop constraint(:playbook_runs, "playbook_runs_bid_id_fkey")

    drop constraint(:playbook_runs, "playbook_runs_procurement_source_id_fkey")

    drop constraint(:playbook_runs, "playbook_runs_organization_id_fkey")

    drop constraint(:playbook_runs, "playbook_runs_signal_id_fkey")

    alter table(:playbook_runs) do
      modify :signal_id, :uuid
      modify :organization_id, :uuid
      modify :procurement_source_id, :uuid
      modify :bid_id, :uuid
      modify :project_id, :uuid
      modify :pursuit_id, :uuid
      modify :applied_by_team_member_id, :uuid
      modify :playbook_id, :uuid
    end

    drop table(:playbooks)

    alter table(:playbook_steps) do
      remove :assignee_team_member_id
      remove :playbook_id
      remove :updated_at
      remove :inserted_at
      remove :assignee_strategy
      remove :due_offset_days
      remove :priority
      remove :task_type
      remove :description
      remove :title
      remove :position
    end

    drop constraint(:tasks, "tasks_playbook_step_id_fkey")

    alter table(:tasks) do
      modify :playbook_step_id, :uuid
    end

    drop table(:playbook_steps)

    alter table(:playbook_runs) do
      remove :signal_id
      remove :organization_id
      remove :procurement_source_id
      remove :bid_id
      remove :project_id
      remove :pursuit_id
      remove :applied_by_team_member_id
      remove :playbook_id
      remove :updated_at
      remove :inserted_at
      remove :playbook_name
    end

    drop constraint(:tasks, "tasks_playbook_run_id_fkey")

    alter table(:tasks) do
      modify :playbook_run_id, :uuid
    end

    drop table(:playbook_runs)

    alter table(:tasks) do
      remove :playbook_step_id
      remove :playbook_run_id
      remove :playbook_step_snapshot
    end
  end
end
