defmodule GnomeGarden.Repo.Migrations.RemoveCompanyFromContact do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:employments) do
      add :is_primary, :boolean, default: false
    end

    alter table(:contacts) do
      remove :company_id
      remove :is_primary
      remove :role
      remove :department
      remove :title
    end
  end

  def down do
    alter table(:contacts) do
      add :title, :text
      add :department, :text
      add :role, :text
      add :is_primary, :boolean, default: false

      add :company_id,
          references(:companies,
            column: :id,
            name: "contacts_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    alter table(:employments) do
      remove :is_primary
    end
  end
end
