defmodule GnomeGarden.Repo.Migrations.AddAgentDeploymentsConsole do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:agent_runs, "agent_runs_parent_run_id_fkey")

    drop constraint(:agent_runs, "agent_runs_agent_id_fkey")

    alter table(:agent_runs) do
      add :run_kind, :text, null: false, default: "manual"
      add :result_summary, :map, default: %{}
      add :failure_details, :map, default: %{}
      add :runtime_instance_id, :text
      add :request_id, :text
      add :deployment_id, :uuid, null: false
      add :requested_by_user_id, :uuid
    end

    create table(:agent_deployments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:agent_runs) do
      modify :deployment_id,
             references(:agent_deployments,
               column: :id,
               name: "agent_runs_deployment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :requested_by_user_id,
             references(:users,
               column: :id,
               name: "agent_runs_requested_by_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :agent_id,
             references(:agents,
               column: :id,
               name: "agent_runs_agent_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :parent_run_id,
             references(:agent_runs,
               column: :id,
               name: "agent_runs_parent_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:agent_deployments) do
      add :name, :text, null: false
      add :description, :text
      add :visibility, :text, null: false, default: "private"
      add :enabled, :boolean, null: false, default: true
      add :schedule, :text
      add :config, :map, null: false, default: %{}
      add :source_scope, :map, null: false, default: %{}
      add :memory_namespace, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agent_id,
          references(:agents,
            column: :id,
            name: "agent_deployments_agent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "agent_deployments_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:agent_deployments, [:name], name: "agent_deployments_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:agent_deployments, [:name],
                     name: "agent_deployments_unique_name_index"
                   )

    drop constraint(:agent_deployments, "agent_deployments_agent_id_fkey")

    drop constraint(:agent_deployments, "agent_deployments_owner_user_id_fkey")

    alter table(:agent_deployments) do
      remove :owner_user_id
      remove :agent_id
      remove :updated_at
      remove :inserted_at
      remove :memory_namespace
      remove :source_scope
      remove :config
      remove :schedule
      remove :enabled
      remove :visibility
      remove :description
      remove :name
    end

    drop constraint(:agent_runs, "agent_runs_deployment_id_fkey")

    drop constraint(:agent_runs, "agent_runs_requested_by_user_id_fkey")

    drop constraint(:agent_runs, "agent_runs_agent_id_fkey")

    drop constraint(:agent_runs, "agent_runs_parent_run_id_fkey")

    alter table(:agent_runs) do
      modify :parent_run_id,
             references(:agent_runs,
               column: :id,
               name: "agent_runs_parent_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :agent_id,
             references(:agents,
               column: :id,
               name: "agent_runs_agent_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :requested_by_user_id, :uuid
      modify :deployment_id, :uuid
    end

    drop table(:agent_deployments)

    alter table(:agent_runs) do
      remove :requested_by_user_id
      remove :deployment_id
      remove :request_id
      remove :runtime_instance_id
      remove :failure_details
      remove :result_summary
      remove :run_kind
    end
  end
end
