defmodule GnomeGarden.Repo.Migrations.AddAddressAndCompanyRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:company_relationships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :relationship_type, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :from_company_id,
          references(:companies,
            column: :id,
            name: "company_relationships_from_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :to_company_id,
          references(:companies,
            column: :id,
            name: "company_relationships_to_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(
             :company_relationships,
             [:from_company_id, :to_company_id, :relationship_type],
             name: "company_relationships_unique_relationship_index"
           )

    create table(:addresses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :address_type, :text, null: false, default: "billing"
      add :street1, :text, null: false
      add :street2, :text
      add :city, :text, null: false
      add :state, :text, null: false
      add :postal_code, :text, null: false
      add :country, :text, default: "USA"
      add :is_primary, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id,
          references(:companies,
            column: :id,
            name: "addresses_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:addresses, "addresses_company_id_fkey")

    drop table(:addresses)

    drop_if_exists unique_index(
                     :company_relationships,
                     [:from_company_id, :to_company_id, :relationship_type],
                     name: "company_relationships_unique_relationship_index"
                   )

    drop constraint(:company_relationships, "company_relationships_from_company_id_fkey")

    drop constraint(:company_relationships, "company_relationships_to_company_id_fkey")

    drop table(:company_relationships)
  end
end
