defmodule GnomeGarden.Repo.Migrations.AddFindingReviewDecisionsAndAcceptanceHistory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_finding_review_decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :decision, :text, null: false
      add :reason, :text
      add :reason_code, :text
      add :feedback_scope, :text
      add :exclude_terms, {:array, :text}, null: false, default: []
      add :recorded_at, :utc_datetime
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :finding_id,
          references(:acquisition_findings,
            column: :id,
            name: "acquisition_finding_review_decisions_finding_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :actor_user_id,
          references(:users,
            column: :id,
            name: "acquisition_finding_review_decisions_actor_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:acquisition_finding_review_decisions, [:decision, :recorded_at])

    create index(:acquisition_finding_review_decisions, [:finding_id, :recorded_at])
  end

  def down do
    drop constraint(
           :acquisition_finding_review_decisions,
           "acquisition_finding_review_decisions_finding_id_fkey"
         )

    drop constraint(
           :acquisition_finding_review_decisions,
           "acquisition_finding_review_decisions_actor_user_id_fkey"
         )

    drop_if_exists index(:acquisition_finding_review_decisions, [:finding_id, :recorded_at])

    drop_if_exists index(:acquisition_finding_review_decisions, [:decision, :recorded_at])

    drop table(:acquisition_finding_review_decisions)
  end
end
