defmodule GnomeGarden.Repo.Migrations.CompanyGrowth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:company_qualifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :name, :text, null: false
      add :issuing_authority, :text, null: false
      add :identifier, :text
      add :status, :text, null: false, default: "pending"
      add :effective_on, :date
      add :expires_on, :date
      add :renewal_lead_days, :bigint, null: false, default: 60
      add :verification_url, :text
      add :verified_on, :date
      add :unlocks, {:array, :text}, null: false, default: []
      add :details, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_profile_id,
          references(:commercial_company_profiles,
            column: :id,
            name: "company_qualifications_company_profile_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :owner_team_member_id,
          references(:team_members,
            column: :id,
            name: "company_qualifications_owner_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :growth_initiative_id, :uuid
      add :evidence_document_id, :uuid
    end

    create unique_index(
             :company_qualifications,
             [:company_profile_id, :kind, :issuing_authority, :name],
             name: "company_qualifications_unique_capability_index"
           )

    create table(:company_growth_initiatives, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:company_qualifications) do
      modify :growth_initiative_id,
             references(:company_growth_initiatives,
               column: :id,
               name: "company_qualifications_growth_initiative_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :evidence_document_id,
             references(:commercial_company_documents,
               column: :id,
               name: "company_qualifications_evidence_document_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:company_growth_initiatives) do
      add :title, :text, null: false
      add :description, :text
      add :category, :text, null: false, default: "operational_readiness"
      add :status, :text, null: false, default: "idea"
      add :expected_benefit, :text
      add :effort_estimate, :text
      add :target_date, :date
      add :decision_notes, :text
      add :outcome_notes, :text
      add :achieved_at, :utc_datetime
      add :declined_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_profile_id,
          references(:commercial_company_profiles,
            column: :id,
            name: "company_growth_initiatives_company_profile_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :owner_team_member_id,
          references(:team_members,
            column: :id,
            name: "company_growth_initiatives_owner_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :created_by_team_member_id,
          references(:team_members,
            column: :id,
            name: "company_growth_initiatives_created_by_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :decided_by_team_member_id,
          references(:team_members,
            column: :id,
            name: "company_growth_initiatives_decided_by_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:tasks) do
      add :company_growth_initiative_id,
          references(:company_growth_initiatives,
            column: :id,
            name: "tasks_company_growth_initiative_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :company_qualification_id,
          references(:company_qualifications,
            column: :id,
            name: "tasks_company_qualification_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:playbook_runs) do
      add :company_growth_initiative_id,
          references(:company_growth_initiatives,
            column: :id,
            name: "playbook_runs_company_growth_initiative_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:company_growth_initiative_evidence, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :gap_category, :text, null: false, default: "other"
      add :quoted_requirement, :text
      add :observed_value, :text
      add :required_value, :text
      add :confidence, :text, null: false, default: "medium"
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :growth_initiative_id,
          references(:company_growth_initiatives,
            column: :id,
            name: "company_growth_initiative_evidence_growth_initiative_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :bid_id,
          references(:bids,
            column: :id,
            name: "company_growth_initiative_evidence_bid_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :finding_id,
          references(:acquisition_findings,
            column: :id,
            name: "company_growth_initiative_evidence_finding_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :created_by_team_member_id,
          references(:team_members,
            column: :id,
            name: "company_growth_initiative_evidence_created_by_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(
           :company_growth_initiative_evidence,
           "company_growth_initiative_evidence_growth_initiative_id_fkey"
         )

    drop constraint(
           :company_growth_initiative_evidence,
           "company_growth_initiative_evidence_bid_id_fkey"
         )

    drop constraint(
           :company_growth_initiative_evidence,
           "company_growth_initiative_evidence_finding_id_fkey"
         )

    drop constraint(
           :company_growth_initiative_evidence,
           "company_growth_initiative_evidence_created_by_team_member_id_fkey"
         )

    drop table(:company_growth_initiative_evidence)

    drop constraint(:playbook_runs, "playbook_runs_company_growth_initiative_id_fkey")

    alter table(:playbook_runs) do
      remove :company_growth_initiative_id
    end

    drop constraint(:tasks, "tasks_company_growth_initiative_id_fkey")

    drop constraint(:tasks, "tasks_company_qualification_id_fkey")

    alter table(:tasks) do
      remove :company_qualification_id
      remove :company_growth_initiative_id
    end

    drop constraint(
           :company_growth_initiatives,
           "company_growth_initiatives_company_profile_id_fkey"
         )

    drop constraint(
           :company_growth_initiatives,
           "company_growth_initiatives_owner_team_member_id_fkey"
         )

    drop constraint(
           :company_growth_initiatives,
           "company_growth_initiatives_created_by_team_member_id_fkey"
         )

    drop constraint(
           :company_growth_initiatives,
           "company_growth_initiatives_decided_by_team_member_id_fkey"
         )

    alter table(:company_growth_initiatives) do
      remove :decided_by_team_member_id
      remove :created_by_team_member_id
      remove :owner_team_member_id
      remove :company_profile_id
      remove :updated_at
      remove :inserted_at
      remove :declined_at
      remove :achieved_at
      remove :outcome_notes
      remove :decision_notes
      remove :target_date
      remove :effort_estimate
      remove :expected_benefit
      remove :status
      remove :category
      remove :description
      remove :title
    end

    drop constraint(:company_qualifications, "company_qualifications_growth_initiative_id_fkey")

    drop constraint(:company_qualifications, "company_qualifications_evidence_document_id_fkey")

    alter table(:company_qualifications) do
      modify :evidence_document_id, :uuid
      modify :growth_initiative_id, :uuid
    end

    drop table(:company_growth_initiatives)

    drop constraint(:company_qualifications, "company_qualifications_company_profile_id_fkey")

    drop constraint(:company_qualifications, "company_qualifications_owner_team_member_id_fkey")

    drop_if_exists unique_index(
                     :company_qualifications,
                     [:company_profile_id, :kind, :issuing_authority, :name],
                     name: "company_qualifications_unique_capability_index"
                   )

    drop table(:company_qualifications)
  end
end
