defmodule GnomeGarden.Repo.Migrations.AddPeopleAndAffiliations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:execution_service_tickets) do
      add :requester_person_id, :uuid
    end

    create table(:people, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:execution_service_tickets) do
      modify :requester_person_id,
             references(:people,
               column: :id,
               name: "execution_service_tickets_requester_person_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:people) do
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :email, :citext
      add :phone, :text
      add :mobile, :text
      add :status, :text, null: false, default: "active"
      add :linkedin_url, :text
      add :preferred_contact_method, :text
      add :do_not_call, :boolean, null: false, default: false
      add :do_not_email, :boolean, null: false, default: false
      add :timezone, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "people_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:people, [:email], name: "people_unique_email_index")

    create table(:organization_affiliations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :department, :text
      add :contact_roles, {:array, :text}, null: false, default: []
      add :status, :text, null: false, default: "active"
      add :is_primary, :boolean, null: false, default: false
      add :started_on, :date
      add :ended_on, :date
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "organization_affiliations_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :person_id,
          references(:people,
            column: :id,
            name: "organization_affiliations_person_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:organization_affiliations, [:organization_id, :person_id, :status],
             name: "organization_affiliations_unique_active_affiliation_index",
             where: "(status = 'active')"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :organization_affiliations,
                     [:organization_id, :person_id, :status],
                     name: "organization_affiliations_unique_active_affiliation_index"
                   )

    drop constraint(:organization_affiliations, "organization_affiliations_organization_id_fkey")

    drop constraint(:organization_affiliations, "organization_affiliations_person_id_fkey")

    drop table(:organization_affiliations)

    drop_if_exists unique_index(:people, [:email], name: "people_unique_email_index")

    drop constraint(:people, "people_owner_user_id_fkey")

    alter table(:people) do
      remove :owner_user_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :timezone
      remove :do_not_email
      remove :do_not_call
      remove :preferred_contact_method
      remove :linkedin_url
      remove :status
      remove :mobile
      remove :phone
      remove :email
      remove :last_name
      remove :first_name
    end

    drop constraint(
           :execution_service_tickets,
           "execution_service_tickets_requester_person_id_fkey"
         )

    alter table(:execution_service_tickets) do
      modify :requester_person_id, :uuid
    end

    drop table(:people)

    alter table(:execution_service_tickets) do
      remove :requester_person_id
    end
  end
end
