defmodule GnomeGarden.Repo.Migrations.AddInventoryAndMaterialUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:execution_material_usages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :usage_date, :date, null: false
      add :description, :text, null: false
      add :usage_kind, :text, null: false, default: "material"
      add :status, :text, null: false, default: "planned"
      add :quantity, :decimal, null: false
      add :unit_cost, :decimal
      add :unit_price, :decimal
      add :billable, :boolean, null: false, default: true
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "execution_material_usages_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :project_id,
          references(:execution_projects,
            column: :id,
            name: "execution_material_usages_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :work_item_id,
          references(:execution_work_items,
            column: :id,
            name: "execution_material_usages_work_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :work_order_id,
          references(:execution_work_orders,
            column: :id,
            name: "execution_material_usages_work_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :asset_id,
          references(:assets,
            column: :id,
            name: "execution_material_usages_asset_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :inventory_item_id, :uuid
      add :used_by_user_id, :uuid
    end

    create table(:operations_inventory_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:execution_material_usages) do
      modify :inventory_item_id,
             references(:operations_inventory_items,
               column: :id,
               name: "execution_material_usages_inventory_item_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :used_by_user_id,
             references(:users,
               column: :id,
               name: "execution_material_usages_used_by_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:operations_inventory_items) do
      add :sku, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :item_type, :text, null: false, default: "other"
      add :unit_of_measure, :text, null: false, default: "each"
      add :tracked_inventory, :boolean, null: false, default: false
      add :quantity_on_hand, :decimal, null: false, default: "0"
      add :reorder_level, :decimal
      add :standard_cost, :decimal
      add :bill_rate, :decimal
      add :active, :boolean, null: false, default: true
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :supplier_organization_id,
          references(:organizations,
            column: :id,
            name: "operations_inventory_items_supplier_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:operations_inventory_items, [:sku],
             name: "operations_inventory_items_sku_idx"
           )
  end

  def down do
    drop_if_exists unique_index(:operations_inventory_items, [:sku],
                     name: "operations_inventory_items_sku_idx"
                   )

    drop constraint(
           :operations_inventory_items,
           "operations_inventory_items_supplier_organization_id_fkey"
         )

    alter table(:operations_inventory_items) do
      remove :supplier_organization_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :active
      remove :bill_rate
      remove :standard_cost
      remove :reorder_level
      remove :quantity_on_hand
      remove :tracked_inventory
      remove :unit_of_measure
      remove :item_type
      remove :description
      remove :name
      remove :sku
    end

    drop constraint(
           :execution_material_usages,
           "execution_material_usages_inventory_item_id_fkey"
         )

    drop constraint(:execution_material_usages, "execution_material_usages_used_by_user_id_fkey")

    alter table(:execution_material_usages) do
      modify :used_by_user_id, :uuid
      modify :inventory_item_id, :uuid
    end

    drop table(:operations_inventory_items)

    drop constraint(:execution_material_usages, "execution_material_usages_organization_id_fkey")

    drop constraint(:execution_material_usages, "execution_material_usages_project_id_fkey")

    drop constraint(:execution_material_usages, "execution_material_usages_work_item_id_fkey")

    drop constraint(:execution_material_usages, "execution_material_usages_work_order_id_fkey")

    drop constraint(:execution_material_usages, "execution_material_usages_asset_id_fkey")

    drop table(:execution_material_usages)
  end
end
