defmodule GnomeGarden.Repo.Migrations.AddSyncRunCountFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:banking_sync_runs) do
      add :accounts_seen_count, :bigint, default: 0
      add :transactions_seen_count, :bigint, default: 0
      add :transactions_created_count, :bigint, default: 0
      add :transactions_updated_count, :bigint, default: 0
    end
  end

  def down do
    alter table(:banking_sync_runs) do
      remove :transactions_updated_count
      remove :transactions_created_count
      remove :transactions_seen_count
      remove :accounts_seen_count
    end
  end
end
