defmodule GnomeGarden.Repo.Migrations.AddProcurementSourceSearchFilters do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:procurement_source_search_filters, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :filter_type, :text, null: false, default: "naics"
      add :value, :text, null: false
      add :label, :text
      add :priority, :text, null: false, default: "medium"
      add :enabled, :boolean, null: false, default: true
      add :per_run_limit, :bigint, null: false, default: 5
      add :last_returned_count, :bigint, null: false, default: 0
      add :last_saved_count, :bigint, null: false, default: 0
      add :last_run_at, :utc_datetime
      add :notes, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :procurement_source_id,
          references(:procurement_sources,
            column: :id,
            name: "procurement_source_search_filters_procurement_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:procurement_source_search_filters, [:filter_type, :value])

    create index(:procurement_source_search_filters, [:procurement_source_id, :enabled, :priority])

    create unique_index(
             :procurement_source_search_filters,
             [:procurement_source_id, :filter_type, :value],
             name: "procurement_source_search_filters_unique_source_filter_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :procurement_source_search_filters,
                     [:procurement_source_id, :filter_type, :value],
                     name: "procurement_source_search_filters_unique_source_filter_index"
                   )

    drop constraint(
           :procurement_source_search_filters,
           "procurement_source_search_filters_procurement_source_id_fkey"
         )

    drop_if_exists index(:procurement_source_search_filters, [
                     :procurement_source_id,
                     :enabled,
                     :priority
                   ])

    drop_if_exists index(:procurement_source_search_filters, [:filter_type, :value])

    drop table(:procurement_source_search_filters)
  end
end
