defmodule GnomeGarden.Repo.Migrations.AddSourceBrowserSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:procurement_source_browser_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :session_family, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :browser_name, :text, null: false, default: "chromium"
      add :storage_state_path, :text
      add :storage_state_fingerprint, :text
      add :verified_at, :utc_datetime
      add :expires_at, :utc_datetime
      add :last_refresh_started_at, :utc_datetime
      add :last_refresh_completed_at, :utc_datetime
      add :last_failure_reason, :text
      add :trace_path, :text
      add :screenshot_path, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :procurement_source_id,
          references(:procurement_sources,
            column: :id,
            name: "procurement_source_browser_sessions_procurement_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :source_credential_id,
          references(:procurement_source_credentials,
            column: :id,
            name: "procurement_source_browser_sessions_source_credential_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:procurement_source_browser_sessions, [:session_family, :status])

    create index(:procurement_source_browser_sessions, [:source_credential_id, :status])

    create index(:procurement_source_browser_sessions, [
             :procurement_source_id,
             :provider,
             :status
           ])
  end

  def down do
    drop constraint(
           :procurement_source_browser_sessions,
           "procurement_source_browser_sessions_procurement_source_id_fkey"
         )

    drop constraint(
           :procurement_source_browser_sessions,
           "procurement_source_browser_sessions_source_credential_id_fkey"
         )

    drop_if_exists index(:procurement_source_browser_sessions, [
                     :procurement_source_id,
                     :provider,
                     :status
                   ])

    drop_if_exists index(:procurement_source_browser_sessions, [:source_credential_id, :status])

    drop_if_exists index(:procurement_source_browser_sessions, [:session_family, :status])

    drop table(:procurement_source_browser_sessions)
  end
end
