defmodule GnomeGarden.Repo.Migrations.AddVendorsAndVendorBills do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "CREATE SEQUENCE finance_vendor_bill_number_seq START 1"

    create table(:finance_vendor_bills, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bill_number, :text, null: false
      add :issued_on, :date, null: false
      add :due_on, :date
      add :description, :text, null: false
      add :total_amount, :decimal, null: false
      add :status, :text, null: false, default: "draft"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :vendor_id, :uuid, null: false
    end

    create table(:finance_vendors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:finance_vendor_bills) do
      modify :vendor_id,
             references(:finance_vendors,
               column: :id,
               name: "finance_vendor_bills_vendor_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:finance_vendors) do
      add :name, :text, null: false
      add :email, :text
      add :phone, :text
      add :address, :text
      add :payment_terms_days, :bigint, default: 30
      add :notes, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    execute "DROP SEQUENCE IF EXISTS finance_vendor_bill_number_seq"

    alter table(:finance_vendors) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :notes
      remove :payment_terms_days
      remove :address
      remove :phone
      remove :email
      remove :name
    end

    drop constraint(:finance_vendor_bills, "finance_vendor_bills_vendor_id_fkey")

    alter table(:finance_vendor_bills) do
      modify :vendor_id, :uuid
    end

    drop table(:finance_vendors)

    drop table(:finance_vendor_bills)
  end
end
