defmodule GnomeGarden.Repo.Migrations.AddResearchRequests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:research_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :state, :text, null: false, default: "requested"
      add :research_type, :text, null: false
      add :priority, :text, default: "normal"
      add :notes, :text
      add :findings, :text
      add :due_at, :utc_datetime
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :researchable_type, :text, null: false
      add :researchable_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :requested_by_id,
          references(:users,
            column: :id,
            name: "research_requests_requested_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :assigned_to_id,
          references(:users,
            column: :id,
            name: "research_requests_assigned_to_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:research_requests, "research_requests_requested_by_id_fkey")

    drop constraint(:research_requests, "research_requests_assigned_to_id_fkey")

    drop table(:research_requests)
  end
end
