defmodule GnomeGarden.Repo.Migrations.AddAssetsAndMaintenancePlans do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:assets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :asset_tag, :text
      add :name, :text, null: false
      add :description, :text
      add :asset_type, :text, null: false, default: "other"
      add :delivery_mode, :text, null: false, default: "physical"
      add :lifecycle_status, :text, null: false, default: "planned"
      add :criticality, :text, null: false, default: "normal"
      add :vendor, :text
      add :model_number, :text
      add :serial_number, :text
      add :installed_on, :date
      add :commissioned_on, :date
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "assets_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :site_id,
          references(:sites,
            column: :id,
            name: "assets_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :managed_system_id,
          references(:managed_systems,
            column: :id,
            name: "assets_managed_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :parent_asset_id,
          references(:assets,
            column: :id,
            name: "assets_parent_asset_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:assets, [:organization_id, :asset_tag],
             name: "assets_unique_asset_tag_per_organization_index"
           )

    alter table(:execution_work_orders) do
      add :asset_id,
          references(:assets,
            column: :id,
            name: "execution_work_orders_asset_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :maintenance_plan_id, :uuid
    end

    create table(:execution_maintenance_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:execution_work_orders) do
      modify :maintenance_plan_id,
             references(:execution_maintenance_plans,
               column: :id,
               name: "execution_work_orders_maintenance_plan_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:execution_maintenance_plans) do
      add :name, :text, null: false
      add :description, :text
      add :plan_type, :text, null: false, default: "preventive_maintenance"
      add :interval_unit, :text, null: false, default: "month"
      add :interval_value, :bigint, null: false, default: 1
      add :next_due_on, :date
      add :last_completed_on, :date
      add :status, :text, null: false, default: "active"
      add :auto_create_work_orders, :boolean, null: false, default: false
      add :billable, :boolean, null: false, default: true
      add :estimated_minutes, :bigint
      add :priority, :text, null: false, default: "normal"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "execution_maintenance_plans_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :site_id,
          references(:sites,
            column: :id,
            name: "execution_maintenance_plans_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :managed_system_id,
          references(:managed_systems,
            column: :id,
            name: "execution_maintenance_plans_managed_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :asset_id,
          references(:assets,
            column: :id,
            name: "execution_maintenance_plans_asset_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "execution_maintenance_plans_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :assigned_user_id,
          references(:users,
            column: :id,
            name: "execution_maintenance_plans_assigned_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(
           :execution_maintenance_plans,
           "execution_maintenance_plans_organization_id_fkey"
         )

    drop constraint(:execution_maintenance_plans, "execution_maintenance_plans_site_id_fkey")

    drop constraint(
           :execution_maintenance_plans,
           "execution_maintenance_plans_managed_system_id_fkey"
         )

    drop constraint(:execution_maintenance_plans, "execution_maintenance_plans_asset_id_fkey")

    drop constraint(:execution_maintenance_plans, "execution_maintenance_plans_agreement_id_fkey")

    drop constraint(
           :execution_maintenance_plans,
           "execution_maintenance_plans_assigned_user_id_fkey"
         )

    alter table(:execution_maintenance_plans) do
      remove :assigned_user_id
      remove :agreement_id
      remove :asset_id
      remove :managed_system_id
      remove :site_id
      remove :organization_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :priority
      remove :estimated_minutes
      remove :billable
      remove :auto_create_work_orders
      remove :status
      remove :last_completed_on
      remove :next_due_on
      remove :interval_value
      remove :interval_unit
      remove :plan_type
      remove :description
      remove :name
    end

    drop constraint(:execution_work_orders, "execution_work_orders_maintenance_plan_id_fkey")

    alter table(:execution_work_orders) do
      modify :maintenance_plan_id, :uuid
    end

    drop table(:execution_maintenance_plans)

    drop constraint(:execution_work_orders, "execution_work_orders_asset_id_fkey")

    alter table(:execution_work_orders) do
      remove :maintenance_plan_id
      remove :asset_id
    end

    drop_if_exists unique_index(:assets, [:organization_id, :asset_tag],
                     name: "assets_unique_asset_tag_per_organization_index"
                   )

    drop constraint(:assets, "assets_organization_id_fkey")

    drop constraint(:assets, "assets_site_id_fkey")

    drop constraint(:assets, "assets_managed_system_id_fkey")

    drop constraint(:assets, "assets_parent_asset_id_fkey")

    drop table(:assets)
  end
end
