defmodule GnomeGarden.Repo.Migrations.AddLeadOriginToAcquisitionFindings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:acquisition_findings) do
      add :source_lead_id,
          references(:leads,
            column: :id,
            name: "acquisition_findings_source_lead_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:acquisition_findings, [:source_lead_id],
             name: "acquisition_findings_unique_source_lead_index"
           )
  end

  def down do
    drop_if_exists unique_index(:acquisition_findings, [:source_lead_id],
                     name: "acquisition_findings_unique_source_lead_index"
                   )

    drop constraint(:acquisition_findings, "acquisition_findings_source_lead_id_fkey")

    alter table(:acquisition_findings) do
      remove :source_lead_id
    end
  end
end
