defmodule GnomeGarden.Repo.Migrations.AddDiscoveryProgramModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_discovery_programs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :program_type, :text, null: false, default: "market_scan"
      add :priority, :text, null: false, default: "normal"
      add :status, :text, null: false, default: "draft"
      add :target_regions, {:array, :text}, null: false, default: []
      add :target_industries, {:array, :text}, null: false, default: []
      add :search_terms, {:array, :text}, null: false, default: []
      add :watch_channels, {:array, :text}, null: false, default: []
      add :cadence_hours, :bigint, null: false, default: 168
      add :last_run_at, :utc_datetime
      add :notes, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "commercial_discovery_programs_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:commercial_discovery_programs, [:name],
             name: "commercial_discovery_programs_unique_name_index"
           )

    alter table(:commercial_target_observations) do
      add :discovery_program_id,
          references(:commercial_discovery_programs,
            column: :id,
            name: "commercial_target_observations_discovery_program_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:commercial_target_accounts) do
      add :discovery_program_id,
          references(:commercial_discovery_programs,
            column: :id,
            name: "commercial_target_accounts_discovery_program_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(
           :commercial_target_accounts,
           "commercial_target_accounts_discovery_program_id_fkey"
         )

    alter table(:commercial_target_accounts) do
      remove :discovery_program_id
    end

    drop constraint(
           :commercial_target_observations,
           "commercial_target_observations_discovery_program_id_fkey"
         )

    alter table(:commercial_target_observations) do
      remove :discovery_program_id
    end

    drop_if_exists unique_index(:commercial_discovery_programs, [:name],
                     name: "commercial_discovery_programs_unique_name_index"
                   )

    drop constraint(
           :commercial_discovery_programs,
           "commercial_discovery_programs_owner_user_id_fkey"
         )

    drop table(:commercial_discovery_programs)
  end
end
