defmodule GnomeGarden.Repo.Migrations.RestrictBrowserSessionCredentialDeletion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(
           :procurement_source_browser_sessions,
           "procurement_source_browser_sessions_source_credential_id_fkey"
         )

    alter table(:procurement_source_browser_sessions) do
      modify :source_credential_id,
             references(:procurement_source_credentials,
               column: :id,
               name: "procurement_source_browser_sessions_source_credential_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end
  end

  def down do
    drop constraint(
           :procurement_source_browser_sessions,
           "procurement_source_browser_sessions_source_credential_id_fkey"
         )

    alter table(:procurement_source_browser_sessions) do
      modify :source_credential_id,
             references(:procurement_source_credentials,
               column: :id,
               name: "procurement_source_browser_sessions_source_credential_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end
  end
end
