defmodule GnomeGarden.Repo.Migrations.RecurringInvoices do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:finance_invoices) do
      add :recurring_invoice_id, :uuid
    end
  end

  def down do
    alter table(:finance_invoices) do
      remove :recurring_invoice_id
    end
  end
end
