defmodule GnomeGarden.Repo.Migrations.AddAcquisitionProgramSources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_program_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :enabled, :boolean, null: false, default: false
      add :status, :text, null: false, default: "draft"
      add :priority, :bigint, null: false, default: 0
      add :query_templates, {:array, :text}, null: false, default: []
      add :cadence_minutes, :bigint, null: false, default: 1440
      add :max_queries_per_run, :bigint, null: false, default: 8
      add :max_results_per_query, :bigint, null: false, default: 8
      add :spend_limit_per_run, :money_with_currency, null: false
      add :spend_limit_per_day, :money_with_currency, null: false
      add :enrichment_policy, :text, null: false, default: "verify_promotable"
      add :max_enrichments_per_run, :bigint, null: false, default: 5
      add :finding_limit_per_run, :bigint, null: false, default: 5
      add :finding_limit_per_day, :bigint, null: false, default: 25
      add :next_run_at, :utc_datetime
      add :last_run_at, :utc_datetime
      add :blocked_reason, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :program_id,
          references(:acquisition_programs,
            column: :id,
            name: "acquisition_program_sources_program_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :source_id,
          references(:acquisition_sources,
            column: :id,
            name: "acquisition_program_sources_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:acquisition_program_sources, [:status, :enabled, :next_run_at])

    create unique_index(:acquisition_program_sources, [:program_id, :source_id],
             name: "acquisition_program_sources_program_source_index"
           )

    alter table(:acquisition_findings) do
      add :program_source_id,
          references(:acquisition_program_sources,
            column: :id,
            name: "acquisition_findings_program_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:acquisition_findings, "acquisition_findings_program_source_id_fkey")

    alter table(:acquisition_findings) do
      remove :program_source_id
    end

    drop constraint(:acquisition_program_sources, "acquisition_program_sources_program_id_fkey")

    drop constraint(:acquisition_program_sources, "acquisition_program_sources_source_id_fkey")

    drop_if_exists unique_index(:acquisition_program_sources, [:program_id, :source_id],
                     name: "acquisition_program_sources_program_source_index"
                   )

    drop_if_exists index(:acquisition_program_sources, [:status, :enabled, :next_run_at])

    drop table(:acquisition_program_sources)
  end
end
