defmodule GnomeGarden.Repo.Migrations.AlignBidWithCommercialModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bids) do
      remove :agency_company_id
      remove :opportunity_id

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "bids_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:bids, "bids_organization_id_fkey")

    alter table(:bids) do
      remove :organization_id

      add :opportunity_id,
          references(:opportunities,
            column: :id,
            name: "bids_opportunity_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :agency_company_id,
          references(:companies,
            column: :id,
            name: "bids_agency_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
