defmodule GnomeGarden.Repo.Migrations.AddProcurementSourceHierarchy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:procurement_sources) do
      add :parent_source_id,
          references(:procurement_sources,
            column: :id,
            name: "procurement_sources_parent_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:procurement_sources, [:parent_source_id, :portal_id],
             name: "procurement_sources_unique_parent_portal_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:procurement_sources, [:parent_source_id, :portal_id],
                     name: "procurement_sources_unique_parent_portal_id_index"
                   )

    drop constraint(:procurement_sources, "procurement_sources_parent_source_id_fkey")

    alter table(:procurement_sources) do
      remove :parent_source_id
    end
  end
end
