defmodule GnomeGarden.Repo.Migrations.AddCompanyComplianceAndSourceReview do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:company_compliance_obligations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :title, :text, null: false
      add :category, :text, null: false, default: "other"
      add :status, :text, null: false, default: "needs_review"
      add :summary, :text
      add :due_on, :date
      add :completed_on, :date
      add :source_path, :text
      add :source_commit, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_profile_id,
          references(:commercial_company_profiles,
            column: :id,
            name: "company_compliance_obligations_company_profile_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:company_compliance_obligations, [:company_profile_id, :key],
             name: "company_compliance_profile_key_idx"
           )

    create table(:company_source_review_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :title, :text, null: false
      add :status, :text, null: false, default: "needs_review"
      add :source_path, :text, null: false
      add :source_commit, :text
      add :evidence_date, :date
      add :target_resource, :text
      add :summary, :text
      add :recommendation, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_profile_id,
          references(:commercial_company_profiles,
            column: :id,
            name: "company_source_review_items_company_profile_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:company_source_review_items, [:company_profile_id, :key],
             name: "company_source_review_profile_key_idx"
           )
  end

  def down do
    drop constraint(
           :company_source_review_items,
           "company_source_review_items_company_profile_id_fkey"
         )

    drop_if_exists unique_index(:company_source_review_items, [:company_profile_id, :key],
                     name: "company_source_review_profile_key_idx"
                   )

    drop table(:company_source_review_items)

    drop constraint(
           :company_compliance_obligations,
           "company_compliance_obligations_company_profile_id_fkey"
         )

    drop_if_exists unique_index(:company_compliance_obligations, [:company_profile_id, :key],
                     name: "company_compliance_profile_key_idx"
                   )

    drop table(:company_compliance_obligations)
  end
end
