defmodule GnomeGarden.Repo.Migrations.RemoveDuplicateAdmissionCaps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:acquisition_lead_admission_policies) do
      remove :finding_daily_limit
      remove :finding_run_limit
      remove :candidate_limit
    end
  end

  def down do
    alter table(:acquisition_lead_admission_policies) do
      add :candidate_limit, :bigint, null: false, default: 5
      add :finding_run_limit, :bigint, null: false, default: 3
      add :finding_daily_limit, :bigint, null: false, default: 20
    end
  end
end
