defmodule GnomeGarden.Repo.Migrations.AddVerifiedFindingAdmission do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_finding_admission_capacities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scope, :text, null: false
      add :scope_key, :text, null: false
      add :window_started_at, :utc_datetime, null: false
      add :resets_at, :utc_datetime
      add :admission_limit, :bigint, null: false
      add :admitted_count, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:acquisition_finding_admission_capacities, [:scope, :resets_at])

    create unique_index(:acquisition_finding_admission_capacities, [:scope, :scope_key],
             name: "finding_admission_capacities_scope_key_index"
           )

    alter table(:commercial_discovery_runs) do
      add :verified_count, :bigint, null: false, default: 0
      add :admitted_count, :bigint, null: false, default: 0
      add :unresolved_count, :bigint, null: false, default: 0
      add :enrichment_cost, :decimal, null: false, default: "0"
    end

    create table(:acquisition_finding_admissions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :identity_key, :text, null: false
      add :admitted_at, :utc_datetime, null: false
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :lead_candidate_verification_id, :uuid, null: false
      add :lead_preview_candidate_id, :uuid, null: false
      add :lead_preview_run_id, :uuid, null: false
      add :finding_id, :uuid, null: false
    end

    create index(:acquisition_finding_admissions, [:lead_preview_run_id, :admitted_at])

    create unique_index(:acquisition_finding_admissions, [:lead_preview_candidate_id],
             name: "acquisition_finding_admissions_unique_candidate_index"
           )

    create unique_index(:acquisition_finding_admissions, [:finding_id],
             name: "acquisition_finding_admissions_unique_finding_index"
           )

    create unique_index(:acquisition_finding_admissions, [:identity_key],
             name: "acquisition_finding_admissions_unique_identity_key_index"
           )

    create unique_index(:acquisition_finding_admissions, [:lead_candidate_verification_id],
             name: "acquisition_finding_admissions_unique_verification_index"
           )

    create table(:acquisition_lead_candidate_verifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:acquisition_finding_admissions) do
      modify :lead_candidate_verification_id,
             references(:acquisition_lead_candidate_verifications,
               column: :id,
               name: "acquisition_finding_admissions_lead_candidate_verification_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :lead_preview_candidate_id,
             references(:acquisition_lead_preview_candidates,
               column: :id,
               name: "acquisition_finding_admissions_lead_preview_candidate_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :lead_preview_run_id,
             references(:acquisition_lead_preview_runs,
               column: :id,
               name: "acquisition_finding_admissions_lead_preview_run_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :finding_id,
             references(:acquisition_findings,
               column: :id,
               name: "acquisition_finding_admissions_finding_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:acquisition_lead_candidate_verifications) do
      add :status, :text, null: false
      add :reason, :text, null: false
      add :website_domain, :text
      add :search_score, :decimal
      add :verification_score, :bigint
      add :evidence, :map, null: false, default: %{}
      add :provider_reservation_key, :text
      add :actual_cost, :decimal, null: false, default: "0"
      add :verified_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :lead_preview_candidate_id,
          references(:acquisition_lead_preview_candidates,
            column: :id,
            name: "acquisition_lead_candidate_verifications_lead_preview_candidate_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:acquisition_lead_candidate_verifications, [:status, :verified_at])

    create unique_index(:acquisition_lead_candidate_verifications, [:lead_preview_candidate_id],
             name: "acquisition_lead_candidate_verifications_unique_candidate_index"
           )
  end

  def down do
    drop constraint(
           :acquisition_lead_candidate_verifications,
           "acquisition_lead_candidate_verifications_lead_preview_candidate_id_fkey"
         )

    drop_if_exists unique_index(
                     :acquisition_lead_candidate_verifications,
                     [:lead_preview_candidate_id],
                     name: "acquisition_lead_candidate_verifications_unique_candidate_index"
                   )

    drop_if_exists index(:acquisition_lead_candidate_verifications, [:status, :verified_at])

    alter table(:acquisition_lead_candidate_verifications) do
      remove :lead_preview_candidate_id
      remove :updated_at
      remove :inserted_at
      remove :verified_at
      remove :actual_cost
      remove :provider_reservation_key
      remove :evidence
      remove :verification_score
      remove :search_score
      remove :website_domain
      remove :reason
      remove :status
    end

    drop constraint(
           :acquisition_finding_admissions,
           "acquisition_finding_admissions_lead_candidate_verification_id_fkey"
         )

    drop constraint(
           :acquisition_finding_admissions,
           "acquisition_finding_admissions_lead_preview_candidate_id_fkey"
         )

    drop constraint(
           :acquisition_finding_admissions,
           "acquisition_finding_admissions_lead_preview_run_id_fkey"
         )

    drop constraint(
           :acquisition_finding_admissions,
           "acquisition_finding_admissions_finding_id_fkey"
         )

    alter table(:acquisition_finding_admissions) do
      modify :finding_id, :uuid
      modify :lead_preview_run_id, :uuid
      modify :lead_preview_candidate_id, :uuid
      modify :lead_candidate_verification_id, :uuid
    end

    drop table(:acquisition_lead_candidate_verifications)

    drop_if_exists unique_index(
                     :acquisition_finding_admissions,
                     [:lead_candidate_verification_id],
                     name: "acquisition_finding_admissions_unique_verification_index"
                   )

    drop_if_exists unique_index(:acquisition_finding_admissions, [:identity_key],
                     name: "acquisition_finding_admissions_unique_identity_key_index"
                   )

    drop_if_exists unique_index(:acquisition_finding_admissions, [:finding_id],
                     name: "acquisition_finding_admissions_unique_finding_index"
                   )

    drop_if_exists unique_index(:acquisition_finding_admissions, [:lead_preview_candidate_id],
                     name: "acquisition_finding_admissions_unique_candidate_index"
                   )

    drop_if_exists index(:acquisition_finding_admissions, [:lead_preview_run_id, :admitted_at])

    drop table(:acquisition_finding_admissions)

    alter table(:commercial_discovery_runs) do
      remove :enrichment_cost
      remove :unresolved_count
      remove :admitted_count
      remove :verified_count
    end

    drop_if_exists unique_index(:acquisition_finding_admission_capacities, [:scope, :scope_key],
                     name: "finding_admission_capacities_scope_key_index"
                   )

    drop_if_exists index(:acquisition_finding_admission_capacities, [:scope, :resets_at])

    drop table(:acquisition_finding_admission_capacities)
  end
end
