defmodule GnomeGarden.Repo.Migrations.AddDiscoveryFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lead_sources) do
      add :scrape_config, :map, default: %{}
      add :discovery_status, :text, default: "pending"
      add :discovered_at, :utc_datetime
    end
  end

  def down do
    alter table(:lead_sources) do
      remove :discovered_at
      remove :discovery_status
      remove :scrape_config
    end
  end
end
