defmodule GnomeGarden.Repo.Migrations.AddResearchLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:research_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :context, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :research_request_id,
          references(:research_requests,
            column: :id,
            name: "research_links_research_request_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :bid_id,
          references(:bids,
            column: :id,
            name: "research_links_bid_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :company_id,
          references(:companies,
            column: :id,
            name: "research_links_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :opportunity_id,
          references(:opportunities,
            column: :id,
            name: "research_links_opportunity_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :event_id,
          references(:sales_events,
            column: :id,
            name: "research_links_event_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :lead_id,
          references(:leads,
            column: :id,
            name: "research_links_lead_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :prospect_id,
          references(:prospects,
            column: :id,
            name: "research_links_prospect_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:bids) do
      modify :status, :text, null: false
    end
  end

  def down do
    alter table(:bids) do
      modify :status, :text, null: true
    end

    drop constraint(:research_links, "research_links_research_request_id_fkey")

    drop constraint(:research_links, "research_links_bid_id_fkey")

    drop constraint(:research_links, "research_links_company_id_fkey")

    drop constraint(:research_links, "research_links_opportunity_id_fkey")

    drop constraint(:research_links, "research_links_event_id_fkey")

    drop constraint(:research_links, "research_links_lead_id_fkey")

    drop constraint(:research_links, "research_links_prospect_id_fkey")

    drop table(:research_links)
  end
end
