defmodule GnomeGarden.Repo.Migrations.TaskOwnerStatusIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:tasks, [:owner_team_member_id, :status, :due_at])
  end

  def down do
    drop_if_exists index(:tasks, [:owner_team_member_id, :status, :due_at])
  end
end
