defmodule GnomeGarden.Repo.Migrations.AddBidScoreContextFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bids) do
      add :score_recommendation, :text
      add :score_icp_matches, {:array, :text}, default: []
      add :score_risk_flags, {:array, :text}, default: []
      add :score_company_profile_key, :text
      add :score_company_profile_mode, :text
      add :score_source_confidence, :text
    end
  end

  def down do
    alter table(:bids) do
      remove :score_source_confidence
      remove :score_company_profile_mode
      remove :score_company_profile_key
      remove :score_risk_flags
      remove :score_icp_matches
      remove :score_recommendation
    end
  end
end
