defmodule GnomeGarden.Repo.Migrations.AddLeadDescriptionAndSourceUrl do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:leads) do
      add :source_url, :text
      add :description, :text
    end
  end

  def down do
    alter table(:leads) do
      remove :description
      remove :source_url
    end
  end
end
