defmodule GnomeGarden.Repo.Migrations.AddDiscoveryIdentityResolution do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :name_key, :text
    end

    alter table(:commercial_target_accounts) do
      add :name_key, :text

      add :contact_person_id,
          references(:people,
            column: :id,
            name: "commercial_target_accounts_contact_person_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    drop_if_exists unique_index(:commercial_target_accounts, [:name, :location],
                     name: "commercial_target_accounts_unique_name_location_index"
                   )

    create unique_index(:commercial_target_accounts, [:name_key, :location],
             name: "commercial_target_accounts_unique_name_key_location_index"
           )

    alter table(:people) do
      add :email_domain, :text
      add :name_key, :text
    end
  end

  def down do
    alter table(:people) do
      remove :name_key
      remove :email_domain
    end

    drop_if_exists unique_index(:commercial_target_accounts, [:name_key, :location],
                     name: "commercial_target_accounts_unique_name_key_location_index"
                   )

    create unique_index(:commercial_target_accounts, [:name, :location],
             name: "commercial_target_accounts_unique_name_location_index"
           )

    drop constraint(
           :commercial_target_accounts,
           "commercial_target_accounts_contact_person_id_fkey"
         )

    alter table(:commercial_target_accounts) do
      remove :contact_person_id
      remove :name_key
    end

    alter table(:organizations) do
      remove :name_key
    end
  end
end
