defmodule GnomeGarden.Repo.Migrations.RenameDiscoveryToConfigStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lead_sources) do
      remove :discovery_notes
      remove :discovered_by
      remove :discovered_at
      remove :discovery_status
      add :config_status, :text, default: "pending"
      add :configured_at, :utc_datetime
      add :added_by, :text
      add :notes, :text
      add :state, :text, null: false, default: "pending"
    end
  end

  def down do
    alter table(:lead_sources) do
      remove :state
      remove :notes
      remove :added_by
      remove :configured_at
      remove :config_status
      add :discovery_status, :text, default: "pending"
      add :discovered_at, :utc_datetime
      add :discovered_by, :text
      add :discovery_notes, :text
    end
  end
end
