defmodule GnomeGarden.Repo.Migrations.AddProcurementCrawlTraversal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:procurement_crawl_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :seed_url, :text, null: false
      add :run_kind, :text, null: false, default: "scan"
      add :status, :text, null: false, default: "queued"
      add :max_depth, :bigint, null: false, default: 0
      add :max_pages, :bigint, null: false, default: 1
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :summary, :map, null: false, default: %{}
      add :diagnostics, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :procurement_source_id,
          references(:procurement_sources,
            column: :id,
            name: "procurement_crawl_runs_procurement_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:procurement_crawl_runs, [:status, :run_kind])

    create index(:procurement_crawl_runs, [:procurement_source_id, :started_at])

    create table(:procurement_extraction_candidates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :candidate_type, :text, null: false
      add :status, :text, null: false, default: "proposed"
      add :payload, :map, null: false, default: %{}
      add :confidence, :decimal
      add :evidence, :map, null: false, default: %{}
      add :rejection_reason, :text
      add :content_hash, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :crawl_run_id,
          references(:procurement_crawl_runs,
            column: :id,
            name: "procurement_extraction_candidates_crawl_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :crawl_page_id, :uuid, null: false
    end

    create index(:procurement_extraction_candidates, [:content_hash])

    create index(:procurement_extraction_candidates, [:crawl_page_id])

    create index(:procurement_extraction_candidates, [:crawl_run_id, :candidate_type, :status])

    create table(:procurement_page_artifacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :body, :text
      add :storage_key, :text
      add :byte_size, :bigint, null: false, default: 0
      add :content_hash, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :crawl_page_id, :uuid, null: false
    end

    create index(:procurement_page_artifacts, [:content_hash])

    create index(:procurement_page_artifacts, [:crawl_page_id, :kind])

    create table(:procurement_crawl_edges, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :to_url, :text, null: false
      add :link_text, :text
      add :selector, :text
      add :edge_type, :text, null: false, default: "link"
      add :ordinal, :bigint
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :crawl_run_id,
          references(:procurement_crawl_runs,
            column: :id,
            name: "procurement_crawl_edges_crawl_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :from_page_id, :uuid, null: false
      add :to_page_id, :uuid
    end

    create index(:procurement_crawl_edges, [:to_url])

    create index(:procurement_crawl_edges, [:to_page_id])

    create index(:procurement_crawl_edges, [:from_page_id])

    create index(:procurement_crawl_edges, [:crawl_run_id, :edge_type])

    create table(:procurement_crawl_pages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:procurement_extraction_candidates) do
      modify :crawl_page_id,
             references(:procurement_crawl_pages,
               column: :id,
               name: "procurement_extraction_candidates_crawl_page_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:procurement_page_artifacts) do
      modify :crawl_page_id,
             references(:procurement_crawl_pages,
               column: :id,
               name: "procurement_page_artifacts_crawl_page_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:procurement_crawl_edges) do
      modify :from_page_id,
             references(:procurement_crawl_pages,
               column: :id,
               name: "procurement_crawl_edges_from_page_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :to_page_id,
             references(:procurement_crawl_pages,
               column: :id,
               name: "procurement_crawl_edges_to_page_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:procurement_crawl_pages) do
      add :url, :text, null: false
      add :normalized_url, :text, null: false
      add :final_url, :text
      add :title, :text
      add :status_code, :bigint
      add :content_type, :text
      add :depth, :bigint, null: false, default: 0
      add :content_hash, :text
      add :fetch_status, :text, null: false, default: "fetched"
      add :diagnostics, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :crawl_run_id,
          references(:procurement_crawl_runs,
            column: :id,
            name: "procurement_crawl_pages_crawl_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :first_seen_from_page_id,
          references(:procurement_crawl_pages,
            column: :id,
            name: "procurement_crawl_pages_first_seen_from_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:procurement_crawl_pages, [:content_hash])

    create index(:procurement_crawl_pages, [:normalized_url])

    create index(:procurement_crawl_pages, [:crawl_run_id, :depth])

    create unique_index(:procurement_crawl_pages, [:crawl_run_id, :normalized_url],
             name: "procurement_crawl_pages_run_url_idx"
           )
  end

  def down do
    drop_if_exists unique_index(:procurement_crawl_pages, [:crawl_run_id, :normalized_url],
                     name: "procurement_crawl_pages_run_url_idx"
                   )

    drop constraint(:procurement_crawl_pages, "procurement_crawl_pages_crawl_run_id_fkey")

    drop constraint(:procurement_crawl_pages, "procurement_crawl_pages_first_seen_from_fkey")

    drop_if_exists index(:procurement_crawl_pages, [:crawl_run_id, :depth])

    drop_if_exists index(:procurement_crawl_pages, [:normalized_url])

    drop_if_exists index(:procurement_crawl_pages, [:content_hash])

    alter table(:procurement_crawl_pages) do
      remove :first_seen_from_page_id
      remove :crawl_run_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :diagnostics
      remove :fetch_status
      remove :content_hash
      remove :depth
      remove :content_type
      remove :status_code
      remove :title
      remove :final_url
      remove :normalized_url
      remove :url
    end

    drop constraint(:procurement_crawl_edges, "procurement_crawl_edges_from_page_fkey")

    drop constraint(:procurement_crawl_edges, "procurement_crawl_edges_to_page_fkey")

    alter table(:procurement_crawl_edges) do
      modify :to_page_id, :uuid
      modify :from_page_id, :uuid
    end

    drop constraint(:procurement_page_artifacts, "procurement_page_artifacts_crawl_page_id_fkey")

    alter table(:procurement_page_artifacts) do
      modify :crawl_page_id, :uuid
    end

    drop constraint(
           :procurement_extraction_candidates,
           "procurement_extraction_candidates_crawl_page_id_fkey"
         )

    alter table(:procurement_extraction_candidates) do
      modify :crawl_page_id, :uuid
    end

    drop table(:procurement_crawl_pages)

    drop constraint(:procurement_crawl_edges, "procurement_crawl_edges_crawl_run_id_fkey")

    drop_if_exists index(:procurement_crawl_edges, [:crawl_run_id, :edge_type])

    drop_if_exists index(:procurement_crawl_edges, [:from_page_id])

    drop_if_exists index(:procurement_crawl_edges, [:to_page_id])

    drop_if_exists index(:procurement_crawl_edges, [:to_url])

    drop table(:procurement_crawl_edges)

    drop_if_exists index(:procurement_page_artifacts, [:crawl_page_id, :kind])

    drop_if_exists index(:procurement_page_artifacts, [:content_hash])

    drop table(:procurement_page_artifacts)

    drop constraint(
           :procurement_extraction_candidates,
           "procurement_extraction_candidates_crawl_run_id_fkey"
         )

    drop_if_exists index(:procurement_extraction_candidates, [
                     :crawl_run_id,
                     :candidate_type,
                     :status
                   ])

    drop_if_exists index(:procurement_extraction_candidates, [:crawl_page_id])

    drop_if_exists index(:procurement_extraction_candidates, [:content_hash])

    drop table(:procurement_extraction_candidates)

    drop constraint(:procurement_crawl_runs, "procurement_crawl_runs_procurement_source_id_fkey")

    drop_if_exists index(:procurement_crawl_runs, [:procurement_source_id, :started_at])

    drop_if_exists index(:procurement_crawl_runs, [:status, :run_kind])

    drop table(:procurement_crawl_runs)
  end
end
