defmodule GnomeGarden.Repo.Migrations.AddInvoiceLinesAndPayments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:finance_invoice_lines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :line_number, :bigint, null: false, default: 1
      add :line_kind, :text, null: false, default: "other"
      add :description, :text, null: false
      add :quantity, :decimal, null: false
      add :unit_price, :decimal, null: false
      add :line_total, :decimal, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :invoice_id,
          references(:finance_invoices,
            column: :id,
            name: "finance_invoice_lines_invoice_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "finance_invoice_lines_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "finance_invoice_lines_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :project_id,
          references(:execution_projects,
            column: :id,
            name: "finance_invoice_lines_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :work_order_id,
          references(:execution_work_orders,
            column: :id,
            name: "finance_invoice_lines_work_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :time_entry_id,
          references(:finance_time_entries,
            column: :id,
            name: "finance_invoice_lines_time_entry_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :expense_id,
          references(:finance_expenses,
            column: :id,
            name: "finance_invoice_lines_expense_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:finance_invoice_lines, [:invoice_id, :line_number],
             name: "finance_invoice_lines_unique_line_number_per_invoice_index"
           )

    create table(:finance_payment_applications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false
      add :applied_on, :date
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :payment_id, :uuid, null: false
      add :invoice_id, :uuid, null: false
    end

    create table(:finance_payments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:finance_payment_applications) do
      modify :payment_id,
             references(:finance_payments,
               column: :id,
               name: "finance_payment_applications_payment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :invoice_id,
             references(:finance_invoices,
               column: :id,
               name: "finance_payment_applications_invoice_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:finance_payment_applications, [:payment_id, :invoice_id],
             name: "finance_payment_applications_unique_payment_invoice_pair_index"
           )

    alter table(:finance_payments) do
      add :payment_number, :text
      add :status, :text, null: false, default: "received"
      add :payment_method, :text, null: false, default: "ach"
      add :received_on, :date, null: false
      add :deposited_on, :date
      add :reversed_on, :date
      add :currency_code, :text, null: false, default: "USD"
      add :amount, :decimal, null: false
      add :reference, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "finance_payments_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "finance_payments_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:finance_payments, "finance_payments_organization_id_fkey")

    drop constraint(:finance_payments, "finance_payments_agreement_id_fkey")

    alter table(:finance_payments) do
      remove :agreement_id
      remove :organization_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :reference
      remove :amount
      remove :currency_code
      remove :reversed_on
      remove :deposited_on
      remove :received_on
      remove :payment_method
      remove :status
      remove :payment_number
    end

    drop_if_exists unique_index(:finance_payment_applications, [:payment_id, :invoice_id],
                     name: "finance_payment_applications_unique_payment_invoice_pair_index"
                   )

    drop constraint(:finance_payment_applications, "finance_payment_applications_payment_id_fkey")

    drop constraint(:finance_payment_applications, "finance_payment_applications_invoice_id_fkey")

    alter table(:finance_payment_applications) do
      modify :invoice_id, :uuid
      modify :payment_id, :uuid
    end

    drop table(:finance_payments)

    drop table(:finance_payment_applications)

    drop_if_exists unique_index(:finance_invoice_lines, [:invoice_id, :line_number],
                     name: "finance_invoice_lines_unique_line_number_per_invoice_index"
                   )

    drop constraint(:finance_invoice_lines, "finance_invoice_lines_invoice_id_fkey")

    drop constraint(:finance_invoice_lines, "finance_invoice_lines_organization_id_fkey")

    drop constraint(:finance_invoice_lines, "finance_invoice_lines_agreement_id_fkey")

    drop constraint(:finance_invoice_lines, "finance_invoice_lines_project_id_fkey")

    drop constraint(:finance_invoice_lines, "finance_invoice_lines_work_order_id_fkey")

    drop constraint(:finance_invoice_lines, "finance_invoice_lines_time_entry_id_fkey")

    drop constraint(:finance_invoice_lines, "finance_invoice_lines_expense_id_fkey")

    drop table(:finance_invoice_lines)
  end
end
