defmodule GnomeGarden.Repo.Migrations.AddMercuryPaymentMatches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mercury_payment_matches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :match_source, :text, null: false
      add :matched_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :mercury_transaction_id,
          references(:mercury_transactions,
            column: :id,
            name: "mercury_payment_matches_mercury_transaction_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :finance_payment_id,
          references(:finance_payments,
            column: :id,
            name: "mercury_payment_matches_finance_payment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:mercury_payment_matches, [:mercury_transaction_id, :finance_payment_id],
             name: "mercury_payment_matches_unique_transaction_payment_pair_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :mercury_payment_matches,
                     [:mercury_transaction_id, :finance_payment_id],
                     name: "mercury_payment_matches_unique_transaction_payment_pair_index"
                   )

    drop constraint(
           :mercury_payment_matches,
           "mercury_payment_matches_mercury_transaction_id_fkey"
         )

    drop constraint(:mercury_payment_matches, "mercury_payment_matches_finance_payment_id_fkey")

    drop table(:mercury_payment_matches)
  end
end
