defmodule GnomeGarden.Repo.Migrations.RenameBidProcurementSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bids) do
      remove :lead_source_id

      add :procurement_source_id,
          references(:lead_sources,
            column: :id,
            name: "bids_procurement_source_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:bids, "bids_procurement_source_id_fkey")

    alter table(:bids) do
      remove :procurement_source_id

      add :lead_source_id,
          references(:lead_sources,
            column: :id,
            name: "bids_lead_source_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
