defmodule GnomeGarden.Repo.Migrations.GrowthFlywheel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bids) do
      add :capability_gaps, {:array, :text}, null: false, default: []
    end

    alter table(:company_growth_initiatives) do
      add :procurement_source_id,
          references(:procurement_sources,
            column: :id,
            name: "company_growth_initiatives_procurement_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(
           :company_growth_initiatives,
           "company_growth_initiatives_procurement_source_id_fkey"
         )

    alter table(:company_growth_initiatives) do
      remove :procurement_source_id
    end

    alter table(:bids) do
      remove :capability_gaps
    end
  end
end
