defmodule GnomeGarden.Repo.Migrations.AddDiscountToInvoiceLines do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:finance_invoice_lines) do
      add :discount_percent, :decimal
    end
  end

  def down do
    alter table(:finance_invoice_lines) do
      remove :discount_percent
    end
  end
end
