defmodule GnomeGarden.Repo.Migrations.AddOperationsMemoryEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:operations_memory_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :content, :text, null: false
      add :namespace, :text, null: false, default: "global"
      add :scope, :text, null: false, default: "global"
      add :scope_key, :text, null: false, default: "global"
      add :memory_type, :text, null: false, default: "fact"
      add :status, :text, null: false, default: "proposed"
      add :tags, {:array, :text}, null: false, default: []
      add :source_type, :text, null: false, default: "operator"
      add :source_record_type, :text
      add :source_record_id, :uuid
      add :confidence, :decimal
      add :expires_at, :utc_datetime
      add :last_used_at, :utc_datetime
      add :usage_count, :bigint, null: false, default: 0
      add :metadata, :map, default: %{}
      add :approved_at, :utc_datetime
      add :rejected_at, :utc_datetime
      add :rejection_reason, :text
      add :expired_at, :utc_datetime
      add :archived_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_team_member_id,
          references(:team_members,
            column: :id,
            name: "operations_memory_entries_created_by_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :approved_by_team_member_id,
          references(:team_members,
            column: :id,
            name: "operations_memory_entries_approved_by_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :source_agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "operations_memory_entries_source_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:operations_memory_entries, [:source_type, :status])

    create index(:operations_memory_entries, [:source_record_type, :source_record_id])

    create index(:operations_memory_entries, [:status, :scope, :scope_key])

    create index(:operations_memory_entries, [:status, :namespace])
  end

  def down do
    drop constraint(
           :operations_memory_entries,
           "operations_memory_entries_created_by_team_member_id_fkey"
         )

    drop constraint(
           :operations_memory_entries,
           "operations_memory_entries_approved_by_team_member_id_fkey"
         )

    drop constraint(
           :operations_memory_entries,
           "operations_memory_entries_source_agent_run_id_fkey"
         )

    drop_if_exists index(:operations_memory_entries, [:status, :namespace])

    drop_if_exists index(:operations_memory_entries, [:status, :scope, :scope_key])

    drop_if_exists index(:operations_memory_entries, [:source_record_type, :source_record_id])

    drop_if_exists index(:operations_memory_entries, [:source_type, :status])

    drop table(:operations_memory_entries)
  end
end
