defmodule GnomeGarden.Repo.Migrations.AddBankingAuditResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:banking_counterparty_aliases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :counterparty_name, :text, null: false
      add :normalized_name, :text, null: false
      add :confidence, :decimal
      add :source, :text, null: false, default: "operator"
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "banking_counterparty_aliases_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:banking_counterparty_aliases, [:normalized_name],
             name: "banking_counterparty_uidx"
           )

    create table(:banking_transaction_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :source, :text, null: false
      add :message, :text
      add :metadata, :map, default: %{}
      add :actor_id, :uuid
      add :amount, :money_with_currency
      add :invoice_ids, {:array, :uuid}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_transaction_id,
          references(:banking_transactions,
            column: :id,
            name: "banking_transaction_events_bank_transaction_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create table(:banking_integration_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false, default: "mercury"
      add :provider_event_id, :text
      add :event_type, :text, null: false
      add :source, :text, null: false
      add :status, :text, null: false, default: "received"
      add :payload, :map

      add :received_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :processed_at, :utc_datetime_usec
      add :error_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_connection_id,
          references(:banking_connections,
            column: :id,
            name: "banking_integration_events_bank_connection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :bank_account_id,
          references(:banking_accounts,
            column: :id,
            name: "banking_integration_events_bank_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :bank_transaction_id,
          references(:banking_transactions,
            column: :id,
            name: "banking_integration_events_bank_transaction_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:banking_integration_events, [:provider, :provider_event_id],
             name: "banking_integration_events_unique_provider_event_index"
           )
  end

  def down do
    drop constraint(
           :banking_integration_events,
           "banking_integration_events_bank_connection_id_fkey"
         )

    drop constraint(
           :banking_integration_events,
           "banking_integration_events_bank_account_id_fkey"
         )

    drop constraint(
           :banking_integration_events,
           "banking_integration_events_bank_transaction_id_fkey"
         )

    drop_if_exists unique_index(:banking_integration_events, [:provider, :provider_event_id],
                     name: "banking_integration_events_unique_provider_event_index"
                   )

    drop table(:banking_integration_events)

    drop constraint(
           :banking_transaction_events,
           "banking_transaction_events_bank_transaction_id_fkey"
         )

    drop table(:banking_transaction_events)

    drop constraint(
           :banking_counterparty_aliases,
           "banking_counterparty_aliases_organization_id_fkey"
         )

    drop_if_exists unique_index(:banking_counterparty_aliases, [:normalized_name],
                     name: "banking_counterparty_uidx"
                   )

    drop table(:banking_counterparty_aliases)
  end
end
