defmodule GnomeGarden.Repo.Migrations.RemoveAgentsProspectModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:research_links) do
      remove :prospect_id

      add :target_account_id,
          references(:commercial_target_accounts,
            column: :id,
            name: "research_links_target_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:leads) do
      remove :prospect_id
    end

    drop table(:prospects)
  end

  def down do
    create table(:prospects, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
      add :website, :text
      add :location, :text
      add :region, :text
      add :industry, :text
      add :size, :text
      add :status, :text, default: "researched"
      add :signals, {:array, :text}, default: []
      add :signal_strength, :text, default: "medium"
      add :tech_indicators, {:array, :text}, default: []
      add :contacts, :map, default: "[]"
      add :discovered_via, :text
      add :discovered_at, :utc_datetime_usec
      add :discovery_url, :text
      add :notes, :text
      add :next_action, :text
      add :next_action_date, :date
      add :metadata, :map, default: %{}

      add :converted_organization_id,
          references(:organizations,
            column: :id,
            name: "prospects_converted_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :converted_signal_id,
          references(:commercial_signals,
            column: :id,
            name: "prospects_converted_signal_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      timestamps(type: :utc_datetime_usec)
    end

    create unique_index(:prospects, [:name, :location],
             name: "prospects_unique_name_location_index"
           )

    alter table(:leads) do
      add :prospect_id,
          references(:prospects,
            column: :id,
            name: "leads_prospect_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop constraint(:research_links, "research_links_target_account_id_fkey")

    alter table(:research_links) do
      remove :target_account_id

      add :prospect_id,
          references(:prospects,
            column: :id,
            name: "research_links_prospect_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
