defmodule GnomeGarden.Repo.Migrations.CustomerVendorOnboarding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_vendor_requirement_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :recipient_email, :text
      add :notes, :text
      add :rejection_reason, :text
      add :occurred_at, :utc_datetime, null: false
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_vendor_requirement_id, :uuid, null: false
    end

    create index(:commercial_vendor_requirement_deliveries, [:event_type, :occurred_at],
             name: "vendor_req_deliveries_event_idx"
           )

    create index(
             :commercial_vendor_requirement_deliveries,
             [:customer_vendor_requirement_id, :occurred_at],
             name: "vendor_req_deliveries_requirement_idx"
           )

    create table(:commercial_vendor_requirements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:commercial_vendor_requirement_deliveries) do
      modify :customer_vendor_requirement_id,
             references(:commercial_vendor_requirements,
               column: :id,
               name: "vendor_req_deliveries_requirement_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:commercial_vendor_requirements) do
      add :key, :text, null: false
      add :title, :text, null: false
      add :requirement_type, :text, null: false, default: "other"
      add :status, :text, null: false, default: "missing"
      add :required, :boolean, null: false, default: true
      add :instructions, :text
      add :sort_order, :bigint, null: false, default: 0
      add :sent_to_email, :text
      add :sent_at, :utc_datetime
      add :accepted_at, :utc_datetime
      add :rejected_at, :utc_datetime
      add :rejection_reason, :text
      add :waived_at, :utc_datetime
      add :notes, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_vendor_onboarding_id, :uuid, null: false
      add :company_document_id, :uuid
    end

    create index(:commercial_vendor_requirements, [:status, :updated_at],
             name: "vendor_requirements_status_idx"
           )

    create index(:commercial_vendor_requirements, [:customer_vendor_onboarding_id, :sort_order],
             name: "vendor_requirements_onboarding_sort_idx"
           )

    create unique_index(:commercial_vendor_requirements, [:customer_vendor_onboarding_id, :key],
             name: "customer_vendor_requirements_onboarding_key_idx"
           )

    create table(:commercial_vendor_onboardings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:commercial_vendor_requirements) do
      modify :customer_vendor_onboarding_id,
             references(:commercial_vendor_onboardings,
               column: :id,
               name: "vendor_requirements_onboarding_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :company_document_id,
             references(:commercial_company_documents,
               column: :id,
               name: "vendor_requirements_company_doc_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:commercial_vendor_onboardings) do
      add :key, :text, null: false
      add :customer_name, :text, null: false
      add :status, :text, null: false, default: "active"
      add :return_email, :text
      add :invoice_email, :text
      add :payment_terms, :text
      add :delivery_terms, :text
      add :currency, :text, null: false, default: "USD"
      add :instructions, {:array, :text}, null: false, default: []
      add :terms_url, :text
      add :supplier_code_url, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_profile_id,
          references(:commercial_company_profiles,
            column: :id,
            name: "vendor_onboardings_company_profile_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :customer_organization_id,
          references(:organizations,
            column: :id,
            name: "vendor_onboardings_customer_org_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:commercial_vendor_onboardings, [:status, :updated_at],
             name: "vendor_onboardings_status_idx"
           )

    create unique_index(:commercial_vendor_onboardings, [:company_profile_id, :key],
             name: "customer_vendor_onboardings_profile_key_idx"
           )
  end

  def down do
    drop constraint(:commercial_vendor_onboardings, "vendor_onboardings_company_profile_fkey")

    drop constraint(:commercial_vendor_onboardings, "vendor_onboardings_customer_org_fkey")

    drop_if_exists unique_index(:commercial_vendor_onboardings, [:company_profile_id, :key],
                     name: "customer_vendor_onboardings_profile_key_idx"
                   )

    drop_if_exists index(:commercial_vendor_onboardings, [:status, :updated_at],
                     name: "vendor_onboardings_status_idx"
                   )

    alter table(:commercial_vendor_onboardings) do
      remove :customer_organization_id
      remove :company_profile_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :supplier_code_url
      remove :terms_url
      remove :instructions
      remove :currency
      remove :delivery_terms
      remove :payment_terms
      remove :invoice_email
      remove :return_email
      remove :status
      remove :customer_name
      remove :key
    end

    drop constraint(:commercial_vendor_requirements, "vendor_requirements_onboarding_fkey")

    drop constraint(:commercial_vendor_requirements, "vendor_requirements_company_doc_fkey")

    alter table(:commercial_vendor_requirements) do
      modify :company_document_id, :uuid
      modify :customer_vendor_onboarding_id, :uuid
    end

    drop table(:commercial_vendor_onboardings)

    drop_if_exists unique_index(
                     :commercial_vendor_requirements,
                     [:customer_vendor_onboarding_id, :key],
                     name: "customer_vendor_requirements_onboarding_key_idx"
                   )

    drop_if_exists index(
                     :commercial_vendor_requirements,
                     [:customer_vendor_onboarding_id, :sort_order],
                     name: "vendor_requirements_onboarding_sort_idx"
                   )

    drop_if_exists index(:commercial_vendor_requirements, [:status, :updated_at],
                     name: "vendor_requirements_status_idx"
                   )

    alter table(:commercial_vendor_requirements) do
      remove :company_document_id
      remove :customer_vendor_onboarding_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :notes
      remove :waived_at
      remove :rejection_reason
      remove :rejected_at
      remove :accepted_at
      remove :sent_at
      remove :sent_to_email
      remove :sort_order
      remove :instructions
      remove :required
      remove :status
      remove :requirement_type
      remove :title
      remove :key
    end

    drop constraint(
           :commercial_vendor_requirement_deliveries,
           "vendor_req_deliveries_requirement_fkey"
         )

    alter table(:commercial_vendor_requirement_deliveries) do
      modify :customer_vendor_requirement_id, :uuid
    end

    drop table(:commercial_vendor_requirements)

    drop_if_exists index(
                     :commercial_vendor_requirement_deliveries,
                     [:customer_vendor_requirement_id, :occurred_at],
                     name: "vendor_req_deliveries_requirement_idx"
                   )

    drop_if_exists index(:commercial_vendor_requirement_deliveries, [:event_type, :occurred_at],
                     name: "vendor_req_deliveries_event_idx"
                   )

    drop table(:commercial_vendor_requirement_deliveries)
  end
end
