defmodule GnomeGarden.Repo.Migrations.AddProposals do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:commercial_agreements) do
      add :proposal_id, :uuid
    end

    create table(:commercial_proposal_lines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :line_number, :bigint, null: false, default: 1
      add :line_kind, :text, null: false, default: "other"
      add :description, :text, null: false
      add :quantity, :decimal, null: false
      add :unit_price, :decimal, null: false
      add :line_total, :decimal, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :proposal_id, :uuid, null: false
    end

    create table(:commercial_proposals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:commercial_agreements) do
      modify :proposal_id,
             references(:commercial_proposals,
               column: :id,
               name: "commercial_agreements_proposal_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:commercial_proposal_lines) do
      modify :proposal_id,
             references(:commercial_proposals,
               column: :id,
               name: "commercial_proposal_lines_proposal_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:commercial_proposal_lines, [:proposal_id, :line_number],
             name: "cpl_proposal_line_no_idx"
           )

    alter table(:commercial_proposals) do
      add :proposal_number, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "draft"
      add :revision_number, :bigint, null: false, default: 1
      add :pricing_model, :text, null: false, default: "fixed_fee"
      add :currency_code, :text, null: false, default: "USD"
      add :valid_until_on, :date
      add :issued_on, :date
      add :accepted_on, :date
      add :delivery_model, :text, null: false, default: "project"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :pursuit_id,
          references(:commercial_pursuits,
            column: :id,
            name: "commercial_proposals_pursuit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "commercial_proposals_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :site_id,
          references(:sites,
            column: :id,
            name: "commercial_proposals_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :managed_system_id,
          references(:managed_systems,
            column: :id,
            name: "commercial_proposals_managed_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "commercial_proposals_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:commercial_proposals, [:proposal_number],
             name: "commercial_proposals_unique_proposal_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(:commercial_proposals, [:proposal_number],
                     name: "commercial_proposals_unique_proposal_number_index"
                   )

    drop constraint(:commercial_proposals, "commercial_proposals_pursuit_id_fkey")

    drop constraint(:commercial_proposals, "commercial_proposals_organization_id_fkey")

    drop constraint(:commercial_proposals, "commercial_proposals_site_id_fkey")

    drop constraint(:commercial_proposals, "commercial_proposals_managed_system_id_fkey")

    drop constraint(:commercial_proposals, "commercial_proposals_owner_user_id_fkey")

    alter table(:commercial_proposals) do
      remove :owner_user_id
      remove :managed_system_id
      remove :site_id
      remove :organization_id
      remove :pursuit_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :delivery_model
      remove :accepted_on
      remove :issued_on
      remove :valid_until_on
      remove :currency_code
      remove :pricing_model
      remove :revision_number
      remove :status
      remove :description
      remove :name
      remove :proposal_number
    end

    drop_if_exists unique_index(:commercial_proposal_lines, [:proposal_id, :line_number],
                     name: "cpl_proposal_line_no_idx"
                   )

    drop constraint(:commercial_proposal_lines, "commercial_proposal_lines_proposal_id_fkey")

    alter table(:commercial_proposal_lines) do
      modify :proposal_id, :uuid
    end

    drop constraint(:commercial_agreements, "commercial_agreements_proposal_id_fkey")

    alter table(:commercial_agreements) do
      modify :proposal_id, :uuid
    end

    drop table(:commercial_proposals)

    drop table(:commercial_proposal_lines)

    alter table(:commercial_agreements) do
      remove :proposal_id
    end
  end
end
