defmodule GnomeGarden.Repo.Migrations.CommercialCompanyDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_company_doc_blobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :filename, :text, null: false
      add :content_type, :text
      add :byte_size, :bigint
      add :checksum, :text
      add :service_name, :text, null: false
      add :service_opts, :map, default: %{}
      add :metadata, :map, default: %{}
      add :analyzers, :map, default: %{}
      add :pending_purge, :boolean, null: false, default: false
      add :pending_analyzers, :boolean, null: false, default: false
      add :pending_variants, :boolean, null: false, default: false

      add :variant_of_blob_id,
          references(:commercial_company_doc_blobs,
            column: :id,
            name: "commercial_company_doc_blobs_variant_of_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :variant_name, :text
      add :variant_digest, :text
    end

    create unique_index(:commercial_company_doc_blobs, [:key],
             name: "commercial_company_doc_blobs_unique_storage_key_index"
           )

    create table(:commercial_company_doc_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :blob_id,
          references(:commercial_company_doc_blobs,
            column: :id,
            name: "commercial_company_doc_attachments_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :company_document_id, :uuid
    end

    create table(:commercial_company_documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:commercial_company_doc_attachments) do
      modify :company_document_id,
             references(:commercial_company_documents,
               column: :id,
               name: "commercial_company_doc_attachments_company_document_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:commercial_company_documents) do
      add :key, :text, null: false
      add :title, :text, null: false
      add :kind, :text, null: false, default: "other"
      add :status, :text, null: false, default: "active"
      add :description, :text
      add :signed_on, :date
      add :effective_on, :date
      add :expires_on, :date
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_profile_id,
          references(:commercial_company_profiles,
            column: :id,
            name: "commercial_company_documents_company_profile_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:commercial_company_documents, [:company_profile_id, :key],
             name: "commercial_company_documents_unique_company_document_key_index"
           )
  end

  def down do
    drop constraint(
           :commercial_company_documents,
           "commercial_company_documents_company_profile_id_fkey"
         )

    drop_if_exists unique_index(:commercial_company_documents, [:company_profile_id, :key],
                     name: "commercial_company_documents_unique_company_document_key_index"
                   )

    alter table(:commercial_company_documents) do
      remove :company_profile_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :expires_on
      remove :effective_on
      remove :signed_on
      remove :description
      remove :status
      remove :kind
      remove :title
      remove :key
    end

    drop constraint(
           :commercial_company_doc_attachments,
           "commercial_company_doc_attachments_company_document_id_fkey"
         )

    alter table(:commercial_company_doc_attachments) do
      modify :company_document_id, :uuid
    end

    drop table(:commercial_company_documents)

    drop constraint(
           :commercial_company_doc_attachments,
           "commercial_company_doc_attachments_blob_id_fkey"
         )

    drop table(:commercial_company_doc_attachments)

    drop_if_exists unique_index(:commercial_company_doc_blobs, [:key],
                     name: "commercial_company_doc_blobs_unique_storage_key_index"
                   )

    drop constraint(
           :commercial_company_doc_blobs,
           "commercial_company_doc_blobs_variant_of_blob_id_fkey"
         )

    drop table(:commercial_company_doc_blobs)
  end
end
