defmodule GnomeGarden.Repo.Migrations.RemoveSalesIdentityGraph do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:research_links) do
      remove :company_id

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "research_links_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :person_id,
          references(:people,
            column: :id,
            name: "research_links_person_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:tasks) do
      remove :contact_id
      remove :company_id

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "tasks_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :person_id,
          references(:people,
            column: :id,
            name: "tasks_person_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:sales_events) do
      remove :company_id

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "sales_events_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:leads) do
      remove :company_id
      remove :converted_contact_id
      remove :converted_company_id
      add :converted_organization_id, :uuid
      add :converted_person_id, :uuid

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "leads_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:activities) do
      remove :contact_id
      remove :company_id

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "activities_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :person_id,
          references(:people,
            column: :id,
            name: "activities_person_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop table(:employments)
    drop table(:company_relationships)

    drop constraint(:companies, "companies_primary_contact_id_fkey")
    drop constraint(:contacts, "contacts_address_id_fkey")

    drop table(:addresses)
    drop table(:contacts)
    drop table(:companies)
    drop table(:industries)
  end

  def down do
    raise "Sales identity graph removal is irreversible"
  end
end
