defmodule GnomeGarden.Repo.Migrations.CreateBankingDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:banking_sync_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false, default: "manual"
      add :status, :text, null: false, default: "running"
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
      add :accounts_synced, :bigint, default: 0
      add :transactions_synced, :bigint, default: 0
      add :error_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_connection_id, :uuid, null: false
    end

    create table(:banking_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :provider_account_id, :text, null: false
      add :name, :text
      add :nickname, :text
      add :kind, :text
      add :status, :text, null: false, default: "active"
      add :current_balance, :money_with_currency
      add :available_balance, :money_with_currency
      add :routing_number, :text
      add :account_number_last4, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_connection_id, :uuid, null: false
    end

    create unique_index(:banking_accounts, [:provider, :provider_account_id],
             name: "banking_accounts_unique_provider_account_index"
           )

    create table(:banking_transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :provider_transaction_id, :text, null: false
      add :amount, :money_with_currency, null: false
      add :direction, :text
      add :status, :text
      add :review_status, :text, null: false, default: "unreviewed"
      add :description, :text
      add :counterparty_name, :text
      add :category, :text
      add :occurred_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_account_id,
          references(:banking_accounts,
            column: :id,
            name: "banking_transactions_bank_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:banking_transactions, [:provider, :provider_transaction_id],
             name: "banking_transactions_unique_provider_transaction_index"
           )

    create table(:banking_connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:banking_sync_runs) do
      modify :bank_connection_id,
             references(:banking_connections,
               column: :id,
               name: "banking_sync_runs_bank_connection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:banking_accounts) do
      modify :bank_connection_id,
             references(:banking_connections,
               column: :id,
               name: "banking_accounts_bank_connection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:banking_connections) do
      add :provider, :text, null: false
      add :environment, :text, null: false, default: "sandbox"
      add :name, :text
      add :status, :text, null: false, default: "active"
      add :last_synced_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:banking_connections, [:provider, :environment],
             name: "banking_connections_unique_provider_environment_index"
           )

    create table(:banking_transaction_matches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "proposed"
      add :confidence, :decimal
      add :amount, :money_with_currency
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_transaction_id,
          references(:banking_transactions,
            column: :id,
            name: "banking_transaction_matches_bank_transaction_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :journal_entry_id,
          references(:ledger_journal_entries,
            column: :id,
            name: "banking_transaction_matches_journal_entry_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ), null: false
    end
  end

  def down do
    drop constraint(
           :banking_transaction_matches,
           "banking_transaction_matches_bank_transaction_id_fkey"
         )

    drop constraint(
           :banking_transaction_matches,
           "banking_transaction_matches_journal_entry_id_fkey"
         )

    drop table(:banking_transaction_matches)

    drop_if_exists unique_index(:banking_connections, [:provider, :environment],
                     name: "banking_connections_unique_provider_environment_index"
                   )

    alter table(:banking_connections) do
      remove :updated_at
      remove :inserted_at
      remove :last_synced_at
      remove :status
      remove :name
      remove :environment
      remove :provider
    end

    drop constraint(:banking_accounts, "banking_accounts_bank_connection_id_fkey")

    alter table(:banking_accounts) do
      modify :bank_connection_id, :uuid
    end

    drop constraint(:banking_sync_runs, "banking_sync_runs_bank_connection_id_fkey")

    alter table(:banking_sync_runs) do
      modify :bank_connection_id, :uuid
    end

    drop table(:banking_connections)

    drop constraint(:banking_transactions, "banking_transactions_bank_account_id_fkey")

    drop_if_exists unique_index(:banking_transactions, [:provider, :provider_transaction_id],
                     name: "banking_transactions_unique_provider_transaction_index"
                   )

    drop table(:banking_transactions)

    drop_if_exists unique_index(:banking_accounts, [:provider, :provider_account_id],
                     name: "banking_accounts_unique_provider_account_index"
                   )

    drop table(:banking_accounts)

    drop table(:banking_sync_runs)
  end
end
