defmodule GnomeGarden.Repo.Migrations.AddPreviewRunIdempotency do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:acquisition_lead_preview_runs) do
      add :idempotency_key, :text
    end

    create unique_index(:acquisition_lead_preview_runs, [:idempotency_key],
             name: "acquisition_lead_preview_runs_unique_idempotency_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:acquisition_lead_preview_runs, [:idempotency_key],
                     name: "acquisition_lead_preview_runs_unique_idempotency_key_index"
                   )

    alter table(:acquisition_lead_preview_runs) do
      remove :idempotency_key
    end
  end
end
