defmodule GnomeGarden.Repo.Migrations.DiscoveryQueryPerformance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_lead_preview_queries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :query, :text, null: false
      add :intent, :text, null: false, default: "company"
      add :query_index, :bigint, null: false
      add :status, :text, null: false
      add :result_count, :bigint, null: false, default: 0
      add :cost, :decimal, null: false, default: "0"
      add :reservation_key, :text, null: false
      add :error, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :lead_preview_run_id,
          references(:acquisition_lead_preview_runs,
            column: :id,
            name: "acquisition_lead_preview_queries_lead_preview_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:acquisition_lead_preview_queries, [:query, :inserted_at],
             name: "lead_preview_queries_query_inserted_index"
           )

    create index(:acquisition_lead_preview_queries, [:lead_preview_run_id, :query_index],
             name: "lead_preview_queries_run_index"
           )

    create unique_index(:acquisition_lead_preview_queries, [:lead_preview_run_id, :query_index],
             name: "acquisition_lead_preview_queries_unique_run_query_index_index"
           )
  end

  def down do
    drop constraint(
           :acquisition_lead_preview_queries,
           "acquisition_lead_preview_queries_lead_preview_run_id_fkey"
         )

    drop_if_exists unique_index(
                     :acquisition_lead_preview_queries,
                     [:lead_preview_run_id, :query_index],
                     name: "acquisition_lead_preview_queries_unique_run_query_index_index"
                   )

    drop_if_exists index(:acquisition_lead_preview_queries, [:lead_preview_run_id, :query_index],
                     name: "lead_preview_queries_run_index"
                   )

    drop_if_exists index(:acquisition_lead_preview_queries, [:query, :inserted_at],
                     name: "lead_preview_queries_query_inserted_index"
                   )

    drop table(:acquisition_lead_preview_queries)
  end
end
