defmodule GnomeGarden.Repo.Migrations.AddBankRulesAndMatchIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:banking_rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :priority, :bigint, null: false, default: 100
      add :match_field, :text, null: false
      add :match_type, :text, null: false, default: "contains"
      add :match_value, :text, null: false
      add :set_category, :text, null: false
      add :enabled?, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:banking_transaction_matches, [:bank_transaction_id, :journal_entry_id],
             name: "banking_transaction_matches_unique_transaction_entry_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :banking_transaction_matches,
                     [:bank_transaction_id, :journal_entry_id],
                     name: "banking_transaction_matches_unique_transaction_entry_index"
                   )

    drop table(:banking_rules)
  end
end
