defmodule GnomeGarden.Repo.Migrations.AddSalesEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sales_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :subject_type, :text, null: false
      add :subject_id, :uuid, null: false
      add :summary, :text, null: false
      add :reason, :text
      add :from_state, :text
      add :to_state, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "sales_events_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :opportunity_id,
          references(:opportunities,
            column: :id,
            name: "sales_events_opportunity_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :company_id,
          references(:companies,
            column: :id,
            name: "sales_events_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:sales_events, "sales_events_actor_id_fkey")

    drop constraint(:sales_events, "sales_events_opportunity_id_fkey")

    drop constraint(:sales_events, "sales_events_company_id_fkey")

    drop table(:sales_events)
  end
end
