defmodule GnomeGarden.Repo.Migrations.AddBankTransactionReconciliationNote do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:banking_transactions) do
      add :reconciliation_note, :text
    end
  end

  def down do
    alter table(:banking_transactions) do
      remove :reconciliation_note
    end
  end
end
