defmodule GnomeGarden.Repo.Migrations.FixBillingReliabilityOnDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:organizations, "organizations_billing_contact_id_fkey")

    alter table(:organizations) do
      modify :billing_contact_id,
             references(:people,
               column: :id,
               name: "organizations_billing_contact_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop constraint(:payment_schedule_items, "payment_schedule_items_agreement_id_fkey")

    alter table(:payment_schedule_items) do
      modify :agreement_id,
             references(:commercial_agreements,
               column: :id,
               name: "payment_schedule_items_agreement_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:payment_schedule_items, "payment_schedule_items_agreement_id_fkey")

    alter table(:payment_schedule_items) do
      modify :agreement_id,
             references(:commercial_agreements,
               column: :id,
               name: "payment_schedule_items_agreement_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:organizations, "organizations_billing_contact_id_fkey")

    alter table(:organizations) do
      modify :billing_contact_id,
             references(:people,
               column: :id,
               name: "organizations_billing_contact_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
