defmodule GnomeGarden.Repo.Migrations.AddCreditNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:credit_note_lines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false
      add :description, :text, null: false
      add :quantity, :decimal
      add :unit_price, :decimal
      add :line_total, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :credit_note_id, :uuid, null: false
    end

    create table(:credit_notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:credit_note_lines) do
      modify :credit_note_id,
             references(:credit_notes,
               column: :id,
               name: "credit_note_lines_credit_note_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:credit_notes) do
      add :credit_note_number, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :total_amount, :decimal, null: false
      add :currency_code, :text, null: false, default: "USD"
      add :issued_on, :date
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :invoice_id,
          references(:finance_invoices,
            column: :id,
            name: "credit_notes_invoice_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ), null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "credit_notes_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ), null: false
    end

    create unique_index(:credit_notes, [:invoice_id],
             name: "credit_notes_one_credit_note_per_invoice_index"
           )

    create unique_index(:credit_notes, [:credit_note_number],
             name: "credit_notes_unique_credit_note_number_index"
           )

    create table(:finance_sequences, primary_key: false) do
      add :name, :text, null: false, primary_key: true
      add :last_value, :bigint, null: false, default: 0
    end

    execute(
      "INSERT INTO finance_sequences (name, last_value) VALUES ('credit_notes', 0) ON CONFLICT (name) DO NOTHING",
      "DELETE FROM finance_sequences WHERE name = 'credit_notes'"
    )
  end

  def down do
    drop table(:finance_sequences)

    drop_if_exists unique_index(:credit_notes, [:credit_note_number],
                     name: "credit_notes_unique_credit_note_number_index"
                   )

    drop_if_exists unique_index(:credit_notes, [:invoice_id],
                     name: "credit_notes_one_credit_note_per_invoice_index"
                   )

    drop constraint(:credit_notes, "credit_notes_invoice_id_fkey")

    drop constraint(:credit_notes, "credit_notes_organization_id_fkey")

    alter table(:credit_notes) do
      remove :organization_id
      remove :invoice_id
      remove :updated_at
      remove :inserted_at
      remove :reason
      remove :issued_on
      remove :currency_code
      remove :total_amount
      remove :status
      remove :credit_note_number
    end

    drop constraint(:credit_note_lines, "credit_note_lines_credit_note_id_fkey")

    alter table(:credit_note_lines) do
      modify :credit_note_id, :uuid
    end

    drop table(:credit_notes)

    drop table(:credit_note_lines)
  end
end
