defmodule GnomeGarden.Repo.Migrations.AddAcquisitionDocumentsAndStorage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_document_blobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :filename, :text, null: false
      add :content_type, :text
      add :byte_size, :bigint
      add :checksum, :text
      add :service_name, :text, null: false
      add :service_opts, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}
      add :analyzers, :map, null: false, default: %{}
      add :pending_purge, :boolean, null: false, default: false
      add :pending_analyzers, :boolean, null: false, default: false
      add :pending_variants, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:acquisition_document_blobs, [:key],
             name: "acquisition_document_blobs_unique_storage_key_index"
           )

    create table(:acquisition_document_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :blob_id,
          references(:acquisition_document_blobs,
            column: :id,
            name: "acquisition_document_attachments_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :document_id, :uuid
    end

    create table(:acquisition_finding_documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :document_role, :text, null: false, default: "supporting"
      add :notes, :text
      add :linked_at, :utc_datetime
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :finding_id,
          references(:acquisition_findings,
            column: :id,
            name: "acquisition_finding_documents_finding_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :document_id, :uuid, null: false
    end

    create index(:acquisition_finding_documents, [:document_role, :linked_at])

    create index(:acquisition_finding_documents, [:finding_id, :linked_at])

    create table(:acquisition_documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:acquisition_document_attachments) do
      modify :document_id,
             references(:acquisition_documents,
               column: :id,
               name: "acquisition_document_attachments_document_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:acquisition_finding_documents) do
      modify :document_id,
             references(:acquisition_documents,
               column: :id,
               name: "acquisition_finding_documents_document_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:acquisition_finding_documents, [:finding_id, :document_id],
             name: "acquisition_finding_documents_unique_finding_document_index"
           )

    alter table(:acquisition_documents) do
      add :title, :text, null: false
      add :summary, :text
      add :document_type, :text, null: false, default: "other"
      add :source_url, :text
      add :uploaded_at, :utc_datetime
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:acquisition_documents) do
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :uploaded_at
      remove :source_url
      remove :document_type
      remove :summary
      remove :title
    end

    drop_if_exists unique_index(:acquisition_finding_documents, [:finding_id, :document_id],
                     name: "acquisition_finding_documents_unique_finding_document_index"
                   )

    drop constraint(
           :acquisition_finding_documents,
           "acquisition_finding_documents_document_id_fkey"
         )

    alter table(:acquisition_finding_documents) do
      modify :document_id, :uuid
    end

    drop constraint(
           :acquisition_document_attachments,
           "acquisition_document_attachments_document_id_fkey"
         )

    alter table(:acquisition_document_attachments) do
      modify :document_id, :uuid
    end

    drop table(:acquisition_documents)

    drop constraint(
           :acquisition_finding_documents,
           "acquisition_finding_documents_finding_id_fkey"
         )

    drop_if_exists index(:acquisition_finding_documents, [:finding_id, :linked_at])

    drop_if_exists index(:acquisition_finding_documents, [:document_role, :linked_at])

    drop table(:acquisition_finding_documents)

    drop constraint(
           :acquisition_document_attachments,
           "acquisition_document_attachments_blob_id_fkey"
         )

    drop table(:acquisition_document_attachments)

    drop_if_exists unique_index(:acquisition_document_blobs, [:key],
                     name: "acquisition_document_blobs_unique_storage_key_index"
                   )

    drop table(:acquisition_document_blobs)
  end
end
