defmodule GnomeGarden.Repo.Migrations.AddMercuryTransactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mercury_transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :mercury_id, :text, null: false
      add :amount, :decimal, null: false
      add :kind, :text, null: false
      add :status, :text, null: false
      add :bank_description, :text
      add :external_memo, :text
      add :counterparty_id, :text
      add :counterparty_name, :text
      add :counterparty_nickname, :text
      add :note, :text
      add :details, :map
      add :currency_exchange_info, :map
      add :reason_for_failure, :text
      add :dashboard_link, :text
      add :fee_id, :text
      add :estimated_delivery_date, :date
      add :posted_date, :date
      add :failed_at, :utc_datetime_usec
      add :occurred_at, :utc_datetime_usec, null: false
      add :company_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :account_id,
          references(:mercury_accounts,
            column: :id,
            name: "mercury_transactions_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:mercury_transactions, [:mercury_id],
             name: "mercury_transactions_unique_mercury_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:mercury_transactions, [:mercury_id],
                     name: "mercury_transactions_unique_mercury_id_index"
                   )

    drop constraint(:mercury_transactions, "mercury_transactions_account_id_fkey")

    drop table(:mercury_transactions)
  end
end
