defmodule GnomeGarden.Repo.Migrations.AlignProcurementSourcesAndProspectsWithOperations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lead_sources) do
      remove :company_id

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "lead_sources_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:prospects) do
      remove :converted_lead_id
      remove :converted_company_id

      add :converted_organization_id,
          references(:organizations,
            column: :id,
            name: "prospects_converted_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :converted_signal_id,
          references(:commercial_signals,
            column: :id,
            name: "prospects_converted_signal_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:prospects, "prospects_converted_organization_id_fkey")

    drop constraint(:prospects, "prospects_converted_signal_id_fkey")

    alter table(:prospects) do
      remove :converted_signal_id
      remove :converted_organization_id

      add :converted_company_id,
          references(:companies,
            column: :id,
            name: "prospects_converted_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :converted_lead_id,
          references(:leads,
            column: :id,
            name: "prospects_converted_lead_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop constraint(:lead_sources, "lead_sources_organization_id_fkey")

    alter table(:lead_sources) do
      remove :organization_id

      add :company_id,
          references(:companies,
            column: :id,
            name: "lead_sources_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
