defmodule GnomeGarden.Repo.Migrations.AddBitwardenSourceCredentialReferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:procurement_source_credentials) do
      add :credential_storage, :text, null: false, default: "local_encrypted"
      add :bitwarden_server_url, :text
      add :bitwarden_organization, :text
      add :bitwarden_collection, :text
      add :bitwarden_item_id, :text
      add :bitwarden_item_name, :text
      add :bitwarden_notes, :text
    end
  end

  def down do
    alter table(:procurement_source_credentials) do
      remove :bitwarden_notes
      remove :bitwarden_item_name
      remove :bitwarden_item_id
      remove :bitwarden_collection
      remove :bitwarden_organization
      remove :bitwarden_server_url
      remove :credential_storage
    end
  end
end
