defmodule GnomeGarden.Repo.Migrations.EnrichBankRuleSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:banking_rules) do
      remove :enabled?
      remove :set_category
      remove :match_value
      remove :match_type
      remove :match_field
      modify :priority, :bigint, default: 0
      add :enabled, :boolean, null: false, default: true
      add :direction, :text, null: false, default: "both"
      add :description_contains, :text
      add :counterparty_contains, :text
      add :amount_operator, :text
      add :amount_value, :decimal
      add :category, :text, null: false, default: "unknown"
      add :review_status_result, :text, null: false, default: "reviewed"
      add :match_behavior, :text, null: false, default: "none"
      add :auto_note, :text
    end
  end

  def down do
    alter table(:banking_rules) do
      remove :auto_note
      remove :match_behavior
      remove :review_status_result
      remove :category
      remove :amount_value
      remove :amount_operator
      remove :counterparty_contains
      remove :description_contains
      remove :direction
      remove :enabled
      modify :priority, :bigint, default: 100
      add :match_field, :text, null: false
      add :match_type, :text, null: false, default: "contains"
      add :match_value, :text, null: false
      add :set_category, :text, null: false
      add :enabled?, :boolean, null: false, default: true
    end
  end
end
