defmodule GnomeGarden.Repo.Migrations.AddCrmRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:leads) do
      add :company_id,
          references(:companies,
            column: :id,
            name: "leads_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:bids) do
      add :bid_type, :text
    end

    alter table(:activities) do
      add :bid_id,
          references(:bids,
            column: :id,
            name: "activities_bid_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :lead_id,
          references(:leads,
            column: :id,
            name: "activities_lead_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :opportunity_id,
          references(:opportunities,
            column: :id,
            name: "activities_opportunity_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:activities, "activities_bid_id_fkey")

    drop constraint(:activities, "activities_lead_id_fkey")

    drop constraint(:activities, "activities_opportunity_id_fkey")

    alter table(:activities) do
      remove :opportunity_id
      remove :lead_id
      remove :bid_id
    end

    alter table(:bids) do
      remove :bid_type
    end

    drop constraint(:leads, "leads_company_id_fkey")

    alter table(:leads) do
      remove :company_id
    end
  end
end
