defmodule GnomeGarden.Repo.Migrations.CustomerVendorRequirementArtifacts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_vendor_requirement_artifact_blobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :filename, :text, null: false
      add :content_type, :text
      add :byte_size, :bigint
      add :checksum, :text
      add :service_name, :text, null: false
      add :service_opts, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}
      add :analyzers, :map, null: false, default: %{}
      add :pending_purge, :boolean, null: false, default: false
      add :pending_analyzers, :boolean, null: false, default: false
      add :pending_variants, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :variant_of_blob_id,
          references(:commercial_vendor_requirement_artifact_blobs,
            column: :id,
            name: "commercial_vendor_requirement_artifact_blobs_variant_of_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :variant_name, :text
      add :variant_digest, :text
    end

    create unique_index(:commercial_vendor_requirement_artifact_blobs, [:key],
             name: "vendor_req_artifact_blobs_key_idx"
           )

    create table(:commercial_vendor_requirement_artifacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :kind, :text, null: false, default: "source_form"
      add :status, :text, null: false, default: "uploaded"
      add :notes, :text
      add :uploaded_at, :utc_datetime
      add :approved_at, :utc_datetime
      add :sent_at, :utc_datetime
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_vendor_requirement_id,
          references(:commercial_vendor_requirements,
            column: :id,
            name: "vendor_requirement_artifacts_requirement_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:commercial_vendor_requirement_artifacts, [:status, :updated_at],
             name: "vendor_requirement_artifacts_status_idx"
           )

    create index(
             :commercial_vendor_requirement_artifacts,
             [:customer_vendor_requirement_id, :kind],
             name: "vendor_requirement_artifacts_requirement_kind_idx"
           )

    create table(:commercial_vendor_requirement_artifact_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :blob_id,
          references(:commercial_vendor_requirement_artifact_blobs,
            column: :id,
            name: "commercial_vendor_requirement_artifact_attachments_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :customer_vendor_requirement_artifact_id,
          references(:commercial_vendor_requirement_artifacts,
            column: :id,
            name:
              "commercial_vendor_requirement_artifact_attachments_customer_vendor_requirement_artifact_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(
           :commercial_vendor_requirement_artifact_attachments,
           "commercial_vendor_requirement_artifact_attachments_blob_id_fkey"
         )

    drop constraint(
           :commercial_vendor_requirement_artifact_attachments,
           "commercial_vendor_requirement_artifact_attachments_customer_vendor_requirement_artifact_id_fkey"
         )

    drop table(:commercial_vendor_requirement_artifact_attachments)

    drop constraint(
           :commercial_vendor_requirement_artifacts,
           "vendor_requirement_artifacts_requirement_fkey"
         )

    drop_if_exists index(
                     :commercial_vendor_requirement_artifacts,
                     [:customer_vendor_requirement_id, :kind],
                     name: "vendor_requirement_artifacts_requirement_kind_idx"
                   )

    drop_if_exists index(:commercial_vendor_requirement_artifacts, [:status, :updated_at],
                     name: "vendor_requirement_artifacts_status_idx"
                   )

    drop table(:commercial_vendor_requirement_artifacts)

    drop_if_exists unique_index(:commercial_vendor_requirement_artifact_blobs, [:key],
                     name: "vendor_req_artifact_blobs_key_idx"
                   )

    drop constraint(
           :commercial_vendor_requirement_artifact_blobs,
           "commercial_vendor_requirement_artifact_blobs_variant_of_blob_id_fkey"
         )

    drop table(:commercial_vendor_requirement_artifact_blobs)
  end
end
