defmodule GnomeGarden.Repo.Migrations.AutomationEngine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:automation_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "running"
      add :rule_snapshot, :map, null: false
      add :action_results, {:array, :map}, null: false, default: []
      add :error, :text
      add :finished_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :rule_id, :uuid, null: false
      add :event_id, :uuid, null: false
    end

    create unique_index(:automation_runs, [:rule_id, :event_id],
             name: "automation_runs_one_run_per_rule_and_event_index"
           )

    create table(:automation_rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:automation_runs) do
      modify :rule_id,
             references(:automation_rules,
               column: :id,
               name: "automation_runs_rule_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:automation_rules) do
      add :name, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "draft"
      add :trigger_resource, :text, null: false
      add :trigger_action, :text, null: false
      add :criteria, {:array, :map}, null: false, default: []
      add :actions, {:array, :map}, null: false, default: []
      add :published_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:automation_rules, [:name], name: "automation_rules_unique_name_index")

    create table(:automation_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:automation_runs) do
      modify :event_id,
             references(:automation_events,
               column: :id,
               name: "automation_runs_event_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:automation_events) do
      add :resource, :text, null: false
      add :action, :text, null: false
      add :record_id, :uuid, null: false
      add :data, :map, null: false, default: %{}
      add :depth, :bigint, null: false, default: 0
      add :occurred_at, :utc_datetime_usec
      add :processed_at, :utc_datetime_usec
      add :error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:automation_events, [:resource, :action])

    create index(:automation_events, [:processed_at])
  end

  def down do
    drop_if_exists index(:automation_events, [:processed_at])

    drop_if_exists index(:automation_events, [:resource, :action])

    alter table(:automation_events) do
      remove :updated_at
      remove :inserted_at
      remove :error
      remove :processed_at
      remove :occurred_at
      remove :depth
      remove :data
      remove :record_id
      remove :action
      remove :resource
    end

    drop constraint(:automation_runs, "automation_runs_event_id_fkey")

    alter table(:automation_runs) do
      modify :event_id, :uuid
    end

    drop table(:automation_events)

    drop_if_exists unique_index(:automation_rules, [:name],
                     name: "automation_rules_unique_name_index"
                   )

    alter table(:automation_rules) do
      remove :updated_at
      remove :inserted_at
      remove :published_at
      remove :actions
      remove :criteria
      remove :trigger_action
      remove :trigger_resource
      remove :status
      remove :description
      remove :name
    end

    drop constraint(:automation_runs, "automation_runs_rule_id_fkey")

    alter table(:automation_runs) do
      modify :rule_id, :uuid
    end

    drop table(:automation_rules)

    drop_if_exists unique_index(:automation_runs, [:rule_id, :event_id],
                     name: "automation_runs_one_run_per_rule_and_event_index"
                   )

    drop table(:automation_runs)
  end
end
