defmodule GnomeGarden.Repo.Migrations.UpdateRetainerApplications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(
           :finance_retainer_applications,
           "finance_retainer_applications_retainer_id_fkey"
         )

    alter table(:finance_retainer_applications) do
      add :applied_on, :date

      add :invoice_id,
          references(:finance_invoices,
            column: :id,
            name: "finance_retainer_applications_invoice_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      modify :retainer_id,
             references(:finance_retainers,
               column: :id,
               name: "finance_retainer_applications_retainer_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:finance_retainer_applications, [:retainer_id, :invoice_id],
             name: "fin_retainer_app_unique_pair_idx"
           )
  end

  def down do
    drop_if_exists unique_index(:finance_retainer_applications, [:retainer_id, :invoice_id],
                     name: "fin_retainer_app_unique_pair_idx"
                   )

    drop constraint(
           :finance_retainer_applications,
           "finance_retainer_applications_invoice_id_fkey"
         )

    drop constraint(
           :finance_retainer_applications,
           "finance_retainer_applications_retainer_id_fkey"
         )

    alter table(:finance_retainer_applications) do
      modify :retainer_id,
             references(:finance_retainers,
               column: :id,
               name: "finance_retainer_applications_retainer_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      remove :invoice_id
      remove :applied_on
    end
  end
end
