defmodule GnomeGarden.Repo.Migrations.AddGlResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "CREATE SEQUENCE finance_journal_entry_number_seq START 1"

    create table(:finance_chart_of_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :number, :bigint, null: false
      add :name, :text, null: false
      add :type, :text, null: false
      add :normal_balance, :text, null: false
      add :is_system, :boolean, null: false, default: false
      add :active, :boolean, null: false, default: true
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:finance_chart_of_accounts, [:number],
             name: "finance_chart_of_accounts_unique_number_index"
           )

    create table(:finance_journal_entry_lines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :debit, :decimal
      add :credit, :decimal
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :journal_entry_id, :uuid, null: false
      add :account_id, :uuid, null: false
    end

    create table(:finance_journal_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:finance_journal_entry_lines) do
      modify :journal_entry_id,
             references(:finance_journal_entries,
               column: :id,
               name: "finance_journal_entry_lines_journal_entry_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :account_id,
             references(:finance_chart_of_accounts,
               column: :id,
               name: "finance_journal_entry_lines_account_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:finance_journal_entries) do
      add :entry_number, :text, null: false
      add :date, :date, null: false
      add :description, :text, null: false
      add :entry_type, :text, null: false, default: "manual"
      add :status, :text, null: false, default: "draft"
      add :reference_id, :uuid
      add :reference_type, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    execute "DROP SEQUENCE IF EXISTS finance_journal_entry_number_seq"

    alter table(:finance_journal_entries) do
      remove :updated_at
      remove :inserted_at
      remove :reference_type
      remove :reference_id
      remove :status
      remove :entry_type
      remove :description
      remove :date
      remove :entry_number
    end

    drop constraint(
           :finance_journal_entry_lines,
           "finance_journal_entry_lines_journal_entry_id_fkey"
         )

    drop constraint(:finance_journal_entry_lines, "finance_journal_entry_lines_account_id_fkey")

    alter table(:finance_journal_entry_lines) do
      modify :account_id, :uuid
      modify :journal_entry_id, :uuid
    end

    drop table(:finance_journal_entries)

    drop table(:finance_journal_entry_lines)

    drop_if_exists unique_index(:finance_chart_of_accounts, [:number],
                     name: "finance_chart_of_accounts_unique_number_index"
                   )

    drop table(:finance_chart_of_accounts)
  end
end
