defmodule GnomeGarden.Repo.Migrations.AddAgentRunScheduleSlot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_runs) do
      add :schedule_slot, :text
    end
  end

  def down do
    alter table(:agent_runs) do
      remove :schedule_slot
    end
  end
end
