defmodule GnomeGarden.Repo.Migrations.AddProviderBudgetPolicy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:acquisition_provider_reservations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idempotency_key, :text, null: false
      add :status, :text, null: false, default: "reserved"
      add :estimated_cost, :decimal, null: false
      add :actual_cost, :decimal, null: false, default: "0"
      add :estimated_requests, :bigint, null: false
      add :actual_requests, :bigint, null: false, default: 0
      add :failure_reason, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :provider_budget_id, :uuid, null: false
    end

    create index(:acquisition_provider_reservations, [:provider_budget_id, :status],
             name: "provider_reservations_budget_status_index"
           )

    create unique_index(:acquisition_provider_reservations, [:idempotency_key],
             name: "acquisition_provider_reservations_unique_idempotency_key_index"
           )

    create table(:acquisition_provider_budgets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:acquisition_provider_reservations) do
      modify :provider_budget_id,
             references(:acquisition_provider_budgets,
               column: :id,
               name: "acquisition_provider_reservations_provider_budget_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:acquisition_provider_budgets) do
      add :provider, :text, null: false
      add :operation, :text, null: false
      add :window_key, :text, null: false
      add :window_started_at, :utc_datetime, null: false
      add :resets_at, :utc_datetime, null: false
      add :spend_limit, :decimal, null: false
      add :request_limit, :bigint, null: false
      add :reserved_cost, :decimal, null: false, default: "0"
      add :spent_cost, :decimal, null: false, default: "0"
      add :reserved_requests, :bigint, null: false, default: 0
      add :used_requests, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:acquisition_provider_budgets, [:provider, :operation, :resets_at])

    create unique_index(:acquisition_provider_budgets, [:provider, :operation, :window_key],
             name: "provider_budgets_window_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :acquisition_provider_budgets,
                     [:provider, :operation, :window_key],
                     name: "provider_budgets_window_index"
                   )

    drop_if_exists index(:acquisition_provider_budgets, [:provider, :operation, :resets_at])

    alter table(:acquisition_provider_budgets) do
      remove :updated_at
      remove :inserted_at
      remove :used_requests
      remove :reserved_requests
      remove :spent_cost
      remove :reserved_cost
      remove :request_limit
      remove :spend_limit
      remove :resets_at
      remove :window_started_at
      remove :window_key
      remove :operation
      remove :provider
    end

    drop constraint(
           :acquisition_provider_reservations,
           "acquisition_provider_reservations_provider_budget_id_fkey"
         )

    alter table(:acquisition_provider_reservations) do
      modify :provider_budget_id, :uuid
    end

    drop table(:acquisition_provider_budgets)

    drop_if_exists unique_index(:acquisition_provider_reservations, [:idempotency_key],
                     name: "acquisition_provider_reservations_unique_idempotency_key_index"
                   )

    drop_if_exists index(:acquisition_provider_reservations, [:provider_budget_id, :status],
                     name: "provider_reservations_budget_status_index"
                   )

    drop table(:acquisition_provider_reservations)
  end
end
