defmodule GnomeGarden.Repo.Migrations.GrowthReviewFixes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:company_qualifications, "company_qualifications_company_profile_id_fkey")

    drop_if_exists unique_index(
                     :company_qualifications,
                     [:company_profile_id, :kind, :issuing_authority, :name],
                     name: "company_qualifications_unique_capability_index"
                   )

    create unique_index(
             :company_qualifications,
             [:company_profile_id, :kind, :issuing_authority, :identifier],
             name: "company_qualifications_unique_capability_index"
           )

    alter table(:company_qualifications) do
      modify :company_profile_id,
             references(:commercial_company_profiles,
               column: :id,
               name: "company_qualifications_company_profile_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    drop constraint(
           :company_growth_initiatives,
           "company_growth_initiatives_company_profile_id_fkey"
         )

    alter table(:company_growth_initiatives) do
      modify :company_profile_id,
             references(:commercial_company_profiles,
               column: :id,
               name: "company_growth_initiatives_company_profile_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:playbook_runs) do
      add :company_qualification_id,
          references(:company_qualifications,
            column: :id,
            name: "playbook_runs_company_qualification_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:playbook_runs, "playbook_runs_company_qualification_id_fkey")

    alter table(:playbook_runs) do
      remove :company_qualification_id
    end

    drop constraint(
           :company_growth_initiatives,
           "company_growth_initiatives_company_profile_id_fkey"
         )

    alter table(:company_growth_initiatives) do
      modify :company_profile_id,
             references(:commercial_company_profiles,
               column: :id,
               name: "company_growth_initiatives_company_profile_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:company_qualifications, "company_qualifications_company_profile_id_fkey")

    alter table(:company_qualifications) do
      modify :company_profile_id,
             references(:commercial_company_profiles,
               column: :id,
               name: "company_qualifications_company_profile_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop_if_exists unique_index(
                     :company_qualifications,
                     [:company_profile_id, :kind, :issuing_authority, :identifier],
                     name: "company_qualifications_unique_capability_index"
                   )

    create unique_index(
             :company_qualifications,
             [:company_profile_id, :kind, :issuing_authority, :name],
             name: "company_qualifications_unique_capability_index"
           )
  end
end
