defmodule GnomeGarden.Repo.Migrations.AddSessionTimeoutToBillingSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:billing_settings) do
      add :session_timeout_minutes, :bigint, null: false, default: 30
    end
  end

  def down do
    alter table(:billing_settings) do
      remove :session_timeout_minutes
    end
  end
end
