defmodule GnomeGarden.Repo.Migrations.DeduplicateLeadPreviewCandidates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:acquisition_lead_preview_candidates, [:lead_preview_run_id, :url],
             name: "acquisition_lead_preview_candidates_unique_run_url_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :acquisition_lead_preview_candidates,
                     [:lead_preview_run_id, :url],
                     name: "acquisition_lead_preview_candidates_unique_run_url_index"
                   )
  end
end
