defmodule GnomeGarden.Repo.Migrations.AddCommercialSpine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_signals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :signal_type, :text, null: false, default: "other"
      add :source_channel, :text, null: false, default: "manual"
      add :status, :text, null: false, default: "new"
      add :external_ref, :text
      add :source_url, :text
      add :observed_at, :utc_datetime
      add :notes, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "commercial_signals_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :site_id,
          references(:sites,
            column: :id,
            name: "commercial_signals_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :managed_system_id,
          references(:managed_systems,
            column: :id,
            name: "commercial_signals_managed_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "commercial_signals_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:commercial_pursuits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :pursuit_type, :text, null: false, default: "other"
      add :stage, :text, null: false, default: "new"
      add :priority, :text, null: false, default: "normal"
      add :probability, :bigint, null: false, default: 10
      add :target_value, :decimal
      add :expected_close_on, :date
      add :delivery_model, :text, null: false, default: "project"
      add :billing_model, :text, null: false, default: "fixed_fee"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :signal_id,
          references(:commercial_signals,
            column: :id,
            name: "commercial_pursuits_signal_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "commercial_pursuits_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :site_id,
          references(:sites,
            column: :id,
            name: "commercial_pursuits_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :managed_system_id,
          references(:managed_systems,
            column: :id,
            name: "commercial_pursuits_managed_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "commercial_pursuits_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:commercial_agreements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reference_number, :text
      add :name, :text, null: false
      add :agreement_type, :text, null: false, default: "project"
      add :status, :text, null: false, default: "draft"
      add :billing_model, :text, null: false, default: "fixed_fee"
      add :currency_code, :text, null: false, default: "USD"
      add :contract_value, :decimal
      add :start_on, :date
      add :end_on, :date
      add :auto_renew, :boolean, null: false, default: false
      add :renewal_notice_days, :bigint, null: false, default: 30
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :pursuit_id,
          references(:commercial_pursuits,
            column: :id,
            name: "commercial_agreements_pursuit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "commercial_agreements_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :site_id,
          references(:sites,
            column: :id,
            name: "commercial_agreements_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :managed_system_id,
          references(:managed_systems,
            column: :id,
            name: "commercial_agreements_managed_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "commercial_agreements_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:commercial_agreements, "commercial_agreements_pursuit_id_fkey")

    drop constraint(:commercial_agreements, "commercial_agreements_organization_id_fkey")

    drop constraint(:commercial_agreements, "commercial_agreements_site_id_fkey")

    drop constraint(:commercial_agreements, "commercial_agreements_managed_system_id_fkey")

    drop constraint(:commercial_agreements, "commercial_agreements_owner_user_id_fkey")

    drop table(:commercial_agreements)

    drop constraint(:commercial_pursuits, "commercial_pursuits_signal_id_fkey")

    drop constraint(:commercial_pursuits, "commercial_pursuits_organization_id_fkey")

    drop constraint(:commercial_pursuits, "commercial_pursuits_site_id_fkey")

    drop constraint(:commercial_pursuits, "commercial_pursuits_managed_system_id_fkey")

    drop constraint(:commercial_pursuits, "commercial_pursuits_owner_user_id_fkey")

    drop table(:commercial_pursuits)

    drop constraint(:commercial_signals, "commercial_signals_organization_id_fkey")

    drop constraint(:commercial_signals, "commercial_signals_site_id_fkey")

    drop constraint(:commercial_signals, "commercial_signals_managed_system_id_fkey")

    drop constraint(:commercial_signals, "commercial_signals_owner_user_id_fkey")

    drop table(:commercial_signals)
  end
end
