defmodule GnomeGarden.Repo.Migrations.AddSourceRetrievalRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:procurement_source_retrieval_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "running"
      add :requested_paths, {:array, :text}, null: false, default: []
      add :retrieval_path, :text
      add :fallback_reason, :text
      add :blocked, :boolean, null: false, default: false
      add :duration_ms, :bigint
      add :attempts, {:array, :map}, null: false, default: []
      add :diagnostics, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :procurement_source_id,
          references(:procurement_sources,
            column: :id,
            name: "procurement_source_retrieval_runs_procurement_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:procurement_source_retrieval_runs, [:status, :retrieval_path])

    create index(:procurement_source_retrieval_runs, [:procurement_source_id, :started_at])
  end

  def down do
    drop constraint(
           :procurement_source_retrieval_runs,
           "procurement_source_retrieval_runs_procurement_source_id_fkey"
         )

    drop_if_exists index(:procurement_source_retrieval_runs, [:procurement_source_id, :started_at])

    drop_if_exists index(:procurement_source_retrieval_runs, [:status, :retrieval_path])

    drop table(:procurement_source_retrieval_runs)
  end
end
