defmodule GnomeGarden.Repo.Migrations.AddMercuryBankRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mercury_bank_rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :priority, :bigint, null: false, default: 0
      add :direction, :text, null: false
      add :counterparty_contains, :text
      add :amount_operator, :text
      add :amount_value, :decimal
      add :reconciliation_category, :text, null: false
      add :auto_note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:mercury_bank_rules)
  end
end
