defmodule GnomeGarden.Repo.Migrations.AddServiceTickets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:execution_work_orders) do
      add :service_ticket_id, :uuid
    end

    create table(:execution_service_tickets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:execution_work_orders) do
      modify :service_ticket_id,
             references(:execution_service_tickets,
               column: :id,
               name: "execution_work_orders_service_ticket_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:execution_service_tickets) do
      add :ticket_number, :text
      add :title, :text, null: false
      add :description, :text
      add :ticket_type, :text, null: false, default: "incident"
      add :source_channel, :text, null: false, default: "manual"
      add :status, :text, null: false, default: "new"
      add :severity, :text, null: false, default: "normal"
      add :impact, :text, null: false, default: "single_area"
      add :reported_at, :utc_datetime
      add :due_on, :date
      add :resolved_at, :utc_datetime
      add :closed_at, :utc_datetime
      add :resolution_summary, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "execution_service_tickets_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :site_id,
          references(:sites,
            column: :id,
            name: "execution_service_tickets_site_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :managed_system_id,
          references(:managed_systems,
            column: :id,
            name: "execution_service_tickets_managed_system_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :asset_id,
          references(:assets,
            column: :id,
            name: "execution_service_tickets_asset_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "execution_service_tickets_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :requester_user_id,
          references(:users,
            column: :id,
            name: "execution_service_tickets_requester_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "execution_service_tickets_owner_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:execution_service_tickets, [:ticket_number],
             name: "execution_service_tickets_unique_ticket_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(:execution_service_tickets, [:ticket_number],
                     name: "execution_service_tickets_unique_ticket_number_index"
                   )

    drop constraint(:execution_service_tickets, "execution_service_tickets_organization_id_fkey")

    drop constraint(:execution_service_tickets, "execution_service_tickets_site_id_fkey")

    drop constraint(
           :execution_service_tickets,
           "execution_service_tickets_managed_system_id_fkey"
         )

    drop constraint(:execution_service_tickets, "execution_service_tickets_asset_id_fkey")

    drop constraint(:execution_service_tickets, "execution_service_tickets_agreement_id_fkey")

    drop constraint(
           :execution_service_tickets,
           "execution_service_tickets_requester_user_id_fkey"
         )

    drop constraint(:execution_service_tickets, "execution_service_tickets_owner_user_id_fkey")

    alter table(:execution_service_tickets) do
      remove :owner_user_id
      remove :requester_user_id
      remove :agreement_id
      remove :asset_id
      remove :managed_system_id
      remove :site_id
      remove :organization_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :resolution_summary
      remove :closed_at
      remove :resolved_at
      remove :due_on
      remove :reported_at
      remove :impact
      remove :severity
      remove :status
      remove :source_channel
      remove :ticket_type
      remove :description
      remove :title
      remove :ticket_number
    end

    drop constraint(:execution_work_orders, "execution_work_orders_service_ticket_id_fkey")

    alter table(:execution_work_orders) do
      modify :service_ticket_id, :uuid
    end

    drop table(:execution_service_tickets)

    alter table(:execution_work_orders) do
      remove :service_ticket_id
    end
  end
end
