defmodule GnomeGarden.Repo.Migrations.AddMaintenancePlanGenerationTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:execution_maintenance_plans) do
      add :last_generated_due_on, :date
      add :generation_lead_days, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:execution_maintenance_plans) do
      remove :generation_lead_days
      remove :last_generated_due_on
    end
  end
end
