defmodule GnomeGarden.Repo.Migrations.DiscoveryLearningPolicy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:acquisition_program_sources) do
      add :learning_enabled, :boolean, null: false, default: true
      add :feedback_window_days, :bigint, null: false, default: 90
      add :learning_min_reviewed, :bigint, null: false, default: 3
      add :learning_noise_threshold, :decimal, null: false, default: "0.67"
    end
  end

  def down do
    alter table(:acquisition_program_sources) do
      remove :learning_noise_threshold
      remove :learning_min_reviewed
      remove :feedback_window_days
      remove :learning_enabled
    end
  end
end
