defmodule GnomeGarden.Repo.Migrations.AddEmploymentHistory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:employments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :department, :text
      add :role, :text
      add :started_at, :date
      add :ended_at, :date
      add :is_current, :boolean, null: false, default: true
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :contact_id,
          references(:contacts,
            column: :id,
            name: "employments_contact_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :company_id,
          references(:companies,
            column: :id,
            name: "employments_company_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:employments, [:contact_id, :company_id, :is_current],
             name: "employments_unique_current_employment_index",
             where: "(is_current = true)"
           )
  end

  def down do
    drop_if_exists unique_index(:employments, [:contact_id, :company_id, :is_current],
                     name: "employments_unique_current_employment_index"
                   )

    drop constraint(:employments, "employments_contact_id_fkey")

    drop constraint(:employments, "employments_company_id_fkey")

    drop table(:employments)
  end
end
