defmodule GnomeGarden.Repo.Migrations.FixLast4FieldNames do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:banking_accounts) do
      remove :account_number_last
      add :account_number_last4, :text
    end

    alter table(:banking_transactions) do
      remove :counterparty_account_last
      add :counterparty_account_last4, :text
    end
  end

  def down do
    alter table(:banking_transactions) do
      remove :counterparty_account_last4
      add :counterparty_account_last, :text
    end

    alter table(:banking_accounts) do
      remove :account_number_last4
      add :account_number_last, :text
    end
  end
end
