defmodule GnomeGarden.Repo.Migrations.AddLeadPreviewIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:acquisition_lead_preview_candidates, [:lead_preview_run_id])

    create index(:acquisition_lead_preview_runs, [:discovery_program_id, :inserted_at])

    create index(:acquisition_lead_preview_runs, [:inserted_at])
  end

  def down do
    drop_if_exists index(:acquisition_lead_preview_runs, [:inserted_at])

    drop_if_exists index(:acquisition_lead_preview_runs, [:discovery_program_id, :inserted_at])

    drop_if_exists index(:acquisition_lead_preview_candidates, [:lead_preview_run_id])
  end
end
