defmodule GnomeGarden.Repo.Migrations.AddProcurementSourceCredentials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:procurement_source_credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false, default: "custom"
      add :credential_family, :text, null: false
      add :scope, :text, null: false, default: "family"
      add :label, :text, null: false, default: "Default"
      add :username, :text
      add :encrypted_password, :map
      add :password_fingerprint, :text
      add :password_present, :boolean, null: false, default: false
      add :encrypted_api_key, :map
      add :api_key_fingerprint, :text
      add :api_key_present, :boolean, null: false, default: false
      add :status, :text, null: false, default: "active"
      add :last_verified_at, :utc_datetime
      add :last_used_at, :utc_datetime
      add :last_failure_reason, :text
      add :last_rotated_at, :utc_datetime
      add :notes, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :procurement_source_id,
          references(:procurement_sources,
            column: :id,
            name: "procurement_source_credentials_procurement_source_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:procurement_source_credentials, [:procurement_source_id, :status])

    create index(:procurement_source_credentials, [:credential_family, :status])
  end

  def down do
    drop constraint(
           :procurement_source_credentials,
           "procurement_source_credentials_procurement_source_id_fkey"
         )

    drop_if_exists index(:procurement_source_credentials, [:credential_family, :status])

    drop_if_exists index(:procurement_source_credentials, [:procurement_source_id, :status])

    drop table(:procurement_source_credentials)
  end
end
