defmodule GnomeGarden.Repo.Migrations.AddOperationsLearningRecommendations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:operations_learning_recommendations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :target_domain, :text, null: false
      add :target_resource, :text, null: false
      add :target_id, :uuid
      add :target_action, :text, null: false
      add :proposed_change, :map, null: false, default: %{}
      add :evidence, :map, null: false, default: %{}
      add :impact_summary, :text
      add :risk_level, :text, null: false, default: "medium"
      add :confidence, :decimal
      add :status, :text, null: false, default: "needs_review"
      add :source_type, :text, null: false, default: "agent"
      add :review_note, :text
      add :rejection_reason, :text
      add :reviewed_at, :utc_datetime
      add :applied_at, :utc_datetime
      add :expired_at, :utc_datetime
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_agent_run_id,
          references(:agent_runs,
            column: :id,
            name: "operations_learning_recommendations_source_agent_run_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :created_by_team_member_id,
          references(:team_members,
            column: :id,
            name: "operations_learning_recommendations_created_by_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :reviewer_team_member_id,
          references(:team_members,
            column: :id,
            name: "operations_learning_recommendations_reviewer_team_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:operations_learning_recommendations, [:source_type, :status])

    create index(:operations_learning_recommendations, [
             :target_domain,
             :target_resource,
             :target_id
           ])

    create index(:operations_learning_recommendations, [:status, :risk_level])
  end

  def down do
    drop constraint(
           :operations_learning_recommendations,
           "operations_learning_recommendations_source_agent_run_id_fkey"
         )

    drop constraint(
           :operations_learning_recommendations,
           "operations_learning_recommendations_created_by_team_member_id_fkey"
         )

    drop constraint(
           :operations_learning_recommendations,
           "operations_learning_recommendations_reviewer_team_member_id_fkey"
         )

    drop_if_exists index(:operations_learning_recommendations, [:status, :risk_level])

    drop_if_exists index(:operations_learning_recommendations, [
                     :target_domain,
                     :target_resource,
                     :target_id
                   ])

    drop_if_exists index(:operations_learning_recommendations, [:source_type, :status])

    drop table(:operations_learning_recommendations)
  end
end
