defmodule GnomeGarden.Repo.Migrations.AddBidSignalLinkage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bids) do
      add :signal_id,
          references(:commercial_signals,
            column: :id,
            name: "bids_signal_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:bids, "bids_signal_id_fkey")

    alter table(:bids) do
      remove :signal_id
    end
  end
end
