defmodule GnomeGarden.Repo.Migrations.RecurringInvoicesTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:finance_recurring_invoice_lines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :line_number, :bigint, null: false, default: 1
      add :line_kind, :text, null: false, default: "service"
      add :description, :text, null: false
      add :quantity, :decimal, null: false
      add :unit_price, :decimal, null: false
      add :line_total, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :recurring_invoice_id, :uuid, null: false
    end

    create table(:finance_recurring_invoices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:finance_recurring_invoice_lines) do
      modify :recurring_invoice_id,
             references(:finance_recurring_invoices,
               column: :id,
               name: "finance_recurring_invoice_lines_recurring_invoice_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:finance_recurring_invoices) do
      add :status, :text, null: false, default: "active"
      add :interval, :text, null: false
      add :net_terms_days, :bigint, null: false, default: 30
      add :start_date, :date, null: false
      add :end_date, :date
      add :next_generation_date, :date, null: false
      add :delivery_mode, :text, null: false, default: "auto_issue"
      add :tax_rate, :decimal, null: false, default: "0"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "finance_recurring_invoices_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "finance_recurring_invoices_agreement_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(
           :finance_recurring_invoices,
           "finance_recurring_invoices_organization_id_fkey"
         )

    drop constraint(:finance_recurring_invoices, "finance_recurring_invoices_agreement_id_fkey")

    alter table(:finance_recurring_invoices) do
      remove :agreement_id
      remove :organization_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :tax_rate
      remove :delivery_mode
      remove :next_generation_date
      remove :end_date
      remove :start_date
      remove :net_terms_days
      remove :interval
      remove :status
    end

    drop constraint(
           :finance_recurring_invoice_lines,
           "finance_recurring_invoice_lines_recurring_invoice_id_fkey"
         )

    alter table(:finance_recurring_invoice_lines) do
      modify :recurring_invoice_id, :uuid
    end

    drop table(:finance_recurring_invoices)

    drop table(:finance_recurring_invoice_lines)
  end
end
