defmodule GnomeGarden.Repo.Migrations.ChangeAnnualRevenueToMoney do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute """
    ALTER TABLE companies
    ALTER COLUMN annual_revenue TYPE money_with_currency
    USING CASE
      WHEN annual_revenue IS NOT NULL THEN ROW('USD', annual_revenue)::money_with_currency
      ELSE NULL
    END
    """
  end

  def down do
    alter table(:companies) do
      modify :annual_revenue, :decimal
    end
  end
end
