defmodule GnomeGarden.Repo.Migrations.AddServiceEntitlements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_service_entitlement_usages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_type, :text, null: false, default: "manual_adjustment"
      add :usage_on, :date, null: false
      add :quantity, :decimal, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "commercial_service_entitlement_usages_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :service_entitlement_id, :uuid, null: false
      add :time_entry_id, :uuid
      add :expense_id, :uuid
      add :work_order_id, :uuid
    end

    create table(:commercial_service_entitlements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:commercial_service_entitlement_usages) do
      modify :service_entitlement_id,
             references(:commercial_service_entitlements,
               column: :id,
               name: "commercial_service_entitlement_usages_service_entitlement_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :time_entry_id,
             references(:finance_time_entries,
               column: :id,
               name: "commercial_service_entitlement_usages_time_entry_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :expense_id,
             references(:finance_expenses,
               column: :id,
               name: "commercial_service_entitlement_usages_expense_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :work_order_id,
             references(:execution_work_orders,
               column: :id,
               name: "commercial_service_entitlement_usages_work_order_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:commercial_service_entitlements) do
      add :name, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "draft"
      add :entitlement_type, :text, null: false, default: "labor"
      add :quantity_unit, :text, null: false, default: "hour"
      add :included_quantity, :decimal, null: false
      add :renewal_cadence, :text, null: false, default: "contract_term"
      add :carryover_mode, :text, null: false, default: "none"
      add :overage_billing_model, :text, null: false, default: "bill_at_agreement_rate"
      add :start_on, :date
      add :end_on, :date
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :agreement_id,
          references(:commercial_agreements,
            column: :id,
            name: "commercial_service_entitlements_agreement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :service_level_policy_id,
          references(:commercial_service_level_policies,
            column: :id,
            name: "commercial_service_entitlements_service_level_policy_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:commercial_service_entitlements, [:agreement_id, :name],
             name: "cse_agreement_name_idx"
           )
  end

  def down do
    drop_if_exists unique_index(:commercial_service_entitlements, [:agreement_id, :name],
                     name: "cse_agreement_name_idx"
                   )

    drop constraint(
           :commercial_service_entitlements,
           "commercial_service_entitlements_agreement_id_fkey"
         )

    drop constraint(
           :commercial_service_entitlements,
           "commercial_service_entitlements_service_level_policy_id_fkey"
         )

    alter table(:commercial_service_entitlements) do
      remove :service_level_policy_id
      remove :agreement_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :end_on
      remove :start_on
      remove :overage_billing_model
      remove :carryover_mode
      remove :renewal_cadence
      remove :included_quantity
      remove :quantity_unit
      remove :entitlement_type
      remove :status
      remove :description
      remove :name
    end

    drop constraint(
           :commercial_service_entitlement_usages,
           "commercial_service_entitlement_usages_service_entitlement_id_fkey"
         )

    drop constraint(
           :commercial_service_entitlement_usages,
           "commercial_service_entitlement_usages_time_entry_id_fkey"
         )

    drop constraint(
           :commercial_service_entitlement_usages,
           "commercial_service_entitlement_usages_expense_id_fkey"
         )

    drop constraint(
           :commercial_service_entitlement_usages,
           "commercial_service_entitlement_usages_work_order_id_fkey"
         )

    alter table(:commercial_service_entitlement_usages) do
      modify :work_order_id, :uuid
      modify :expense_id, :uuid
      modify :time_entry_id, :uuid
      modify :service_entitlement_id, :uuid
    end

    drop table(:commercial_service_entitlements)

    drop constraint(
           :commercial_service_entitlement_usages,
           "commercial_service_entitlement_usages_agreement_id_fkey"
         )

    drop table(:commercial_service_entitlement_usages)
  end
end
