defmodule GnomeGarden.Repo.Migrations.AddRetainers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "CREATE SEQUENCE IF NOT EXISTS finance_retainer_number_seq START 1"

    create table(:finance_retainers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :retainer_number, :text
      add :status, :text, null: false, default: "draft"
      add :amount, :decimal, null: false
      add :auto_apply, :boolean, null: false, default: false
      add :received_on, :date
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "finance_retainers_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create table(:finance_retainer_applications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :retainer_id,
          references(:finance_retainers,
            column: :id,
            name: "finance_retainer_applications_retainer_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(
           :finance_retainer_applications,
           "finance_retainer_applications_retainer_id_fkey"
         )

    drop table(:finance_retainer_applications)

    drop constraint(:finance_retainers, "finance_retainers_organization_id_fkey")

    drop table(:finance_retainers)

    execute "DROP SEQUENCE IF EXISTS finance_retainer_number_seq"
  end
end
