defmodule GnomeGarden.Repo.Migrations.AddOrganizationWebsiteDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :website_domain, :text
    end

    create unique_index(:organizations, [:website_domain],
             name: "organizations_unique_website_domain_index"
           )
  end

  def down do
    drop_if_exists unique_index(:organizations, [:website_domain],
                     name: "organizations_unique_website_domain_index"
                   )

    alter table(:organizations) do
      remove :website_domain
    end
  end
end
