defmodule GnomeGarden.Repo.Migrations.FinanceBankingFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:finance_bank_transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false, default: "mercury"
      add :provider_transaction_id, :text, null: false
      add :amount, :decimal, null: false
      add :direction, :text, null: false
      add :kind, :text, null: false, default: "other"
      add :status, :text, null: false, default: "posted"
      add :occurred_at, :utc_datetime_usec, null: false
      add :posted_at, :utc_datetime_usec
      add :description, :text
      add :memo, :text
      add :counterparty_id, :text
      add :counterparty_name, :text
      add :counterparty_account_last4, :text
      add :dashboard_link, :text
      add :raw_provider_payload, :map
      add :category, :text, null: false, default: "unknown"
      add :review_status, :text, null: false, default: "needs_review"
      add :match_status, :text, null: false, default: "unmatched"
      add :match_confidence, :text
      add :reconciliation_note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_account_id, :uuid, null: false
    end

    create unique_index(:finance_bank_transactions, [:provider, :provider_transaction_id],
             name: "finance_bank_transactions_unique_provider_transaction_index"
           )

    create table(:finance_bank_connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false, default: "mercury"
      add :name, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :environment, :text, null: false, default: "production"
      add :last_synced_at, :utc_datetime_usec
      add :last_successful_sync_at, :utc_datetime_usec
      add :last_error_at, :utc_datetime_usec
      add :last_error_message, :text
      add :sync_cursor, :map
      add :settings, :map, default: %{}
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:finance_bank_connections, [:provider, :environment],
             name: "finance_bank_connections_unique_provider_environment_index"
           )

    create table(:finance_bank_sync_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "running"
      add :source, :text, null: false, default: "manual_sync"

      add :started_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :finished_at, :utc_datetime_usec
      add :accounts_seen_count, :bigint, default: 0
      add :transactions_seen_count, :bigint, default: 0
      add :transactions_created_count, :bigint, default: 0
      add :transactions_updated_count, :bigint, default: 0
      add :error_message, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_connection_id,
          references(:finance_bank_connections,
            column: :id,
            name: "finance_bank_sync_runs_bank_connection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create table(:finance_bank_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:finance_bank_transactions) do
      modify :bank_account_id,
             references(:finance_bank_accounts,
               column: :id,
               name: "finance_bank_transactions_bank_account_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:finance_bank_accounts) do
      add :provider, :text, null: false, default: "mercury"
      add :provider_account_id, :text, null: false
      add :name, :text, null: false
      add :nickname, :text
      add :legal_business_name, :text
      add :status, :text, null: false, default: "active"
      add :kind, :text, null: false
      add :currency_code, :text, null: false, default: "USD"
      add :current_balance, :decimal
      add :available_balance, :decimal
      add :balance_as_of, :utc_datetime_usec
      add :routing_number, :text
      add :wire_routing_number, :text
      add :account_number_last4, :text
      add :account_number_encrypted, :text
      add :dashboard_id, :text
      add :raw_provider_payload, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_connection_id,
          references(:finance_bank_connections,
            column: :id,
            name: "finance_bank_accounts_bank_connection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:finance_bank_accounts, [:provider, :provider_account_id],
             name: "finance_bank_accounts_unique_provider_account_index"
           )

    create table(:finance_bank_rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :enabled, :boolean, null: false, default: true
      add :priority, :bigint, null: false, default: 0
      add :direction, :text, null: false, default: "both"
      add :description_contains, :text
      add :counterparty_contains, :text
      add :amount_operator, :text
      add :amount_value, :decimal
      add :category, :text, null: false, default: "unknown"
      add :review_status_result, :text, null: false, default: "reviewed"
      add :match_behavior, :text, null: false, default: "none"
      add :auto_note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:finance_bank_transaction_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :source, :text, null: false
      add :message, :text
      add :metadata, :map, default: %{}
      add :actor_id, :uuid
      add :amount, :decimal
      add :invoice_ids, {:array, :uuid}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_transaction_id,
          references(:finance_bank_transactions,
            column: :id,
            name: "finance_bank_transaction_events_bank_transaction_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create table(:finance_bank_counterparty_aliases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :counterparty_name, :text, null: false
      add :normalized_name, :text, null: false
      add :confidence, :decimal
      add :source, :text, null: false, default: "operator"
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "finance_bank_counterparty_aliases_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:finance_bank_counterparty_aliases, [:normalized_name],
             name: "finance_bank_counterparty_uidx"
           )

    create table(:finance_bank_transaction_matches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :match_source, :text, null: false
      add :status, :text, null: false, default: "suggested"
      add :confidence, :text, null: false, default: "possible"
      add :matched_at, :utc_datetime_usec
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_transaction_id,
          references(:finance_bank_transactions,
            column: :id,
            name: "finance_bank_transaction_matches_bank_transaction_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :payment_id,
          references(:finance_payments,
            column: :id,
            name: "finance_bank_transaction_matches_payment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :invoice_id,
          references(:finance_invoices,
            column: :id,
            name: "finance_bank_transaction_matches_invoice_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:finance_bank_transaction_matches, [:bank_transaction_id, :payment_id],
             name: "finance_bank_txn_payment_uidx"
           )

    create table(:finance_bank_integration_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false, default: "mercury"
      add :provider_event_id, :text
      add :event_type, :text, null: false
      add :source, :text, null: false
      add :status, :text, null: false, default: "received"
      add :payload, :map

      add :received_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :processed_at, :utc_datetime_usec
      add :error_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bank_connection_id,
          references(:finance_bank_connections,
            column: :id,
            name: "finance_bank_integration_events_bank_connection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :bank_account_id,
          references(:finance_bank_accounts,
            column: :id,
            name: "finance_bank_integration_events_bank_account_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :bank_transaction_id,
          references(:finance_bank_transactions,
            column: :id,
            name: "finance_bank_integration_events_bank_transaction_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:finance_bank_integration_events, [:provider, :provider_event_id],
             name: "finance_bank_integration_events_unique_provider_event_index"
           )
  end

  def down do
    drop constraint(
           :finance_bank_integration_events,
           "finance_bank_integration_events_bank_connection_id_fkey"
         )

    drop constraint(
           :finance_bank_integration_events,
           "finance_bank_integration_events_bank_account_id_fkey"
         )

    drop constraint(
           :finance_bank_integration_events,
           "finance_bank_integration_events_bank_transaction_id_fkey"
         )

    drop_if_exists unique_index(:finance_bank_integration_events, [:provider, :provider_event_id],
                     name: "finance_bank_integration_events_unique_provider_event_index"
                   )

    drop table(:finance_bank_integration_events)

    drop constraint(
           :finance_bank_transaction_matches,
           "finance_bank_transaction_matches_bank_transaction_id_fkey"
         )

    drop constraint(
           :finance_bank_transaction_matches,
           "finance_bank_transaction_matches_payment_id_fkey"
         )

    drop constraint(
           :finance_bank_transaction_matches,
           "finance_bank_transaction_matches_invoice_id_fkey"
         )

    drop_if_exists unique_index(
                     :finance_bank_transaction_matches,
                     [:bank_transaction_id, :payment_id], name: "finance_bank_txn_payment_uidx")

    drop table(:finance_bank_transaction_matches)

    drop constraint(
           :finance_bank_counterparty_aliases,
           "finance_bank_counterparty_aliases_organization_id_fkey"
         )

    drop_if_exists unique_index(:finance_bank_counterparty_aliases, [:normalized_name],
                     name: "finance_bank_counterparty_uidx"
                   )

    drop table(:finance_bank_counterparty_aliases)

    drop constraint(
           :finance_bank_transaction_events,
           "finance_bank_transaction_events_bank_transaction_id_fkey"
         )

    drop table(:finance_bank_transaction_events)

    drop table(:finance_bank_rules)

    drop constraint(:finance_bank_accounts, "finance_bank_accounts_bank_connection_id_fkey")

    drop_if_exists unique_index(:finance_bank_accounts, [:provider, :provider_account_id],
                     name: "finance_bank_accounts_unique_provider_account_index"
                   )

    alter table(:finance_bank_accounts) do
      remove :bank_connection_id
      remove :updated_at
      remove :inserted_at
      remove :raw_provider_payload
      remove :dashboard_id
      remove :account_number_encrypted
      remove :account_number_last4
      remove :wire_routing_number
      remove :routing_number
      remove :balance_as_of
      remove :available_balance
      remove :current_balance
      remove :currency_code
      remove :kind
      remove :status
      remove :legal_business_name
      remove :nickname
      remove :name
      remove :provider_account_id
      remove :provider
    end

    drop constraint(:finance_bank_transactions, "finance_bank_transactions_bank_account_id_fkey")

    alter table(:finance_bank_transactions) do
      modify :bank_account_id, :uuid
    end

    drop table(:finance_bank_accounts)

    drop constraint(:finance_bank_sync_runs, "finance_bank_sync_runs_bank_connection_id_fkey")

    drop table(:finance_bank_sync_runs)

    drop_if_exists unique_index(:finance_bank_connections, [:provider, :environment],
                     name: "finance_bank_connections_unique_provider_environment_index"
                   )

    drop table(:finance_bank_connections)

    drop_if_exists unique_index(:finance_bank_transactions, [:provider, :provider_transaction_id],
                     name: "finance_bank_transactions_unique_provider_transaction_index"
                   )

    drop table(:finance_bank_transactions)
  end
end
