defmodule GnomeGarden.Repo.Migrations.UnifiedDiscoveryAndReview do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:leads) do
      add :rejection_reason, :text
      add :rejection_notes, :text
    end

    alter table(:lead_sources) do
      add :company_id,
          references(:companies,
            column: :id,
            name: "lead_sources_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:companies) do
      add :review_status, :text, null: false, default: "new"
      add :rejection_reason, :text
      add :rejection_notes, :text
      add :snoozed_until, :utc_datetime
    end
  end

  def down do
    alter table(:companies) do
      remove :snoozed_until
      remove :rejection_notes
      remove :rejection_reason
      remove :review_status
    end

    drop constraint(:lead_sources, "lead_sources_company_id_fkey")

    alter table(:lead_sources) do
      remove :company_id
    end

    alter table(:leads) do
      remove :rejection_notes
      remove :rejection_reason
    end
  end
end
