defmodule GnomeGarden.Repo.Migrations.FinalizeLeadSourceStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lead_sources) do
      modify :status, :text, null: false
      modify :portal_id, :text, null: true
    end
  end

  def down do
    alter table(:lead_sources) do
      modify :portal_id, :text, null: false
      modify :status, :text, null: true
    end
  end
end
