defmodule GnomeGarden.Repo.Migrations.AddCommercialDiscoveryRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commercial_discovery_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idempotency_key, :text, null: false
      add :trigger, :text, null: false
      add :status, :text, null: false, default: "queued"
      add :query_provenance, :map, null: false, default: %{}
      add :reserved_cost, :decimal, null: false, default: "0"
      add :actual_cost, :decimal, null: false, default: "0"
      add :query_count, :bigint, null: false, default: 0
      add :candidate_count, :bigint, null: false, default: 0
      add :promotable_count, :bigint, null: false, default: 0
      add :attempt_count, :bigint, null: false, default: 0
      add :attempt_history, {:array, :map}, null: false, default: []
      add :lead_preview_run_id, :uuid
      add :requested_by_id, :uuid
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
      add :terminal_diagnostics, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :discovery_program_id,
          references(:commercial_discovery_programs,
            column: :id,
            name: "commercial_discovery_runs_discovery_program_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:commercial_discovery_runs, [:status, :updated_at],
             name: "discovery_runs_status_updated_index"
           )

    create index(:commercial_discovery_runs, [:discovery_program_id, :inserted_at],
             name: "discovery_runs_program_inserted_index"
           )

    create unique_index(:commercial_discovery_runs, [:idempotency_key],
             name: "commercial_discovery_runs_unique_idempotency_key_index"
           )
  end

  def down do
    drop constraint(
           :commercial_discovery_runs,
           "commercial_discovery_runs_discovery_program_id_fkey"
         )

    drop_if_exists unique_index(:commercial_discovery_runs, [:idempotency_key],
                     name: "commercial_discovery_runs_unique_idempotency_key_index"
                   )

    drop_if_exists index(:commercial_discovery_runs, [:discovery_program_id, :inserted_at],
                     name: "discovery_runs_program_inserted_index"
                   )

    drop_if_exists index(:commercial_discovery_runs, [:status, :updated_at],
                     name: "discovery_runs_status_updated_index"
                   )

    drop table(:commercial_discovery_runs)
  end
end
